### ISSUE TITLE
sbt can't find com.twitter.common.zookeeper dependency when building marathon from source

### ISSUE THREAD

**Issue by solarkennedy** [mesosphere/marathon#1457]
```
[info] Resolving com.twitter.common.zookeeper#candidate;0.0.76 ...
[warn]     module not found: com.twitter.common.zookeeper#candidate;0.0.76
[warn] ==== local: tried
[warn]   /home/aslan/.ivy2/local/com.twitter.common.zookeeper/candidate/0.0.76/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/twitter/common/zookeeper/candidate/0.0.76/candidate-0.0.76.pom
[warn] ==== Mesosphere Public Repo: tried
[warn]   http://downloads.mesosphere.io/maven/com/twitter/common/zookeeper/candidate/0.0.76/candidate-0.0.76.pom
[warn] ==== Typesafe Releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/twitter/common/zookeeper/candidate/0.0.76/candidate-0.0.76.pom
[warn] ==== Spray Maven Repository: tried
[warn]   http://repo.spray.io/com/twitter/common/zookeeper/candidate/0.0.76/candidate-0.0.76.pom
[info] Resolving jline#jline;2.12 ...
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     ::          UNRESOLVED DEPENDENCIES         ::
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     :: com.twitter.common.zookeeper#candidate;0.0.76: not found
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: com.twitter.common.zookeeper#candidate;0.0.76: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)

Also could not find com.twitter.common.zookeeper in tried repos
```

If you hint at me how I could fix this I could give it a shot?

**Comment by drexin** [comment]
Hi,

I added a mirror of the libraries to the mesosphere repo and the travis build works again. Could you please try if it works for you as well?

Thanks,
Dario

**Comment by ConnorDoyle** [comment]
@drexin - I think this is affecting the Docker ABR as well.  That means we won't have a tagged image for version `0.8.2` on DockerHub until we cherry-pick your change on top of that tag.  DockerHub doesn't let you push to ABR repos, otherwise we could push from a machine that has the artifact in cache.  Our CI servers must have also cached this dependency, which prevented us from finding the problem.

**Comment by drexin** [comment]
Does it still not work? I mirrored the libraries on the Mesosphere repo.

**Comment by ConnorDoyle** [comment]
Kicking a new build now...

**Comment by ConnorDoyle** [comment]
Sorry, I misunderstood your fix (thought you added an additional resolver).  We should be able to publish from the original tag with the problematic artifact hosted in our existing repo.

**Comment by solarkennedy** [comment]
This is working for me. I'm ok with closing if things work on your ends.

**Comment by drexin** [comment]
Thanks.

**Comment by ConnorDoyle** [comment]
+1, Docker build is working again.
