### ISSUE TITLE
can't get list of group versions

### ISSUE THREAD

**Issue by tamarrow** [mesosphere/marathon#1458]
GET /v2/groups/group-id/versions 

returns

 "message": "Failed to wait for future within timeout"

**Comment by kolloch** [comment]
We apparently do not limit the number of versions we keep. Therefore, if the list of versions become very long, you might run into the trouble you are seeing.

We definitely should restrict the number of versions we keep.

Nevertheless, I would really like to check if my theory about your problem is true. Would it be possible for you to create stack traces of the Marathon process shortly after issuing the request (before it finishes)? You can do that by `kill -3` or using the `jstack` command.

Thanks!

**Comment by bobrik** [comment]
@kolloch is there an issue to limit version history?

**Comment by kolloch** [comment]
@bobrik now there is.

**Comment by aquamatthias** [comment]
Hey @tamarrow do you have limited the number of versions in the store?
The problem you describe can be a result of too many versions.
Use the command line option --zk_max_versions to limit the number of versions stored per entity.

**Comment by tamarrow** [comment]
I limited the number to 3, but I still get the same timeout issue. This is the stacktrace I get from Marathon:
```
[2015-05-13 17:32:29,158] WARN error while calling class mesosphere.marathon.state.MarathonStore.names() for prefix app: (mesosphere.marathon.state.MarathonStore:131)
java.util.concurrent.TimeoutException: Failed to wait for future within timeout
	at org.apache.mesos.state.AbstractState.__names_get_timeout(Native Method)
	at org.apache.mesos.state.AbstractState.access$2200(AbstractState.java:34)
	at org.apache.mesos.state.AbstractState$4.get(AbstractState.java:209)
	at org.apache.mesos.state.AbstractState$4.get(AbstractState.java:181)
	at mesosphere.util.BackToTheFuture$$anonfun$futureToFuture$1$$anonfun$apply$2.apply(BackToTheFuture.scala:35)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:123)
	at mesosphere.util.BackToTheFuture$$anonfun$futureToFuture$1.apply(BackToTheFuture.scala:33)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by aquamatthias** [comment]
Just to make sure: Only restarting marathon with this option does not have any effect, until you change an entity. The limit kicks in after a new version (of that entity) has been created. To see the current state in zookeeper, you can list the marathon state:

```
$> zkCli
[zk: localhost:2181(CONNECTED) 0] ls /marathon/state
```
The path `/marathon/` is the configured default - please replace with your location.

Then you see all items in all versions. 
Do you see _a lot_ of items here, or only the defined number of max versions per item?
If you increase the timeout with `--zk_timeout` does the problem still remains?

**Comment by aquamatthias** [comment]
Hey @tamarrow would be nice if you could try this out with 0.9.0-RC1. Does this problem still exists?

**Comment by tamarrow** [comment]
works for me!

**Comment by aquamatthias** [comment]
I will close this ticket then.
