### ISSUE TITLE
Test output is too noizy

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1586]
A lot of unrelated stuff is printed when you run `sbt test`: offer matching, deployment plans, dead letters from akka, debug output, etc. Let's keep it clean.

On a related note, I see NPEs, but test don't fail, this is very confusing:

```
[info] - names() correctly uses timeouts
[2015-05-29 19:13:57,492] WARN error while calling class mesosphere.marathon.state.MarathonStore.names() for prefix app: (mesosphere.marathon.state.MarathonStore:131)
java.lang.NullPointerException
    at mesosphere.util.BackToTheFuture$$anonfun$futureToFuture$1$$anonfun$apply$2.apply(BackToTheFuture.scala:38)
    at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
    at scala.concurrent.package$.blocking(package.scala:123)
    at mesosphere.util.BackToTheFuture$$anonfun$futureToFuture$1.apply(BackToTheFuture.scala:33)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I'm too scared to check if #1558 can improve things in prod.

**Comment by kolloch** [comment]
Hi @bobrik,

maybe one can introduce an option for a low noise test run. But I wouldn't make it silent on default. If you run tests and something fails, you want to see why.

Running tests is meant for Marathon developers and not for ops.

About the NPE that you have mentioned:

Probably, we should rename this NPE. It is unfortunately, normal, when running Marathon against a virgin Zookeeper without data.

A bug in the library in Mesos 0.22.1 prevents us from distinguish this error case from others (because we always get NPEs, not matter what the error is).

**Comment by bobrik** [comment]
Option would work for me. When I change the code I see myself as a developer, not ops. The problem is that  I cannot say if tests failed or not, I don't yet have a problem to figure out why tests failed.

**Comment by kolloch** [comment]
Write a test that fails. Basically, if a test fails, it is printed at the end of the test run and the return code should be non-zero.

Feel free to create a PR for a non-noisy test output flag.

**Comment by timcharper** [comment]
Closing due to inactivity.

As a work-around, you can run a single test with this:

```
$ sbt

marathon(master)> set testOptions in Test := Nil

[info] Defining marathon/test:testOptions
[info] The new value will be used by marathon/test:test::testOptions, marathon/test:testOnly::testOptions, marathon/test:testQuick::testOptions
[info] Reapplying settings...
[info] Set current project to marathon (in build file:/Users/tim/src/m8e/marathon/)

marathon(master)> test-only mesosphere.marathon.integration.ResidentTaskIntegrationTest -- -z "Scale Up"
```

Running a single test should help you sort through the noise. I hope this is sufficient @bobrik ! Feel free to suggest something else.
