### ISSUE TITLE
when marathon start and  raise java.lang.NullPointerException

### ISSUE THREAD

**Issue by istrike** [mesosphere/marathon#1626]
mesos:0.22.1
marathon:0.8.2

when i start mesos-master and mesos-slave with this command:
 
### 
 ```
 mesos-master \
--ip=192.168.1.147 \
--hostname=mesos.master147.local \
--work_dir=/tmp/mesos/master \
--log_dir=/tmp/mesos/master_log 
```

``` 
/opt/mesos/sbin/mesos-slave\
--containerizers=mesos,docker \
--work_dir=/tmp/mesos/slave \
--log_dir=/tmp/mesos/slave_log \
--master=192.168.1.147:5050  \
--ip=192.168.1.147 \
--hostname=mesos.slave147.local  \
--resources="ports(*):[5000-60000,5000-60000]"
 ```

and tested with mesos-execute it works ok,

when i starting marathon with this command:
 ``` 
./bin/start --master 192.168.1.147:5050 \
-z 192.168.1.147:2181/marathonTesting1 \
--log_level trace
 ```

it raise some warn then  make some test deploy  docker service it not work ,

```
[2015-06-08 23:55:47,214] WARN error while calling class mesosphere.marathon.state.MarathonStore.names() for prefix app: (mesosphere.marathon.state.MarathonStore:131)
java.lang.NullPointerException
	at mesosphere.util.BackToTheFuture$$anonfun$futureToFuture$1$$anonfun$apply$2.apply(BackToTheFuture.scala:38)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:123)
	at mesosphere.util.BackToTheFuture$$anonfun$futureToFuture$1.apply(BackToTheFuture.scala:33)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-06-08 23:55:47,215] INFO Migration for storage: Version(0, 0, 0) to current: Version(0, 8, 2): apply change for version: Version(0, 7, 0)  (mesosphere.marathon.state.Migration:53)
[2015-06-08 23:55:47,214] INFO Binding mesosphere.marathon.api.v2.SchemaResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
[2015-06-08 23:55:47,226] WARN error while calling class mesosphere.marathon.state.MarathonStore.names() for prefix app: (mesosphere.marathon.state.MarathonStore:131)
java.lang.NullPointerException
	at mesosphere.util.BackToTheFuture$$anonfun$futureToFuture$1$$anonfun$apply$2.apply(BackToTheFuture.scala:38)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:123)
	at mesosphere.util.BackToTheFuture$$anonfun$futureToFuture$1.apply(BackToTheFuture.scala:33)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kolloch** [comment]
Hi @istrike, 

Unfortunately, this is normal if your Zookeeper didn't contain any data yet. Unfortunately, we cannot distinguish between error cases because of the Mesos State API. We have filed a bug for that in Mesos.

We will make the WARNing more clear in a future release.
