### ISSUE TITLE
Integration Tests currently shaky

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1655]
Make them work reliably again.

**Comment by kolloch** [comment]
This is the log of a failing integration test. It seems that for some reason the last TASK_RUNNING isn't propagated to Marathon.

https://gist.github.com/kolloch/081b41bb8dbbd23223fb

**Comment by meichstedt** [comment]
I keep getting these once in a while:
```
[15:57:57][Step 3/3] Reporter completed abruptly with an exception after receiving event: TestSucceeded(Ordinal(0, 484),InMemoryStoreTest,mesosphere.util.state.memory.InMemoryStoreTest,Some(mesosphere.util.state.memory.InMemoryStoreTest),Create node is successful,Create node is successful,Vector(),Some(16),Some(IndentedText(- Create node is successful,Create node is successful,0)),Some(LineInFile(25,IntegrationFunSuite.scala)),Some(mesosphere.util.state.memory.InMemoryStoreTest),None,pool-1-thread-1-ScalaTest-running-InMemoryStoreTest,1436544243518).
[15:57:57][Step 3/3] java.net.SocketException: Broken pipe
[15:57:57][Step 3/3] 	at java.net.SocketOutputStream.socketWrite0(Native Method)
[15:57:57][Step 3/3] 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
[15:57:57][Step 3/3] 	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
[15:57:57][Step 3/3] 	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1876)
[15:57:57][Step 3/3] 	at java.io.ObjectOutputStream$BlockDataOutputStream.writeByte(ObjectOutputStream.java:1914)
[15:57:57][Step 3/3] 	at java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1575)
[15:57:57][Step 3/3] 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
[15:57:57][Step 3/3] 	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
[15:57:57][Step 3/3] 	at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:240)
[15:57:57][Step 3/3] 	at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:239)
[15:57:57][Step 3/3] 	at scala.collection.immutable.List.foreach(List.scala:381)
[15:57:57][Step 3/3] 	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:239)
[15:57:57][Step 3/3] 	at java.lang.Thread.run(Thread.java:745)
```
see [here](https://teamcity.mesosphere.io/viewLog.html?buildId=25007&buildTypeId=Oss_Marathon_IntegrationScaleTests&tab=buildLog#_focus=30651) for an example.

**Comment by aquamatthias** [comment]
I checked the failing integration tests over the last days. These is the result:

- 4 times: AppDeployIntegrationTest: rollback a deployment 
- 3 times: AppDeployIntegrationTest:  stop (forcefully delete) 
- 3 times: GroupDeployIntegrationTest: Groups with dependant Applications get upgraded in 
- 2 times: Reporter completed abruptly with an exception after receiving event: SuiteCompleted(Ordinal(0, 411),LeaderIntegrationTest

```
AppDeployIntegrationTest:
[14:41:16][Step 3/3] 
[14:41:16][Step 3/3] - rollback a deployment *** FAILED *** (198 milliseconds)
[14:41:16][Step 3/3]   List(Deployment(e7bba467-8e08-4374-9581-b60c37c07087,List(/marathonintegrationtest/failing))) had size 1 instead of expected size 0 (AppDeployIntegrationTest.scala:441)

AppDeployIntegrationTest:
[12:03:08][Step 3/3] 
[12:03:08][Step 3/3] - stop (forcefully delete) a deployment *** FAILED *** (60 milliseconds)
[12:03:08][Step 3/3]   List() had size 0 instead of expected size 1 (AppDeployIntegrationTest.scala:408)

GroupDeployIntegrationTest:
[14:06:47][Step 3/3] 
[14:06:47][Step 3/3] - Groups with dependant Applications get upgraded in the correct order with maintained upgrade strategy *** FAILED *** (30 seconds, 100 milliseconds)
[14:06:47][Step 3/3]   java.lang.AssertionError: Waiting for event deployment_success to arrive took longer than 30 seconds. Give up.

 Reporter completed abruptly with an exception after receiving event: SuiteCompleted(Ordinal(0, 398),LeaderIntegrationTest,mesosphere.marathon.integration.LeaderIntegrationTest,Some(mesosphere.marathon.integration.LeaderIntegrationTest),Some(18102),Some(MotionToSuppress),Some(TopOfClass(mesosphere.marathon.integration.LeaderIntegrationTest)),None,None,pool-1-thread-1,1436797854130).
[14:24:44][Step 3/3] java.net.SocketException: Broken pipe
```

**Comment by aquamatthias** [comment]
We fixed the named integration tests. 
If we experience problems with specific integration tests, we should make specific tickets.
This one is to broad and will probably never be closed.
