### ISSUE TITLE
java.lang.NoClassDefFoundError: java/util/concurrent/ThreadLocalRandom

### ISSUE THREAD

**Issue by zbzoch** [mesosphere/marathon#2017]
Marathon 0.10.0 produces exception on startup:

```
[INFO] [08/17/2015 11:21:40.372] [marathon-akka.actor.default-dispatcher-4] [akka://marathon/user/offerReviver] Starting up
[2015-08-17 11:21:40,386] INFO Initiating client connection, connectString=10.12.3.0:2181 sessionTimeout=1800000 watcher=com.twitter.zk.EventBroker@7ef1accd (org.apache.zookeeper.ZooKeeper:438)
[2015-08-17 11:21:40,389] INFO Opening socket connection to server 10.12.3.0/10.12.3.0:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn:975)
[2015-08-17 11:21:40,389] INFO Socket connection established to 10.12.3.0/10.12.3.0:2181, initiating session (org.apache.zookeeper.ClientCnxn:852)
Exception in thread "main" java.lang.NoClassDefFoundError: java/util/concurrent/ThreadLocalRandom
        at com.twitter.concurrent.LocalScheduler$Activation.<init>(Scheduler.scala:119)
        at com.twitter.concurrent.LocalScheduler.com$twitter$concurrent$LocalScheduler$$get(Scheduler.scala:201)
        at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:216)
        at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:84)
        at com.twitter.util.Promise.runq(Promise.scala:338)
        at com.twitter.util.Promise.updateIfEmpty(Promise.scala:664)
        at com.twitter.util.Promise.update(Promise.scala:642)
        at com.twitter.concurrent.Serialized$Job.apply(Serialized.scala:18)
        at com.twitter.concurrent.Serialized$$anonfun$serialized$1.apply$mcV$sp(Serialized.scala:32)
        at com.twitter.concurrent.Serialized$$anonfun$serialized$1.apply(Serialized.scala:32)
        at com.twitter.concurrent.Serialized$$anonfun$serialized$1.apply(Serialized.scala:32)
        at com.twitter.util.Try$.apply(Try.scala:13)
        at com.twitter.concurrent.Serialized$class.serialized(Serialized.scala:32)
        at com.twitter.zk.NativeConnector.serialized(NativeConnector.scala:12)
        at com.twitter.zk.NativeConnector.apply(NativeConnector.scala:43)
        at com.twitter.zk.ZkClient$class.apply(ZkClient.scala:32)
        at com.twitter.zk.ZkClient$$anon$1.apply(ZkClient.scala:73)
        at com.twitter.zk.ZkClient$$anonfun$retrying$1.apply(ZkClient.scala:66)
        at com.twitter.zk.ZkClient$$anonfun$retrying$1.apply(ZkClient.scala:66)
        at com.twitter.zk.RetryPolicy$Basic.com$twitter$zk$RetryPolicy$Basic$$retry$1(RetryPolicy.scala:29)
        at com.twitter.zk.RetryPolicy$Basic.apply(RetryPolicy.scala:33)
        at com.twitter.zk.ZkClient$class.retrying(ZkClient.scala:66)
        at com.twitter.zk.ZkClient$$anon$1.retrying(ZkClient.scala:73)
        at com.twitter.zk.ZNode$$anon$7.apply(ZNode.scala:176)
        at mesosphere.util.state.zk.ZKStore.createParent$1(ZKStore.scala:95)
        at mesosphere.util.state.zk.ZKStore.createPathBlocking(ZKStore.scala:105)
        at mesosphere.util.state.zk.ZKStore.<init>(ZKStore.scala:25)
        at mesosphere.marathon.MarathonModule.directZK$1(MarathonModule.scala:131)
        at mesosphere.marathon.MarathonModule.provideStore(MarathonModule.scala:143)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:622)
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at mesosphere.chaos.App$class.injector(App.scala:17)
        at mesosphere.marathon.MarathonApp.injector$lzycompute(Main.scala:17)
        at mesosphere.marathon.MarathonApp.injector(Main.scala:17)
        at mesosphere.chaos.App$$anonfun$run$2.apply(App.scala:35)
        at mesosphere.chaos.App$$anonfun$run$2.apply(App.scala:34)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at mesosphere.chaos.App$class.run(App.scala:34)
        at mesosphere.marathon.MarathonApp.run(Main.scala:17)
        at mesosphere.marathon.MarathonApp.runDefault(Main.scala:88)
        at mesosphere.marathon.Main$.delayedEndpoint$mesosphere$marathon$Main$1(Main.scala:96)
        at mesosphere.marathon.Main$delayedInit$body.apply(Main.scala:95)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at mesosphere.marathon.MarathonApp.main(Main.scala:17)
        at mesosphere.marathon.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: java.util.concurrent.ThreadLocalRandom
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        ... 126 more
[2015-08-17 11:21:40,410] INFO Session establishment complete on server 10.12.3.0/10.12.3.0:2181, sessionid = 0x14f221dcd8f0a39, negotiated timeout = 100000 (org.apache.zookeeper.ClientCnxn:1235)
[2015-08-17 11:21:40,413] ERROR Error while calling watcher  (org.apache.zookeeper.ClientCnxn:524)
java.lang.NoClassDefFoundError: java/util/concurrent/ThreadLocalRandom
        at com.twitter.concurrent.LocalScheduler$Activation.<init>(Scheduler.scala:119)
        at com.twitter.concurrent.LocalScheduler.com$twitter$concurrent$LocalScheduler$$get(Scheduler.scala:201)
        at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:216)
        at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:84)
        at com.twitter.util.Promise.runq(Promise.scala:338)
        at com.twitter.util.Promise.updateIfEmpty(Promise.scala:669)
        at com.twitter.util.Promise.update(Promise.scala:642)
        at com.twitter.util.Promise.setValue(Promise.scala:618)
        at com.twitter.concurrent.Broker$$anon$1.prepare(Broker.scala:72)
        at com.twitter.concurrent.Offer$class.sync(Offer.scala:51)
        at com.twitter.concurrent.Broker$$anon$1.sync(Broker.scala:62)
        at com.twitter.zk.EventBroker.process(Event.scala:92)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
```

The process stays up, but it's unusable. There should be detection fo unsupported Java versions so it's possible to terminate whole marathon soon enough (and have clear message in logs).

**Comment by kolloch** [comment]
Thanks for your report. You are right, we should terminate in this case.

You should be able to get ride of the problem by upgrading to Java 7.

**Comment by aquamatthias** [comment]
Please use Java7. We will  not backport a fix for that issue.
