### ISSUE TITLE
Shaky Test: MarathonSchedulerActorTest "Forced deployment"

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2195]
Has failed in this test run:

https://travis-ci.org/mesosphere/marathon/builds/79098150

```
*** 1 TEST FAILED ***
MarathonSchedulerActorTest:
- Forced deployment *** FAILED *** (3 seconds, 11 milliseconds)
  java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class mesosphere.marathon.MarathonSchedulerActor$DeploymentStarted
  at scala.Predef$.assert(Predef.scala:165)
  at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:423)
  at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:396)
  at akka.testkit.TestKit.expectMsgType(TestKit.scala:718)
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$11.apply$mcV$sp(MarathonSchedulerActorTest.scala:511)
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$11.apply(MarathonSchedulerActorTest.scala:491)
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$11.apply(MarathonSchedulerActorTest.scala:491)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158)
  at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
  at mesosphere.marathon.MarathonSchedulerActorTest.withFixture(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$runTest(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
  at mesosphere.marathon.MarathonSchedulerActorTest.runTest(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:200)
  at mesosphere.marathon.MarathonSchedulerActorTest.runTests(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.Suite$class.run(Suite.scala:1423)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$FunSuiteLike$$super$run(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:204)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$run(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfterAll$$super$run(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
  at mesosphere.marathon.MarathonSchedulerActorTest.run(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:444)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:651)
  at sbt.ForkMain$Run$2.call(ForkMain.java:294)
  at sbt.ForkMain$Run$2.call(ForkMain.java:284)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by kolloch** [comment]
I just encountered this again.

See https://gist.github.com/anonymous/70204232245aad860864

**Comment by mwasn** [comment]
There were 2 waitForAssert statements with default timeout. I increased the timeout and run the test i a loop - did not arise again.
