### ISSUE TITLE
App not present right after its creation

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#2202]
The Scaling Test recently failed [[0]](https://teamcity.mesosphere.io/viewLog.html?buildId=43959&buildTypeId=Oss_Marathon_IntegrationScaleTests&tab=buildLog
), because the app it created wasn't included in the result of GET /v2/apps shortly after having created it:

https://teamcity.mesosphere.io/viewLog.html?buildId=43959&buildTypeId=Oss_Marathon_IntegrationScaleTests&tab=buildLog

```
[12:42:34][Step 3/3] - application scaling *** FAILED *** (1 second, 58 milliseconds)
[12:42:34][Step 3/3]   java.util.NoSuchElementException: head of empty list
[12:42:34][Step 3/3]   at scala.collection.immutable.Nil$.head(List.scala:420)
[12:42:34][Step 3/3]   at scala.collection.immutable.Nil$.head(List.scala:417)
[12:42:34][Step 3/3]   at mesosphere.mesos.scale.SingleAppScalingTest$$anonfun$4$$anonfun$apply$mcV$sp$1.apply(SingleAppScalingTest.scala:97)
[12:42:34][Step 3/3]   at mesosphere.mesos.scale.SingleAppScalingTest$$anonfun$4$$anonfun$apply$mcV$sp$1.apply(SingleAppScalingTest.scala:90)
[12:42:34][Step 3/3]   at scala.collection.immutable.Range.foreach(Range.scala:166)
[12:42:34][Step 3/3]   at mesosphere.mesos.scale.SingleAppScalingTest$$anonfun$4.apply$mcV$sp(SingleAppScalingTest.scala:90)
[12:42:34][Step 3/3]   at mesosphere.mesos.scale.SingleAppScalingTest$$anonfun$4.apply(SingleAppScalingTest.scala:77)
[12:42:34][Step 3/3]   at mesosphere.mesos.scale.SingleAppScalingTest$$anonfun$4.apply(SingleAppScalingTest.scala:77)
```

**Comment by bobrik** [comment]
#1407 maybe?

**Comment by kolloch** [comment]
Thanks, @bobrik

**Comment by aquamatthias** [comment]
See #2299
