### ISSUE TITLE
Investigate MarathonSchedulerServiceTest failure

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#2307]
`- Abdicate leadership when migration fails and reoffer leadership *** FAILED *** (4 seconds, 359 milliseconds)`

See https://travis-ci.org/mesosphere/marathon/builds/81970953 for more details.

```
[2015-09-24 14:10:50,038] INFO Elected (Leader Interface) (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anon$5:244)
[2015-09-24 14:10:50,039] ERROR Failed to take over leadership (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anon$5:263)
java.util.concurrent.TimeoutException: Failed to wait for future within timeout
	at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anon$10.answer(MarathonSchedulerServiceTest.scala:273)
	at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anon$10.answer(MarathonSchedulerServiceTest.scala:270)
	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
	at org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:51)
	at mesosphere.marathon.state.Migration$$EnhancerByMockitoWithCGLIB$$aa7b2fe.migrate(<generated>)
	at mesosphere.marathon.MarathonSchedulerService.onElected(MarathonSchedulerService.scala:250)
	at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6.apply$mcV$sp(MarathonSchedulerServiceTest.scala:277)
	at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6.apply(MarathonSchedulerServiceTest.scala:246)
	at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6.apply(MarathonSchedulerServiceTest.scala:246)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
	at mesosphere.marathon.MarathonSchedulerServiceTest.withFixture(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167)
	at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$BeforeAndAfter$$super$runTest(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
	at mesosphere.marathon.MarathonSchedulerServiceTest.runTest(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:200)
	at mesosphere.marathon.MarathonSchedulerServiceTest.runTests(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.Suite$class.run(Suite.scala:1423)
	at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$FunSuiteLike$$super$run(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:204)
	at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$BeforeAndAfter$$super$run(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
	at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$BeforeAndAfterAll$$super$run(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
	at mesosphere.marathon.MarathonSchedulerServiceTest.run(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:444)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:651)
	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-09-24 14:10:50,040] INFO Increasing offerLeadership backoff to 1000 milliseconds (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anon$5:322)
[2015-09-24 14:10:50,040] INFO Abdicating (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anon$5:308)
[2015-09-24 14:10:50,040] INFO Defeat leadership (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anon$5:280)
[2015-09-24 14:10:50,045] INFO Stopping driver (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anon$5:224)
[2015-09-24 14:10:50,046] INFO Will offer leadership after 1000 milliseconds backoff (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anon$5:332)
[2015-09-24 14:10:54,238] INFO Using HA and therefore offering leadership (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anon$5:339)
[info] - Abdicate leadership when migration fails and reoffer leadership *** FAILED ***
[info]   org.mockito.exceptions.verification.WantedButNotInvoked: Wanted but not invoked:
[info] candidate.offerLeadership($anon$5 [NEW]);
[info] -> at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anonfun$apply$mcV$sp$2.apply(MarathonSchedulerServiceTest.scala:279)
[info] Actually, there were zero interactions with this mock.
[info]   at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anonfun$apply$mcV$sp$2.apply(MarathonSchedulerServiceTest.scala:279)
[info]   at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anonfun$apply$mcV$sp$2.apply(MarathonSchedulerServiceTest.scala:279)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:254)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:265)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:718)
[info]   at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6.apply$mcV$sp(MarathonSchedulerServiceTest.scala:279)
[info]   at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6.apply(MarathonSchedulerServiceTest.scala:246)
[info]   at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6.apply(MarathonSchedulerServiceTest.scala:246)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   ...
[2015-09-24 14:10:54,424] INFO Elected (Leader Interface) (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$7$$anon$6:244)
[2015-09-24 14:10:54,424] ERROR Failed to take over leadership (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$7$$anon$6:263)
mesosphere.marathon.Exception: Some weird exception
	at mesosphere.marathon.MarathonSchedulerService.onElected(MarathonSchedulerService.scala:247)
	at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$7.apply$mcV$sp(MarathonSchedulerServiceTest.scala:309)
	at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$7.apply(MarathonSchedulerServiceTest.scala:283)
	at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$7.apply(MarathonSchedulerServiceTest.scala:283)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
	at mesosphere.marathon.MarathonSchedulerServiceTest.withFixture(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167)
	at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$BeforeAndAfter$$super$runTest(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
	at mesosphere.marathon.MarathonSchedulerServiceTest.runTest(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:200)
	at mesosphere.marathon.MarathonSchedulerServiceTest.runTests(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.Suite$class.run(Suite.scala:1423)
	at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$FunSuiteLike$$super$run(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:204)
	at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$BeforeAndAfter$$super$run(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
	at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$BeforeAndAfterAll$$super$run(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
	at mesosphere.marathon.MarathonSchedulerServiceTest.run(MarathonSchedulerServiceTest.scala:64)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:444)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:651)
	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-09-24 14:10:54,425] INFO Increasing offerLeadership backoff to 1000 milliseconds (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$7$$anon$6:322)
[2015-09-24 14:10:54,425] INFO Abdicating (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$7$$anon$6:308)
[2015-09-24 14:10:54,425] INFO Defeat leadership (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$7$$anon$6:280)
[2015-09-24 14:10:54,426] INFO Stopping driver (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$7$$anon$6:224)
[2015-09-24 14:10:54,426] INFO Will offer leadership after 1000 milliseconds backoff (mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$7$$anon$6:332)
- Abdicate leadership when migration fails and reoffer leadership *** FAILED *** (4 seconds, 359 milliseconds)
  org.mockito.exceptions.verification.WantedButNotInvoked: Wanted but not invoked:
candidate.offerLeadership($anon$5 [NEW]);
-> at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anonfun$apply$mcV$sp$2.apply(MarathonSchedulerServiceTest.scala:279)
Actually, there were zero interactions with this mock.
  at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anonfun$apply$mcV$sp$2.apply(MarathonSchedulerServiceTest.scala:279)
  at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6$$anonfun$apply$mcV$sp$2.apply(MarathonSchedulerServiceTest.scala:279)
  at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:254)
  at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:265)
  at akka.testkit.TestKit.awaitAssert(TestKit.scala:718)
  at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6.apply$mcV$sp(MarathonSchedulerServiceTest.scala:279)
  at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6.apply(MarathonSchedulerServiceTest.scala:246)
  at mesosphere.marathon.MarathonSchedulerServiceTest$$anonfun$6.apply(MarathonSchedulerServiceTest.scala:246)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158)
  at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
  at mesosphere.marathon.MarathonSchedulerServiceTest.withFixture(MarathonSchedulerServiceTest.scala:64)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167)
  at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$BeforeAndAfter$$super$runTest(MarathonSchedulerServiceTest.scala:64)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
  at mesosphere.marathon.MarathonSchedulerServiceTest.runTest(MarathonSchedulerServiceTest.scala:64)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:200)
  at mesosphere.marathon.MarathonSchedulerServiceTest.runTests(MarathonSchedulerServiceTest.scala:64)
  at org.scalatest.Suite$class.run(Suite.scala:1423)
  at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$FunSuiteLike$$super$run(MarathonSchedulerServiceTest.scala:64)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:204)
  at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$BeforeAndAfter$$super$run(MarathonSchedulerServiceTest.scala:64)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
  at mesosphere.marathon.MarathonSchedulerServiceTest.org$scalatest$BeforeAndAfterAll$$super$run(MarathonSchedulerServiceTest.scala:64)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
  at mesosphere.marathon.MarathonSchedulerServiceTest.run(MarathonSchedulerServiceTest.scala:64)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:444)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:651)
  at sbt.ForkMain$Run$2.call(ForkMain.java:294)
  at sbt.ForkMain$Run$2.call(ForkMain.java:284)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by aquamatthias** [comment]
There were 2 verify cases with default timeout of 800ms. I increased the timeouts to 5 seconds. Did not see that problem again. Close for now.
