### ISSUE TITLE
IntegrationTest failed: SingleAppScalingTest  create/stop app with 100 instances

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2321]
- create/stop app with 100 instances (warm up) *** FAILED *** (30 seconds, 150 milliseconds)
[15:10:06][Step 3/3]   java.lang.AssertionError: Waiting for event deployment_success to arrive took longer than 30 seconds. Give up.
[15:10:06][Step 3/3]   at mesosphere.marathon.integration.setup.WaitTestSupport$.next$1(WaitTestSupport.scala:30)
[15:10:06][Step 3/3]   at mesosphere.marathon.integration.setup.WaitTestSupport$.waitFor(WaitTestSupport.scala:36)
[15:10:06][Step 3/3]   at mesosphere.marathon.integration.setup.MarathonCallbackTestSupport$class.waitForEventMatching(MarathonCallbackTestSupport.scala:46)

**Comment by aquamatthias** [comment]
+1 

https://teamcity.mesosphere.io/viewLog.html?buildId=52518&buildTypeId=Oss_Marathon_IntegrationScaleTests&tab=buildLog#_focus=98790

**Comment by meichstedt** [comment]
Hint: look for the message `Requesting task reconciliation with the Mesos master`. After that, a lot of `TASK_LOST` messages are received. Pretty sure that this leads to the deployment timing out, but I have not yet looked into this. Maybe there is a bug in the DriverActor; there have been some recent changes.

**Comment by meichstedt** [comment]
Fixed via #2510
