### ISSUE TITLE
Marathon doesn't run on the latest Vagrant DCOS

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2482]
JIRA Key: MARATHON-423
Reporter: José Armando García Sancio
Priority: Blocker

Description:
We filed a similar bug against Chronos but it looks like Marathon has a similar problem:

run
```
dcos package install marathon
```

stderr:
```
I1020 00:16:30.103524 15508 exec.cpp:133] Version: 0.24.1
I1020 00:16:30.106516 15513 exec.cpp:207] Executor registered on slave 20151019-235506-1711804844-5050-1661-S0
Exception in thread "main" java.net.UnknownHostException: dcos-01: dcos-01: unknown error
        at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
        at mesosphere.marathon.MarathonConf$$anonfun$hostname$1.apply(MarathonConf.scala:60)
        at mesosphere.marathon.MarathonConf$$anonfun$hostname$1.apply(MarathonConf.scala:60)
        at org.rogach.scallop.Scallop$$anonfun$get$5$$anonfun$apply$35.apply(Scallop.scala:543)
        at org.rogach.scallop.Scallop$$anonfun$get$5$$anonfun$apply$35.apply(Scallop.scala:543)
        at scala.Option.orElse(Option.scala:289)
        at org.rogach.scallop.Scallop$$anonfun$get$5.apply(Scallop.scala:543)
        at org.rogach.scallop.Scallop$$anonfun$get$5.apply(Scallop.scala:537)
        at scala.Option.map(Option.scala:146)
        at org.rogach.scallop.Scallop.get(Scallop.scala:537)
        at org.rogach.scallop.Scallop$$anonfun$verify$17.apply(Scallop.scala:623)
        at org.rogach.scallop.Scallop$$anonfun$verify$17.apply(Scallop.scala:614)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.rogach.scallop.Scallop.verify(Scallop.scala:614)
        at org.rogach.scallop.ScallopConf.verify(ScallopConf.scala:274)
        at org.rogach.scallop.ScallopConf.afterInit(ScallopConf.scala:504)
        at mesosphere.chaos.App$class.initConf(App.scala:26)
        at mesosphere.marathon.MarathonApp.initConf(Main.scala:18)
        at mesosphere.chaos.App$class.run(App.scala:30)
        at mesosphere.marathon.MarathonApp.run(Main.scala:18)
        at mesosphere.marathon.MarathonApp.runDefault(Main.scala:87)
        at mesosphere.marathon.Main$.delayedEndpoint$mesosphere$marathon$Main$1(Main.scala:95)
        at mesosphere.marathon.Main$delayedInit$body.apply(Main.scala:94)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at mesosphere.marathon.MarathonApp.main(Main.scala:18)
        at mesosphere.marathon.Main.main(Main.scala)
Caused by: java.net.UnknownHostException: dcos-01: unknown error
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
        ... 31 more
```

stdout:
```
...
--container="mesos-20151019-235506-1711804844-5050-1661-S0.29373f3b-ef91-4761-8536-a0b52345c25f" --docker="docker" --help="false" --initialize_driver_logging="true" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slave/slaves/20151019-235506-1711804844-5050-1661-S0/frameworks/20151019-235506-1711804844-5050-1661-0000/executors/marathon-user2.cfa053af-76bf-11e5-8dbd-080027190480/runs/29373f3b-ef91-4761-8536-a0b52345c25f" --stop_timeout="0ns"
Registered docker executor on 172.17.8.102
Starting task marathon-user2.cfa053af-76bf-11e5-8dbd-080027190480
MESOS_NATIVE_JAVA_LIBRARY is not set. Searching in /usr/lib /usr/local/lib.
MESOS_NATIVE_LIBRARY, MESOS_NATIVE_JAVA_LIBRARY set to '/usr/lib/libmesos.so'
[2015-10-20 00:16:30,718] INFO Starting Marathon 0.11.1 with --master zk://master.mesos:2181/mesos --checkpoint --decline_offer_duration 5000 --http_port 4356 --event_stream_max_outstanding_messages 50 --failover_timeout 604800 --framework_name marathon-user --ha --leader_proxy_connection_timeout 5000 --leader_proxy_read_timeout 10000 --local_port_max 20000 --local_port_min 10000 --marathon_store_timeout 2000 --max_tasks_per_offer 1 --max_tasks_per_offer_cycle 1000 --min_revive_offers_interval 5000 --revive_offers_for_new_apps --scale_apps_initial_delay 15000 --scale_apps_interval 300000 --zk_session_timeout 1800000 --zk zk://master.mesos:2181/universe/marathon-user2 --mesos_leader_ui_url /mesos --zk_compression --zk_compression_threshold 65536 (mesosphere.marathon.Main$:86)
```

We have test in the CLI that depends on Marathon installing. This is blocking those tests. Also, note that this works on AWS DCOS.

Cody made the following comment:
```
Marathon has a different codepath for this sort of thing though
`--hostname "$LIBPROCESS_IP"` I think will fix it (edited)
because that's not libmesos erroring, it is marathon itself
```

**Comment by aquamatthias** [comment]
It does not make sense to start Marathon without a resolvable host name.
You either define the hostname by --hostname or rely on the underlying OS to detect the ip address. So the behavior you describe is not a bug, but intended.
