### ISSUE TITLE
Deploy app failed

### ISSUE THREAD

**Issue by lynchli** [mesosphere/marathon#2539]
I trying to use curl command POST an app JSON to Marathon, although it returns code 200, app can't deploy successful.

command:  
```shell
curl -X POST -H "Content-Type: application/json" http://username:password@ip:8080/v2/apps -d@app_marathon.json.tmp
```  

json file:
```json
{
  "id": "galaxy-dispatcher-dockerize11",
  "container": {
    "type": "DOCKER",
    "volumes": [
      {
        "hostPath": "/data/log/galaxy",
        "containerPath": "/var/log/galaxy",
        "mode": "RW"
      },
      {
        "hostPath": "/data/logbak/galaxy",
        "containerPath": "/var/logbak/galaxy",
        "mode": "RW"
      },
      {
        "hostPath": "/usr/local/mesos/build/src/.libs/",
        "containerPath": "/usr/local/mesos/build/src/.libs/",
        "mode": "RW"
      },
      {
        "hostPath": "/usr/lib64/libexpat.so.1",
        "containerPath": "/usr/lib/libexpat.so.1",
        "mode": "RW"
      },
      {
        "hostPath": "/usr/lib64/libdb-4.7.so",
        "containerPath": "/usr/lib/libdb-4.7.so",
        "mode": "RW"
      },
      {
        "hostPath": "/usr/lib64/libsasl2.so.2",
        "containerPath": "/usr/lib/libsasl2.so.2",
        "mode": "RW"
      }
    ],
    "docker": {
      "image": "docker-shnw.fenxibao.com/sirius/galaxy-dispatcher:dockerize-11",
      "forcePullImage": true,
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 8081,
          "servicePort": 0,
          "hostPort": 0,
          "protocol": "tcp"
        }
      ]
    }
  },
  "cpus": 2,
  "mem": 4096,
  "instances": 1,
  "uris": [
    "/root/.dockercfg"
  ],
  "env": {
    "app_log_dir": "/var/log/",
    "app_logbak_dir": "/var/logbak/",
    "MESOS_NATIVE_JAVA_LIBRARY": "/usr/local/mesos/build/src/.libs/libmesos.so"
  }
}
```

logs:
```java
Oct 27 15:17:06 mesos1 marathon[1848]: [2015-10-27 15:17:06,597] INFO Proxying request to POST http://172.18.2.131:8080/v2/apps from 172.18.2.130:8080 (mesosphere.marathon.api.JavaUrlConnectionRequestForwarder$:280)
Oct 27 14:54:40 mesos1 marathon[1848]: [2015-10-27 14:54:40,481] WARN /v2/apps (org.eclipse.jetty.servlet.ServletHandler:563)
Oct 27 14:54:40 mesos1 marathon[1848]: java.lang.RuntimeException: while proxying
Oct 27 14:54:40 mesos1 marathon[1848]: at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:141)
Oct 27 14:54:40 mesos1 marathon[1848]: at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
Oct 27 14:54:40 mesos1 marathon[1848]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
Oct 27 14:54:40 mesos1 marathon[1848]: at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
Oct 27 14:54:40 mesos1 marathon[1848]: at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Oct 27 14:54:40 mesos1 marathon[1848]: at com.codahale.metrics.jetty8.InstrumentedHandler.handle(InstrumentedHandler.java:192)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.Server.handle(Server.java:370)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:651)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
Oct 27 14:54:40 mesos1 marathon[1848]: at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
Oct 27 14:54:40 mesos1 marathon[1848]: at java.lang.Thread.run(Thread.java:745)
Oct 27 14:54:40 mesos1 marathon[1848]: Caused by: java.net.SocketTimeoutException: Read timed out
Oct 27 14:54:40 mesos1 marathon[1848]: at java.net.SocketInputStream.socketRead0(Native Method)
Oct 27 14:54:40 mesos1 marathon[1848]: at java.net.SocketInputStream.read(SocketInputStream.java:152)
Oct 27 14:54:40 mesos1 marathon[1848]: at java.net.SocketInputStream.read(SocketInputStream.java:122)
Oct 27 14:54:40 mesos1 marathon[1848]: at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
Oct 27 14:54:40 mesos1 marathon[1848]: at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
Oct 27 14:54:40 mesos1 marathon[1848]: at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
Oct 27 14:54:40 mesos1 marathon[1848]: at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
Oct 27 14:54:40 mesos1 marathon[1848]: at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
Oct 27 14:54:40 mesos1 marathon[1848]: at sun.net.www.protocol.http.HttpURLConnection.expect100Continue(HttpURLConnection.java:1021)
Oct 27 14:54:40 mesos1 marathon[1848]: at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1106)
Oct 27 14:54:40 mesos1 marathon[1848]: at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder$$anonfun$copyRequestBodyToConnection$1$1.apply(LeaderProxyFilter.scala:238)
Oct 27 14:54:40 mesos1 marathon[1848]: at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder$$anonfun$copyRequestBodyToConnection$1$1.apply(LeaderProxyFilter.scala:237)
Oct 27 14:54:40 mesos1 marathon[1848]: at mesosphere.marathon.io.IO$.using(IO.scala:87)
Oct 27 14:54:40 mesos1 marathon[1848]: at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.copyRequestBodyToConnection$1(LeaderProxyFilter.scala:237)
Oct 27 14:54:40 mesos1 marathon[1848]: at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.copyRequestToConnection$1(LeaderProxyFilter.scala:248)
Oct 27 14:54:40 mesos1 marathon[1848]: at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.forward(LeaderProxyFilter.scala:290)
Oct 27 14:54:40 mesos1 marathon[1848]: at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:137)
```

**Comment by aquamatthias** [comment]
The HTTP response code of create is 201. The 200 status os sent from the non leading instance.
The leader proxy does not work correctly. I assume you are not running latest Marathon (0.11.1)? 
Please update to the latest Marathon version.
