### ISSUE TITLE
Unable to find valid certification path to requested target - HTTPS errors on non-leader instances in cluster.

### ISSUE THREAD

**Issue by quamilek** [mesosphere/marathon#2540]
Hi, I have a problem with HTTPS configuration in Marathon.
I generated ssl cert for all Marathon instances (3 in cluster)
SSL certs was signed by local CA.
I disabled http and set only https.

I started Marathon with this parameters:

```
--ssl_keystore_password $MARATHON_JKS_PASSWORD --ssl_keystore_path /etc/marathon/marathon.jks --https_port 8080 --disable_http
```

On Marathon leader instance all UI work, but on non-leader instances I got following errors:

```
Oct 29 11:16:36 master1.local marathon[11760]: [2015-10-29 11:16:36,692] WARN /v2/deployments (org.eclipse.jetty.servlet.ServletHandler:563)
Oct 29 11:16:36 master1.local marathon[11760]: java.lang.RuntimeException: while proxying
Oct 29 11:16:36 master1.local marathon[11760]:   at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:147)
Oct 29 11:16:36 master1.local marathon[11760]:   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
Oct 29 11:16:36 master1.local marathon[11760]:   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
Oct 29 11:16:36 master1.local marathon[11760]:   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
Oct 29 11:16:36 master1.local marathon[11760]:   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Oct 29 11:16:36 master1.local marathon[11760]:   at com.codahale.metrics.jetty8.InstrumentedHandler.handle(InstrumentedHandler.java:192)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.Server.handle(Server.java:370)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
Oct 29 11:16:36 master1.local marathon[11760]:   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
Oct 29 11:16:36 master1.local marathon[11760]:   at java.lang.Thread.run(Thread.java:745)
Oct 29 11:16:36 master1.local marathon[11760]: Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.Handshaker.processLoop(Handshaker.java:969)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.Handshaker.process_record(Handshaker.java:904)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
Oct 29 11:16:36 master1.local marathon[11760]:   at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
Oct 29 11:16:36 master1.local marathon[11760]:   at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.copyConnectionResponse$1(LeaderProxyFilter.scala:260)
Oct 29 11:16:36 master1.local marathon[11760]:   at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.forward(LeaderProxyFilter.scala:299)
Oct 29 11:16:36 master1.local marathon[11760]:   at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:50)
Oct 29 11:16:36 master1.local marathon[11760]:   at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:24)
Oct 29 11:16:36 master1.local marathon[11760]:   at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:49)
Oct 29 11:16:36 master1.local marathon[11760]:   at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:143)
Oct 29 11:16:36 master1.local marathon[11760]:   ... 27 more
Oct 29 11:16:36 master1.local marathon[11760]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.validator.Validator.validate(Validator.java:260)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
Oct 29 11:16:36 master1.local marathon[11760]:   ... 46 more
Oct 29 11:16:36 master1.local marathon[11760]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
Oct 29 11:16:36 master1.local marathon[11760]:   at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
Oct 29 11:16:36 master1.local marathon[11760]:   at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
Oct 29 11:16:36 master1.local marathon[11760]:   ... 52 more
```

**Comment by pierlo-upitup** [comment]
Similar symptoms to https://github.com/mesosphere/marathon/issues/2539

**Comment by quamilek** [comment]
When ssl certificated was signed by our not trusted certificate authority, you must add this CA certificate to keystore. 

```keytool -import -trustcacerts -file ./cacert.cer -alias yourca --keystore /etc/marathon/marathon.jks```

When CA cert was added to keystore, all working ok, and errors does not occur.

**Comment by yangtao309** [comment]
i met it.
marathon master: 172.18.2.131
marathon slave: 172.18.2.130 172.18.2.132

in my mac terminal i will execute
```
curl -X POST -H "Content-Type: application/json" http://username:password@172.18.2.130:8080/v2/apps -d@app_marathon_template.json.tmp
```
it throw exception Similar to the @quamilek  report.

then i copy json data in postman，set it IP 172.18.2.130， but execute ok。

i don't know what happend。

then i will change ip 172.18.2.131 in my terminal ， execute ok。

**Comment by kolloch** [comment]
Hi @quamilek, thanks for also reporting the solution! I added it to our "Common Problems" section of our documentation. Feel free to comment on my pull request: https://github.com/mesosphere/marathon/pull/2647

(We generally are very thankful for documentation pull requests if you want to add something.)

Hi @yangtao309, did the instructions of @quamilek work for you? Can you try with a more recent Marathon version? What did you expect to happen and what happened exactly?
