### ISSUE TITLE
Create app failed when there're multiple same word in the app id

### ISSUE THREAD

**Issue by wshzhn** [mesosphere/marathon#2855]
The error log like:

INFO Upgrade id:/someword/dev2/someword/test/111 version:2015-12-17T09:59:37.729Z with force:true (mesosphere.marathon.state.GroupManager:136)
[2015-12-17 17:59:42,867] WARN  (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$e73f5c3c:30)
java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:347)
    at scala.None$.get(Option.scala:345)
    at mesosphere.marathon.api.v2.AppsResource.replace(AppsResource.scala:166)
    at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:50)
    at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:24)
    at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:49)
    at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    at com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchProvider$TimedRequestDispatcher.dispatch(InstrumentedResourceMethodDispatchProvider.java:30)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
    at mesosphere.marathon.api.CacheDisablingFilter.doFilter(CacheDisablingFilter.scala:18)
    at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:50)
    at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:24)
    at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:49)
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
    at mesosphere.marathon.api.CORSFilter.doFilter(CORSFilter.scala:46)
    at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:50)
    at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:24)
    at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:49)
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
    at mesosphere.marathon.api.SetRequestDefaultsFilter.doFilter(SetRequestDefaultsFilter.scala:36)
    at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:50)
    at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:24)
    at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:49)
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
    at mesosphere.marathon.api.LimitConcurrentRequestsFilter.pass(LimitConcurrentRequestsFilter.scala:32)
    at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15)
    at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15)
    at mesosphere.marathon.api.LimitConcurrentRequestsFilter.doFilter(LimitConcurrentRequestsFilter.scala:36)
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
    at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:127)
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at com.codahale.metrics.jetty8.InstrumentedHandler.handle(InstrumentedHandler.java:192)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:744)

**Comment by gkleiman** [comment]
@wshzhn thanks for the report. Which version of Marathon gave you that stack trace?

I can confirm that using the following app definition with the current dev snapshot (Marathon v0.15.0-SNAPSHOT) it doesn't work either, but it breaks in a different way:

POST /v2/apps with:

```
{
  "id": "/someword/dev2/someword/test/111",
  "cmd": "sleep 1000"
}
```

Marathon will then create an empty deployment, return 201 and log the following:

```
marathon [2015-12-21 11:56:00,155] INFO Upgrade group id:/someword/dev2/someword/test version:2015-12-21T10:55:59.850Z with force:false (mesosphere.marathon.state.GroupManager:marathon-akka.actor.default-dispatcher-8)
marathon [2015-12-21 11:56:00,184] INFO Computed new deployment plan:
marathon DeploymentPlan 2015-12-21T10:55:59.850Z NO STEPS
marathon  (mesosphere.marathon.state.GroupManager:pool-1-thread-13)
marathon [2015-12-21 11:56:00,184] INFO Deploy plan with force=false:
marathon DeploymentPlan 2015-12-21T10:55:59.850Z NO STEPS
marathon   (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$c08ae884:pool-1-thread-12)
marathon [2015-12-21 11:56:00,256] INFO Updated groups/apps according to deployment plan b68b6beb-5bd2-4e75-8c6c-da27f466f710 (mesosphere.marathon.state.GroupManager:pool-1-thread-14)
marathon [2015-12-21 11:56:00,256] INFO Deployment acknowledged. Waiting to get processed:
marathon DeploymentPlan 2015-12-21T10:55:59.850Z NO STEPS
marathon  (mesosphere.marathon.state.GroupManager:pool-1-thread-14)
marathon [2015-12-21 11:56:00,262] INFO Deployment of / successful (mesosphere.marathon.MarathonSchedulerActor:marathon-akka.actor.default-dispatcher-15)
marathon [2015-12-21 11:56:00,263] INFO Removing b68b6beb-5bd2-4e75-8c6c-da27f466f710 from list of running deployments (mesosphere.marathon.upgrade.DeploymentManager:marathon-akka.actor.default-dispatcher-15)
```

Because the deployment has no steps, it will succeed, but the app isn't created.

**Comment by wshzhn** [comment]
@gkleiman Thanks for your answer.
Marathon is V0.10.0, mesos is V0.24.0.
