### ISSUE TITLE
Marathon cannot schedule task when log writing is blocked

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2985]
I don't think these two should be related that much. We saw this when running Marathon (both 0.11.1 and 0.14.0RC3) under docker that is very busy, see docker/docker#19209.

```
2016-01-14T00:21:02.000Z 36s54 [2016-01-14 00:16:47,422] ERROR error while matching '44bc368b-40c7-4669-8a25-340efc507a2e-O513897' (mesosphere.marathon.core.launcher.impl.OfferProcessorImpl:59)
2016-01-14T00:21:02.000Z 36s54 at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
2016-01-14T00:21:02.000Z 36s54 at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:335)
2016-01-14T00:21:02.000Z 36s54 akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://marathon/user/offerMatcherManager#168703490]] after [1000 ms]
2016-01-14T00:21:02.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
2016-01-14T00:21:02.000Z 36s54 at java.lang.Thread.run(Thread.java:745)
2016-01-14T00:21:02.000Z 36s54 at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
2016-01-14T00:21:02.000Z 36s54 at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
2016-01-14T00:21:02.000Z 36s54 at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
2016-01-14T00:21:02.000Z 36s54 at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
2016-01-14T00:21:03.000Z 36s54 at java.lang.Thread.run(Thread.java:745)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
2016-01-14T00:21:03.000Z 36s54 at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
2016-01-14T00:21:03.000Z 36s54 [2016-01-14 00:16:47,422] ERROR error while matching '44bc368b-40c7-4669-8a25-340efc507a2e-O513893' (mesosphere.marathon.core.launcher.impl.OfferProcessorImpl:59)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
2016-01-14T00:21:03.000Z 36s54 at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
2016-01-14T00:21:03.000Z 36s54 akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://marathon/user/offerMatcherManager#168703490]] after [1000 ms]
2016-01-14T00:21:03.000Z 36s54 [2016-01-14 00:16:47,422] ERROR error while matching '44bc368b-40c7-4669-8a25-340efc507a2e-O513891' (mesosphere.marathon.core.launcher.impl.OfferProcessorImpl:59)
2016-01-14T00:21:03.000Z 36s54 akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://marathon/user/offerMatcherManager#168703490]] after [999 ms]
2016-01-14T00:21:03.000Z 36s54 at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:335)
2016-01-14T00:21:03.000Z 36s54 at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:335)
2016-01-14T00:21:03.000Z 36s54 at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
2016-01-14T00:21:03.000Z 36s54 at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
2016-01-14T00:21:03.000Z 36s54 at java.lang.Thread.run(Thread.java:745)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
2016-01-14T00:21:03.000Z 36s54 at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
2016-01-14T00:21:03.000Z 36s54 at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
2016-01-14T00:21:03.000Z 36s54 at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
2016-01-14T00:21:03.000Z 36s54 at java.lang.Thread.run(Thread.java:745)
```

The minimum thing that should be done is error message. It should probably point to the possible source of the error and give some clues how to improve. Ex:

```
Taking too long [1000ms] to match offers, see --max_whatever.
```

Here `--max_whatever` can have some explanations in docs.

**Comment by kolloch** [comment]
Hmmm. The `--max_offer_matching_timeout` suggestion is good.

Since this is not a fatal error (the matching will be retried), I wonder if we should also choose `WARN` as log level. It is an indication that things are going less than optimal but not more.

**Comment by kolloch** [comment]
Another remedy could be better logging configuration including some buffer. The downside would be that not all log messages would be captured in a crash. 

We could also make it easy to log to a file and not standard output.

Alternatively, you could also reduce the log level -- but the reality is that you are then throwing away information that will help us to find errors.

What do you think, @bobrik?

**Comment by bobrik** [comment]
> It is an indication that things are going less than optimal but not more.

Less than optimal for me was causing inability to schedule anything at all. Making it WARN is fine, I guess.

I'd like to understand why logging affects offer matching so much. Is it because matching logs each match try and it appears to be cartesian product of tasks x offers?

**Comment by kolloch** [comment]
Our logging configuration writes log messages synchronously to standard output. If you pipe the output into a file than there is a OS buffer involved and in combination with really awesome linear writing speeds nowadays, its very hard to block in this cases.

`docker` and `journald` unfortuantely do get overwhelmed quite easily. It would be nice to fix them but we are not living in an optimal world.

We can configure an in-app strategy to buffer events in the application memory. This only really helps for short logging spikes. If our logging consumer is consistently slower when the app that writes logs, we can either block or start dropping log messages. That strategy has the additional downside that you might loose the last log statements in the case of crashes -- and if you have crashes these are often the log statements that interest you.

Look [here](http://logback.qos.ch/manual/appenders.html#AsyncAppender) for some options, I'd love to hear your opinion.

**Comment by bobrik** [comment]
Maybe we don't have to care that much about slow stdout reading. Let's improve error message to point to the solution fist. In our case we have to fix docker anyway.

**Comment by kolloch** [comment]
There is not clear solution. Increasing the timeout is not necessarily what you want and could actually lead to more problems (since more launches are attempted in parallel). Instead you might want to decrease the number of task launches you allow. That's kind of hard to explain in a log message. Maybe we include an URL with an explanation?

**Comment by bobrik** [comment]
Yes, URL explaining tradeoffs would work too.

**Comment by aquamatthias** [comment]
@kolloch: 
I see 2 action items here:
- the log message should be Warn not Error (and also no stack trace)
- the log message should include an URL for explanation
 correct?

**Comment by kolloch** [comment]
Yes, plus potentially the following:

* adjust our logging to be asynchronous and drop everything but WARN/ERROR on overload. At least that's functionality easily attainable in logback.
