### ISSUE TITLE
Don't log giant stack traces for 404s (or similarly trivial errors) [0.13]

### ISSUE THREAD

**Issue by cmaloney** [mesosphere/marathon#3067]
```
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: [2016-01-21 19:38:55,566] INFO mapping exception to status code (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$f3b705a9:qtp828312047-36)
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: com.sun.jersey.api.NotFoundException: null for uri: http://zc.qq.com/cgi-bin/chs/numreg/init
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1543) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.CacheDisablingFilter.doFilter(CacheDisablingFilter.scala:18) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$4d32cee3.CGLIB$doFilter$0(<generated>) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$4d32cee3$$FastClassByGuice$$3ac36027.invoke(<generated>) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$4d32cee3.doFilter(<generated>) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.CORSFilter.doFilter(CORSFilter.scala:46) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$6d0e9d1d.CGLIB$doFilter$0(<generated>) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$6d0e9d1d$$FastClassByGuice$$73c1d07f.invoke(<generated>) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$6d0e9d1d.doFilter(<generated>) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.LimitConcurrentRequestsFilter.pass(LimitConcurrentRequestsFilter.scala:32) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.LimitConcurrentRequestsFilter.doFilter(LimitConcurrentRequestsFilter.scala:36) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:126) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.server.Server.handle(Server.java:517) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [marathon.jar:0.13.0]
Jan 21 19:38:55 ip-10-0-7-191.us-west-2.compute.internal java[1317]: at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
```

**Comment by kolloch** [comment]
@cmaloney: Ok, that's a rather long message for a "404". What do you mean by "unexpected"?

So what would you suggest? Changing the log level for this sort of message to "DEBUG"?

**Comment by cmaloney** [comment]
Yea, just log a 404, rather than printing a giant backtrace. Backtraces tend to suggest some internal error which is a bug, vs. "this is normal operation"

**Comment by kolloch** [comment]
Thanks for the clarification, @cmaloney! I will update the issue title a bit -- please complain if you dislike it.

**Comment by jasongilanfarr** [comment]
I believe we fixed this. We definitely have filtering for stack traces on certain error types.
