### ISSUE TITLE
MarathonSchedulerActorTest is shaky

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#3103]
On TC I often get:
*** 1 TEST FAILED ***
[18:49:28][Step 3/3] MarathonSchedulerActorTest:
[18:49:28][Step 3/3] 
[18:49:28][Step 3/3] - Concurrent reconciliation check is not preventing sequential calls *** FAILED *** (8 milliseconds)
[18:49:28][Step 3/3]   org.mockito.exceptions.verification.TooLittleActualInvocations: schedulerActions.reconcileTasks(<any>);
[18:49:28][Step 3/3] Wanted 3 times:
[18:49:28][Step 3/3] -> at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$14.apply$mcV$sp(MarathonSchedulerActorTest.scala:520)
[18:49:28][Step 3/3] But was 2 times:
[18:49:28][Step 3/3] -> at mesosphere.marathon.MarathonSchedulerActor$$anonfun$started$1.applyOrElse(MarathonSchedulerActor.scala:114)
[18:49:28][Step 3/3]   at mesosphere.marathon.Ma

On my local machine this test is green all the time.

**Comment by gkleiman** [comment]
A user reported that the test is still flaky: #3152
