### ISSUE TITLE
Marathon UI always hang in version 0.14.0

### ISSUE THREAD

**Issue by wshzhn** [mesosphere/marathon#3113]
I just upgrade to version 0.14.0, and the UI always hang with error in the log:

[2016-01-28 12:18:02,770] WARN /ui/fonts/SourceSansPro-Regular.otf.woff (org.eclipse.jetty.servlet.ServletHandler:qtp1598561139-29)
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
    at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:226) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:164) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:297) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.io.IO$.read$1(IO.scala:100) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.io.IO$.transfer(IO.scala:104) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.WebJarServlet$$anonfun$sendResource$1$2.apply(WebJarServlet.scala:22) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.WebJarServlet$$anonfun$sendResource$1$2.apply(WebJarServlet.scala:18) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.io.IO$$anonfun$withResource$1.apply(IO.scala:118) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.io.IO$$anonfun$withResource$1.apply(IO.scala:116) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at scala.Option.flatMap(Option.scala:171) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.io.IO$.withResource(IO.scala:116) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.WebJarServlet.sendResource$1(WebJarServlet.scala:18) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.WebJarServlet.sendResourceNormalized$1(WebJarServlet.scala:30) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.WebJarServlet.doGet(WebJarServlet.scala:67) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.CacheDisablingFilter.doFilter(CacheDisablingFilter.scala:18) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.CORSFilter.doFilter(CORSFilter.scala:46) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.LimitConcurrentRequestsFilter.pass(LimitConcurrentRequestsFilter.scala:32) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.LimitConcurrentRequestsFilter.doFilter(LimitConcurrentRequestsFilter.scala:36) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:126) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon-assembly-0.14.0.jar:0.14.0]
    at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.Server.handle(Server.java:517) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [marathon-assembly-0.14.0.jar:0.14.0]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
    at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50) ~[marathon-assembly-0.14.0.jar:0.14.0]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_60]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_60]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_60]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
    ... 1 common frames omitted

Please help to check it. Thanks.

**Comment by Poltergeist** [comment]
Hi @wshzhn,

0.14 is stable and should work from the log I do not see what the problem is, could you please provide the log from the browser. The JavaScript console can be accessed from the browser with these [hotkeys](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers). It would also be great if you could provide some more information for example like on which os version you are.

**Comment by wshzhn** [comment]
Thanks for your reply!
OS version is Centos 6.4 with 2.6 kernel.
Browser log like:

Download the React DevTools for a better development experience: https://fb.me/react-devtools
35http://xxxxxxx:8080/v2/apps//testdocker1/f/publicdata/cache/test?embed=app.taskStats Failed to load resource: the server responded with a status of 404 (Not Found)
21http://xxxxxxx:8080/v2/apps//ttsi/dev1/f/publicdata/cache/test?embed=app.taskStats Failed to load resource: the server responded with a status of 404 (Not Found)

It seems some app had been destroyed, when I refresh a marathon url which was opened a few days ago, it will hang.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3161. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
