### ISSUE TITLE
Exit with a meaningful error if mesos library can not be loaded

### ISSUE THREAD

**Issue by guenter** [mesosphere/marathon#313]
The current exception is:

```
Exception in thread "main" com.google.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.UnsatisfiedLinkError: org.apache.mesos.state.AbstractState.__fetch(Ljava/lang/String;)J
  at mesosphere.marathon.MarathonSchedulerService.<init>(MarathonSchedulerService.scala:33)
  at mesosphere.marathon.MarathonModule.configure(MarathonModule.scala:38)
  while locating mesosphere.marathon.MarathonSchedulerService
    for parameter 0 at mesosphere.marathon.api.LeaderProxyFilter.<init>(LeaderProxyFilter.scala:22)
  at mesosphere.marathon.api.MarathonRestModule.configureServlets(MarathonRestModule.scala:38)
  while locating mesosphere.marathon.api.LeaderProxyFilter
```

**Comment by crystalfuns** [comment]
I am seeing this issue..when i run spark-submit from client instance ( i am trying to connect my Mesos Cluster)

java.lang.UnsatisfiedLinkError: Can't load library: /usr/local/lib/libmesos.so
