### ISSUE TITLE
Jetty throws exception during load

### ISSUE THREAD

**Issue by sdwr98** [mesosphere/marathon#3141]
Hi all,

I've been seeing this show up in my marathon logs since upgrading to 0.11.1:  

```
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]: SLF4J: Failed toString() invocation on an object of type [org.eclipse.jetty.server.HttpConnection]
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]: java.lang.IndexOutOfBoundsException
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at java.nio.Buffer.checkIndex(Buffer.java:540)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.util.BufferUtil.appendDebugString(BufferUtil.java:1054)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.util.BufferUtil.toDetailString(BufferUtil.java:1021)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.server.HttpConnection.toString(HttpConnection.java:809)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:297)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:269)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:227)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:619)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.util.log.JettyAwareLogger.debug(JettyAwareLogger.java:206)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:89)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.io.AbstractConnection.onClose(AbstractConnection.java:186)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.server.HttpConnection.onClose(HttpConnection.java:482)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.io.SelectorManager.connectionClosed(SelectorManager.java:327)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.io.ManagedSelector$2.run(ManagedSelector.java:431)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
Feb 02 13:47:09 mesosmaster-prod-i-52ad96e0 marathon[15927]:         at java.lang.Thread.run(Thread.java:745)
```

It appears to be https://bugs.eclipse.org/bugs/show_bug.cgi?id=479179, which is fixed in Jetty 9.3.5.  It doesn't seem to be affecting functionality, but it does show up a lot and clutters up the logs.  

Thanks!

**Comment by gkleiman** [comment]
@sdwr98 thanks for reporting this and for finding the root cause of the exceptions.

We'll need to release and use a new Chaos version with an updated Jetty version.

**Comment by meichstedt** [comment]
cherry-picked onto releases/0.15
