### ISSUE TITLE
Can't scale Docker task after Docker image crash

### ISSUE THREAD

**Issue by deric** [mesosphere/marathon#3228]
A task gets stuck in deployment after a Docker container job crashes and Marathon can't stop the container, from debug tab:

```
Unable to stop docker container, error: Failed to 'docker -H unix:///var/run/docker.sock
 stop -t 0 mesos-9956b2f6-(...)': exit status = exited with status 1
 stderr = An error occurred trying to connect: 
Post http:///var/run/docker.sock/v1.21/containers/mesos-9956b2f6-(...)/stop?t=0: 
EOF Error: failed to stop containers: [mesos-9956b2f6-(...)]
```

The task is locked for deployment, and I can't delete an instance which should be running according to Marathon but it's not running anymore. I can't scale it nor suspend the task.

A workaround is to create a task with new app ID, but the old task will stay there in a zombie state:

```
 DeploymentPlan 2016-02-11T17:47:02.327Z
 step 1:
 * Stop(App(/parser, image="some-image", cmd="run-forrest")))
 (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$6617eef1:ForkJoinPool-2-worker-233)
 [2016-02-11 12:47:02,335] INFO Conflicting deployments for deployment 9efffc37-d983-4ca8-a7f9-818c698163e6 have been canceled (mesosphere.marathon.upgrade.DeploymentManager:marathon-akka.actor.default-dispatcher-2)
 [2016-02-11 12:47:12,329] WARN mapping exception to status code (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$93f15861:qtp1967434886-121004)
 java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
 at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[marathon:0.15.1]
 at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) ~[marathon:0.15.1]
 at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190) ~[marathon:0.15.1]
 at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53) ~[marathon:0.15.1]
 at scala.concurrent.Await$.result(package.scala:190) ~[marathon:0.15.1]
 at mesosphere.marathon.api.RestResource$class.result(RestResource.scala:52) ~[marathon:0.15.1]
 at mesosphere.marathon.api.v2.AppsResource.result(AppsResource.scala:33) ~[marathon:0.15.1]
 at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) ~[marathon:0.15.1]
 at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27) ~[marathon:0.15.1]
 at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) ~[marathon:0.15.1]
 at mesosphere.marathon.api.v2.AppsResource$$anonfun$delete$1.apply(AppsResource.scala:184) ~[marathon:0.15.1]
...
```

Marathon 0.15.1

**Comment by philipnrmn** [comment]
After some initial investigation, this message seems to have come from Docker itself. I wonder whether you're running into some facet of docker/docker#12738. 

Would you be able to post an (anonymised, if necessary) app configuration that reproduces this issue?

**Comment by deric** [comment]
You should be able to reproduce this by starting a container with a zombie process. 
```
root  2039  0.0  Sl   Feb15   0:27  \_ docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 30029 -container-ip 172.17.0
root  2078  0.0  Ss   Feb15   0:00  \_ [sh]
root  1829 99.9  Zl   Feb15 885:31      \_ [java] <defunct>
```
You're right, it's definitely a Docker bug/application bug, I can't stop the container nor `docker rm -f {container ID}`. Another related bug seems to be https://github.com/docker/docker/issues/19166. Just for reference, I'm running on `Linux kernel 3.16.7-ckt20-1+deb8u2`.

Of course I don't want to run zombie processes in containers, from Marathon perspective it would be nice to handle such state of a task. Right now it reports 2 instances in unknown state and other 2 and other 2 unscheduled. Marathon pretends it's deploying the task for last 20 hours, but it's not. Also there's no error report from last restart. It's quite hard to debug such application, because there are no error logs, failure reports.

Restarting docker daemon on slave nodes, usually helps Marathon realize that the task really failed (removes it from running tasks, but does not start new one instead). Then you'll get application in RUNNING state with 0 instances out of 4 running.

**Comment by deric** [comment]
Btw. reaching UNIX socket via HTTP is really intentional?
```
Post http://%2Fvar%2Frun%2Fdocker.sock/v1.22/containers/mesos-9956b2f6-9102-4b77-a2e0-c8649629f62b-S1.2eb71885-d80a-49f7-9288-c4910e6172b5/stop?t=0: EOF
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1979. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
