### ISSUE TITLE
java.lang.UnsatisfiedLinkError: /usr/lib/libmesos-0.26.0.so: libgcrypt.so.20

### ISSUE THREAD

**Issue by yfinkelstein** [mesosphere/marathon#3288]
When starting Marathon in a docker container using https://hub.docker.com/r/mesosphere/marathon/ 
version 0.15.2
I'm seeing the following in the log file:
```
Failed to load native Mesos library from /usr/lib/libmesos.so
java.lang.UnsatisfiedLinkError: /usr/lib/libmesos-0.26.0.so: libgcrypt.so.20: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:159)
        at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:188)
        at org.apache.mesos.MesosSchedulerDriver.<clinit>(MesosSchedulerDriver.java:61)
        at mesosphere.marathon.MarathonSchedulerDriver$.newDriver(MarathonSchedulerDriver.scala:80)
        at mesosphere.marathon.MesosSchedulerDriverFactory.createDriver(SchedulerDriverFactory.scala:28)
        at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56)
        at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27)
        at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55)
        at mesosphere.marathon.MarathonSchedulerService.onElected(MarathonSchedulerService.scala:282)
        at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56)
        at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27)
        at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55)
        at com.twitter.common.zookeeper.CandidateImpl$4.onGroupChange(CandidateImpl.java:155)
        at com.twitter.common.zookeeper.Group$GroupMonitor.setMembers(Group.java:665)
        at com.twitter.common.zookeeper.Group$GroupMonitor.watchGroup(Group.java:638)
        at com.twitter.common.zookeeper.Group$GroupMonitor.access$900(Group.java:579)
        at com.twitter.common.zookeeper.Group$4.get(Group.java:551)
        at com.twitter.common.zookeeper.Group$4.get(Group.java:548)
        at com.twitter.common.util.BackoffHelper$1.get(BackoffHelper.java:109)
        at com.twitter.common.util.BackoffHelper$1.get(BackoffHelper.java:107)
        at com.twitter.common.util.BackoffHelper.doUntilResult(BackoffHelper.java:127)
        at com.twitter.common.util.BackoffHelper.doUntilSuccess(BackoffHelper.java:107)
 ```
The strange thing is that if I run ldd on libmesos.so inside of the container it's happily found:
```
libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f05d2371000)
```

**Comment by orlandohohmeier** [comment]
Hi @yfinkelstein could you please provide your `docker run` and Marathon configuration?

**Comment by yfinkelstein** [comment]
I'm sorry, I discovered that this was caused by my own remapping of the /lib/x86_64-linux-gnu directory which came from a different script. The docker image of marathon indeed contains correct library versions. Please close this as non-issue.

**Comment by orlandohohmeier** [comment]
@yfinkelstein No problem, I'm glad you could fix your problem.
