### ISSUE TITLE
404 Retrieving logs.

### ISSUE THREAD

**Issue by kevincox** [mesosphere/marathon#3406]
When I click the "stdout" or "stderr" links for a task in the Marathon 0.15.3 WebUI it says "Sorry there was a problem retrieving file. Click to retry."

In the network debugger of my browser I can see that the URI `https://marathon/pkgpanda/active.buildinfo.full.json` returns 404 and the following error appears in the Marathon logs.

```
[2016-03-06 12:56:29,492] INFO mapping exception to status code (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$48574864:qtp1650327539-30)
com.sun.jersey.api.NotFoundException: null for uri: http://marathon/pkgpanda/active.buildinfo.full.json
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1543) [marathon-0.15.3.jar:0.15.3]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [marathon-0.15.3.jar:0.15.3]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [marathon-0.15.3.jar:0.15.3]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [marathon-0.15.3.jar:0.15.3]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [marathon-0.15.3.jar:0.15.3]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [marathon-0.15.3.jar:0.15.3]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [marathon-0.15.3.jar:0.15.3]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.CacheDisablingFilter.doFilter(CacheDisablingFilter.scala:18) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$80a53e51.CGLIB$doFilter$0(<generated>) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$80a53e51$$FastClassByGuice$$6a1765e2.invoke(<generated>) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$80a53e51.doFilter(<generated>) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.CORSFilter.doFilter(CORSFilter.scala:46) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$ab667925.CGLIB$doFilter$0(<generated>) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$ab667925$$FastClassByGuice$$846d1c44.invoke(<generated>) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$ab667925.doFilter(<generated>) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.LimitConcurrentRequestsFilter.pass(LimitConcurrentRequestsFilter.scala:32) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.LimitConcurrentRequestsFilter.doFilter(LimitConcurrentRequestsFilter.scala:36) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon-0.15.3.jar:0.15.3]
        at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:126) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [marathon-0.15.3.jar:0.15.3]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon-0.15.3.jar:0.15.3]
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.server.Server.handle(Server.java:517) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [marathon-0.15.3.jar:0.15.3]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [marathon-0.15.3.jar:0.15.3]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_76]
[2016-03-06 12:56:29,500] INFO 127.0.0.1 - - [06/Mar/2016:12:56:29 +0000] "GET //marathon/pkgpanda/active.buildinfo.full.json HTTP/1.1" 404 65 "https://marathon/ui/" "Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0" 2 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$b549f0ba:qtp1650327539-30)
```

**Comment by vixns** [comment]
May be related to https.

I run marathon on https only on a public IP, and mesos on http / private IP, only available thru a VPN.
Loading the logs raise mixed contents error, forcing them in the browser does not work either, after getting data from the mesos master, it try to access mesos slaves with https.

Proxiyng mesos logs thru marathon should fix many use cases like this one.

Also have this 404, but no exceptions in the logs.

**Comment by aliostad** [comment]
I am getting the same problem
![image](https://cloud.githubusercontent.com/assets/487334/15284201/e3193574-1b47-11e6-9eae-21dea283d321.png)

**Comment by vixns** [comment]
Use a tunnel/vlan/VPN/... , having mesos binding a public IP without enforcing ssl is a bit reckless.
I was able to workaround my issue (mixed content when accessing marathon thru https) by enabling SSL on mesos.

These are different issues, but related to the same design flaw ( not proxying logs thru marathon )

**Comment by aliostad** [comment]
Thanks @vixns but I am using IP whitelisting for the public IP so it is secured access although the communication is publicly visible. Thanks I will look into enabling a tunnel.

**Comment by dariko** [comment]
I have a similar error on a (ssl+authentication)-enabled deployment:

I access the ui via https://h2.mydomain.com:8443 (one of 3 marathon hosts).
When in the ui I click `stdout` or `stderr` a request to `https://h2.mydomain.com:8443/pkgpanda/active.buildinfo.full.json` fails with 404

on the active mesos master log i found this error

`
May 31 11:33:16 h2.mydomain.com marathon[20523]: [2016-05-31 11:33:16,454] INFO mapping exception to status code (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$7a099f65:qtp14838518-133)
`
`
May 31 11:33:16 h2.mydomain.com marathon[20523]: com.sun.jersey.api.NotFoundException: null for uri: https://h2.mydomain.com:8443/pkgpanda/active.buildinfo.full.json
`

**Comment by MrMarvin** [comment]
@dariko the request for the `pkgpanda/active.buildinfo.full.json` seems to be unrelated to the actual architectural flaw of directly accessing mesos-agents. It is the (tbhq extremly hacky) way of deciding if marathon is running as part of a DCOS installation, done by the Marathon-UI.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1711. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1711. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
