### ISSUE TITLE
Resident Tasks: Flaky test: config change

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3477]
```
16:13:30]W:	 [Step 3/3]  [31m- Config Change *** FAILED *** (3 seconds, 528 milliseconds) [0m
[16:13:30]W:	 [Step 3/3]  [31m  6 was not equal to 5 (ResidentTaskIntegrationTest.scala:187) [0m
[16:13:30]W:	 [Step 3/3]  [31m  org.scalatest.exceptions.TestFailedException: [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6318) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$8.apply(ResidentTaskIntegrationTest.scala:187) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$8.apply(ResidentTaskIntegrationTest.scala:168) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply$mcV$sp(ResidentTaskIntegrationTest.scala:225) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:225) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:225) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.Transformer.apply(Transformer.scala:22) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.Transformer.apply(Transformer.scala:20) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.Suite$class.withFixture(Suite.scala:1121) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.FunSuite.withFixture(FunSuite.scala:1559) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at mesosphere.marathon.integration.ResidentTaskIntegrationTest.org$scalatest$BeforeAndAfter$$super$runTest(ResidentTaskIntegrationTest.scala:16) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at mesosphere.marathon.integration.ResidentTaskIntegrationTest.runTest(ResidentTaskIntegrationTest.scala:16) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401) [0m
[16:13:30]W:	 [Step 3/3]  [31m  at scala.collection.immutable.List.foreach(List.scala:381) [0m

```

**Comment by meichstedt** [comment]
The underlying problem is the same as for #3579. Closing this as a duplicate.
