### ISSUE TITLE
Could not send response error 500: java.lang.RuntimeException: while proxying

### ISSUE THREAD

**Issue by felixb** [mesosphere/marathon#3491]
We found marathon api responses with http response code 200 but content-length 0.
The log states, that marathon ran into timeout while proxying the request to the actual leader.

I'd expect it to return a 5xx instead of a 200.

system info:
- mesos 0.26
- marathon 0.14
- centos 7
- mesophere rpm packages

logs:

```
423419459 [qtp448131210-57] INFO  m.m.a.JavaUrlConnectionRequestForwarder$ - Proxying request to GET http://marathon-hosts-xxx.example.org:8080/v2/apps?requestid=cfa4a7e451ffd21f5a5a0fb5371c9feab8fe9f12 from marathon-hosts-xxx.example.org:8080
423429465 [qtp448131210-57] WARN  o.e.jetty.servlet.ServletHandler - /v2/apps
java.lang.RuntimeException: while proxying
        at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:146) ~[marathon:0.14.0]
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) ~[marathon:0.14.0]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) ~[marathon:0.14.0]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) ~[marathon:0.14.0]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) ~[marathon:0.14.0]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667) ~[marathon:0.14.0]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [marathon:0.14.0]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114) [marathon:0.14.0]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [marathon:0.14.0]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048) [marathon:0.14.0]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [marathon:0.14.0]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon:0.14.0]
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [marathon:0.14.0]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) [marathon:0.14.0]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon:0.14.0]
        at org.eclipse.jetty.server.Server.handle(Server.java:517) [marathon:0.14.0]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302) [marathon:0.14.0]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [marathon:0.14.0]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245) [marathon:0.14.0]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [marathon:0.14.0]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [marathon:0.14.0]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [marathon:0.14.0]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [marathon:0.14.0]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [marathon:0.14.0]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [marathon:0.14.0]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_74]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_74]
        at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_74]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_74]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_74]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_74]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_74]
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704) ~[na:1.8.0_74]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[na:1.8.0_74]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[na:1.8.0_74]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_74]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_74]
        at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.copyConnectionResponse$1(LeaderProxyFilter.scala:260) ~[marathon:0.14.0]
        at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.forward(LeaderProxyFilter.scala:299) ~[marathon:0.14.0]
        at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) ~[marathon:0.14.0]
        at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) ~[marathon:0.14.0]
        at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) ~[marathon:0.14.0]
        at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:142) ~[marathon:0.14.0]
        ... 25 common frames omitted
423429466 [qtp448131210-57] WARN  o.eclipse.jetty.server.HttpChannel - //127.0.0.1:8080/v2/apps?requestid=cfa4a7e451ffd21f5a5a0fb5371c9feab8fe9f12
java.lang.RuntimeException: while proxying
        at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:146) ~[marathon:0.14.0]
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) ~[marathon:0.14.0]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) ~[marathon:0.14.0]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) ~[marathon:0.14.0]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) ~[marathon:0.14.0]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667) ~[marathon:0.14.0]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) ~[marathon:0.14.0]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114) ~[marathon:0.14.0]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) ~[marathon:0.14.0]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048) ~[marathon:0.14.0]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[marathon:0.14.0]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) ~[marathon:0.14.0]
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) ~[marathon:0.14.0]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) ~[marathon:0.14.0]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) ~[marathon:0.14.0]
        at org.eclipse.jetty.server.Server.handle(Server.java:517) ~[marathon:0.14.0]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302) ~[marathon:0.14.0]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [marathon:0.14.0]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245) [marathon:0.14.0]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [marathon:0.14.0]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [marathon:0.14.0]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [marathon:0.14.0]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [marathon:0.14.0]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [marathon:0.14.0]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [marathon:0.14.0]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_74]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_74]
        at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_74]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_74]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_74]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_74]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_74]
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704) ~[na:1.8.0_74]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[na:1.8.0_74]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[na:1.8.0_74]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_74]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_74]
        at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.copyConnectionResponse$1(LeaderProxyFilter.scala:260) ~[marathon:0.14.0]
        at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.forward(LeaderProxyFilter.scala:299) ~[marathon:0.14.0]
        at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:56) ~[marathon:0.14.0]
        at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:25) ~[marathon:0.14.0]
        at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:55) ~[marathon:0.14.0]
        at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:142) ~[marathon:0.14.0]
        ... 25 common frames omitted
423429466 [qtp448131210-57] WARN  o.eclipse.jetty.server.HttpChannel - Could not send response error 500: java.lang.RuntimeException: while proxying
```

**Comment by jdef** [comment]
hacking on a solution here. https://phabricator.mesosphere.com/D133
