### ISSUE TITLE
Resident Tasks: Flaky test: restart

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3579]
```

[10:42:00][Step 3/3] - Restart *** FAILED *** (3 seconds, 130 milliseconds)
[10:42:00][Step 3/3]   false was not equal to true (ResidentTaskIntegrationTest.scala:159)
[10:42:00][Step 3/3]   org.scalatest.exceptions.TestFailedException:
[10:42:00][Step 3/3]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[10:42:00][Step 3/3]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6318)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$7.apply(ResidentTaskIntegrationTest.scala:159)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$7.apply(ResidentTaskIntegrationTest.scala:143)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply$mcV$sp(ResidentTaskIntegrationTest.scala:225)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:225)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:225)
[10:42:00][Step 3/3]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[10:42:00][Step 3/3]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[10:42:00][Step 3/3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[10:42:00][Step 3/3]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[10:42:00][Step 3/3]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158)
[10:42:00][Step 3/3]   at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
[10:42:00][Step 3/3]   at org.scalatest.FunSuite.withFixture(FunSuite.scala:1559)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.org$scalatest$BeforeAndAfter$$super$runTest(ResidentTaskIntegrationTest.scala:16)
[10:42:00][Step 3/3]   at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.runTest(ResidentTaskIntegrationTest.scala:16)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[10:42:00][Step 3/3]   at scala.collection.immutable.List.foreach(List.scala:381)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:200)
[10:42:00][Step 3/3]   at org.scalatest.FunSuite.runTests(FunSuite.scala:1559)
[10:42:00][Step 3/3]   at org.scalatest.Suite$class.run(Suite.scala:1423)
[10:42:00][Step 3/3]   at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1559)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
[10:42:00][Step 3/3]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[10:42:00][Step 3/3]   at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:204)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.org$scalatest$BeforeAndAfterAllConfigMap$$super$run(ResidentTaskIntegrationTest.scala:16)
[10:42:00][Step 3/3]   at org.scalatest.BeforeAndAfterAllConfigMap$class.liftedTree1$1(BeforeAndAfterAllConfigMap.scala:248)
[10:42:00][Step 3/3]   at org.scalatest.BeforeAndAfterAllConfigMap$class.run(BeforeAndAfterAllConfigMap.scala:247)
[10:42:00][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.org$scalatest$BeforeAndAfter$$super$run(ResidentTaskIntegrationTest.scala:16)
[10:42:00][Step 3/3]   at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
```

(https://teamcity.mesosphere.io/viewLog.html?buildId=178347&buildTypeId=Oss_Marathon_IntegrationScaleTests&tab=buildLog#_focus=50222)

**Comment by meichstedt** [comment]
Analysis: after a config change or restart, there are sometimes 6 instead of 5 instances. We enforce an `UpgradeStrategy` that allows to restart resident apps without creating new instances:
```
strategy.minimumHealthCapacity should be <= 0.5
strategy.maximumOverCapacity should be == 0.0
```
However, the `TaskReplaceActor` increases the maxCapacity by one regardless of whether we can kill instances immediately and don't need to have a higher maxCapacity:
```
    // make sure at least one task can be started to get the ball rolling
    if (maxCapacity == app.instances)
      maxCapacity += 1
```
