### ISSUE TITLE
Could not determine the current leader

### ISSUE THREAD

**Issue by simoneroselli** [mesosphere/marathon#3725]
Hi, 
I get this error trying to deploy Marathon as Docker container on a dedicated Mesos slave. It's using a remote Zookeeper, running on 3 Mesos master.

If I run Marathon directly from the slave itself (package), using the same configuration used in the Docker environment, everything is fine.

From inside the container, I get:
`
Problem accessing /. Reason:
Could not determine the current leader
`
- Tried with both "host" and "bridge" Docker network mode
- Zookeeper and Mesos master are perfectly reachable from inside the container
- Zookeeper storage path is present for the new marathon

Thanks

**Comment by vlombardi** [comment]
Hi,
I had the same problem and solved from ZooKeeper (Exhibitor) deleting the nodes \marathon\leader\member-N, where N was related to all non-leader hosts.

ZK then correctly recreated them automatically.

In my case the problem was raised by temporary network unreachability of hosts...

Hope this can help others.

Regards

**Comment by jgarcia-mesosphere** [comment]
Looks similar to #2751

**Comment by TeddyRux** [comment]
I ran into the same issue this morning on a cluster running 3 mesos master and zk installed locally on each instance. 

Marathon: `1.1.0`
Mesos: `0.28.01
ZK: `1.5.5`

The logs of the current leader were filled with the same errors from 
`INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some([ip])`

**Comment by HackToday** [comment]
it seems this issue still not solved ?

**Comment by bwhaley** [comment]
I just experience a very similar issue. 3 Mesos masters, 3 Zookeeper masters on the same nodes. Zookeeper managed via Exhibitor. One of the Zookeeper nodes failed. Exhibitor reconfigured and restarted zookeeper on the healthy nodes. Marathon UI was throwing the error from OP. All docker containers deployed by Marathon remained running. In the exhibitor UI I could see that all the tasks under /marathon/state/* were still there. I deleted the non-leader nodes from /marathon/leader and marathon immediately recovered.

**Comment by renou** [comment]
Happened again on our prod environment. Fixed by clean up zookeeper mararthon/leaders node. Terrifying...

**Comment by TeddyRux** [comment]
This issue continues to happen for me sporadically. I was able to gather some logs.

Marathon
```
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16496 [2016-11-03 19:17:09,164] ERROR error while getting current leader (mesosphere.marathon.MarathonLeaderInfo$$EnhancerByGuice$$606d8c78:qtp1484119658-13041448)
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16499 org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /marathon/leader
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16500         at org.apache.zookeeper.KeeperException.create(KeeperException.java:99) ~[marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16501         at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16501         at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1472) ~[marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16501         at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1500) ~[marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16502         at com.twitter.common.zookeeper.Group.getMemberIds(Group.java:147) ~[marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16502         at mesosphere.marathon.core.leadership.CandidateImpl.getLeaderData(CandidateImpl.java:119) ~[marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16503         at mesosphere.marathon.MarathonLeaderInfo$$anonfun$currentLeaderHostPort$1$$anonfun$apply$1.apply(MarathonLeaderInfo.scala:31) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16504         at mesosphere.marathon.MarathonLeaderInfo$$anonfun$currentLeaderHostPort$1$$anonfun$apply$1.apply(MarathonLeaderInfo.scala:29) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16505         at scala.Option.flatMap(Option.scala:171) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16505         at mesosphere.marathon.MarathonLeaderInfo$$anonfun$currentLeaderHostPort$1.apply(MarathonLeaderInfo.scala:29) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16506         at mesosphere.marathon.MarathonLeaderInfo$$anonfun$currentLeaderHostPort$1.apply(MarathonLeaderInfo.scala:29) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16506         at mesosphere.marathon.metrics.Metrics$Timer.apply(Metrics.scala:100) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16508         at mesosphere.marathon.MarathonLeaderInfo.currentLeaderHostPort(MarathonLeaderInfo.scala:28) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16509         at mesosphere.marathon.MarathonLeaderInfo$$EnhancerByGuice$$606d8c78.CGLIB$currentLeaderHostPort$0(<generated>) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16509         at mesosphere.marathon.MarathonLeaderInfo$$EnhancerByGuice$$606d8c78$$FastClassByGuice$$bc703c1e.invoke(<generated>) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16510         at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16511         at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16511         at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:62) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16511         at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16512         at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:61) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16512         at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16512         at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16513         at mesosphere.marathon.MarathonLeaderInfo$$EnhancerByGuice$$606d8c78.currentLeaderHostPort(<generated>) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16513         at mesosphere.marathon.api.LeaderProxyFilter.leaderDataOpt$lzycompute$1(LeaderProxyFilter.scala:122) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16513         at mesosphere.marathon.api.LeaderProxyFilter.leaderDataOpt$1(LeaderProxyFilter.scala:122) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16514         at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:128) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16514         at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16514         at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16515         at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16515         at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16515         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16516         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16516         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16516         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16516         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16517         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16517         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16518         at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16518         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16518         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16518         at org.eclipse.jetty.server.Server.handle(Server.java:517) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16519         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16520         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16520         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16521         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16521         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16521         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16521         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16522         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16522         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [marathon.jar:1.1.1]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16522         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
/var/log/marathon/@40000000581b8ef0003efb0c.s:2016-11-03_19:17:09.16523 [2016-11-03 19:17:09,164] INFO Do not proxy to myself. Waiting for consistent leadership state. Are we leader?: false, leader: None (mesosphere.marathon.api.LeaderProxyFilter$:qtp1484119658-13041448)
``` 

Exhibitor
```
2016-11-03_19:17:12.83488 2016-11-03 19:17:12 INFO  ActivityLog:128 - State: not serving
2016-11-03_19:17:12.83496 2016-11-03 19:17:12 INFO  ActivityLog:128 - Server list has changed
2016-11-03_19:17:12.83517 2016-11-03 19:17:12 INFO  ActivityLog:128 - Attempting to stop instance
2016-11-03_19:17:12.83524 2016-11-03 19:17:12 INFO  ActivityLog:128 - Attempting to start/restart ZooKeeper
2016-11-03_19:17:13.13214 2016-11-03 19:17:13 INFO  ActivityLog:128 - Kill attempted result: 0
2016-11-03_19:17:13.32038 2016-11-03 19:17:13 INFO  ActivityLog:128 - Starting in standalone mode
2016-11-03_19:17:13.32352 2016-11-03 19:17:13 INFO  ActivityLog:128 - Process started via: /opt/zookeeper/zookeeper-3.4.6/bin/zkServer.sh
2016-11-03_19:17:13.32474 2016-11-03 19:17:13 ERROR ActivityLog:106 - ZooKeeper Server: JMX enabled by default
2016-11-03_19:17:13.32828 2016-11-03 19:17:13 ERROR ActivityLog:106 - ZooKeeper Server: Using config: /opt/zookeeper/zookeeper-3.4.6/bin/../conf/zoo.cfg
2016-11-03_19:17:14.33223 2016-11-03 19:17:14 INFO  ActivityLog:128 - ZooKeeper Server: Starting zookeeper ... STARTED
```
I checked zookeeper, and it looks like it was failing on a java.io error, but I wasn't able to capture before it got overwritten.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1997. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
