### ISSUE TITLE
"Running in Development Mode" doesn't work as it tries to elect a leader

### ISSUE THREAD

**Issue by sayden** [mesosphere/marathon#3825]
As pointed out int README.md, to run in Development mode you just need to run the following command (once you have Apache Mesos Master and Slaves running and a Zookeeper):

`./bin/start --master local --zk zk://localhost:2181/marathon`

It shows this `INFO All services up and running. (mesosphere.marathon.Main$:main)` but when you open `localhost:8080` it shows a 503 with the message "Could not determine the current leader". Console output repeats the following message few times:

`INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)`

```
MESOS_NATIVE_JAVA_LIBRARY is not set. Searching in /usr/lib /usr/local/lib.
MESOS_NATIVE_LIBRARY, MESOS_NATIVE_JAVA_LIBRARY set to ''
[2016-04-24 22:03:11,283] INFO Starting Marathon 1.1.0-RC1 with --master local --zk zk://localhost:2181/marathon (mesosphere.marathon.Main$:main)
[2016-04-24 22:03:12,269] INFO Connecting to ZooKeeper... (mesosphere.marathon.Main$:main)
[2016-04-24 22:03:12,275] INFO Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,275] INFO Client environment:host.name=localhost.localdomain (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,275] INFO Client environment:java.version=1.8.0_71 (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,275] INFO Client environment:java.vendor=Oracle Corporation (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,275] INFO Client environment:java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.71-1.b15.fc22.x86_64/jre (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,276] INFO Client environment:java.class.path=bin/../target/scala-2.11/marathon-assembly-1.1.0-RC1.jar (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,276] INFO Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,276] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,276] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,276] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,276] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,276] INFO Client environment:os.version=4.3.6-201.fc22.x86_64 (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,276] INFO Client environment:user.name=mariocaster (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,276] INFO Client environment:user.home=/home/mariocaster (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,276] INFO Client environment:user.dir=/home/mariocaster/Downloads/marathon-1.1.0-RC1 (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,277] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=10000 watcher=com.twitter.common.zookeeper.ZooKeeperClient$3@7fb9f71f (org.apache.zookeeper.ZooKeeper:main)
[2016-04-24 22:03:12,294] INFO Opening socket connection to server localhost.localdomain/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn:main-SendThread(localhost.localdomain:2181))
[2016-04-24 22:03:12,355] INFO Socket connection established to localhost.localdomain/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn:main-SendThread(localhost.localdomain:2181))
[2016-04-24 22:03:12,366] INFO Session establishment complete on server localhost.localdomain/127.0.0.1:2181, sessionid = 0x15449d5fd680004, negotiated timeout = 10000 (org.apache.zookeeper.ClientCnxn:main-SendThread(localhost.localdomain:2181))
[2016-04-24 22:03:12,903] WARN Method [public javax.ws.rs.core.Response mesosphere.marathon.api.MarathonExceptionMapper.toResponse(java.lang.Throwable)] is synthetic and is being intercepted by [mesosphere.marathon.DebugModule$MetricsBehavior@f14e5bf]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all. (com.google.inject.internal.ProxyFactory:main)
[2016-04-24 22:03:13,183] INFO Logging initialized @2518ms (org.eclipse.jetty.util.log:main)
[2016-04-24 22:03:13,831] INFO Slf4jLogger started (akka.event.slf4j.Slf4jLogger:marathon-akka.actor.default-dispatcher-4)
[2016-04-24 22:03:13,927] INFO Registering in ZooKeeper with hostPort:asusfedora:8080 (mesosphere.marathon.MarathonModule:main)
[2016-04-24 22:03:14,013] INFO Started TaskTrackerUpdateStepsProcessorImpl with steps:
* continueOnError(notifyHealthCheckManager)
* continueOnError(notifyRateLimiter)
* continueOnError(notifyLaunchQueue)
* continueOnError(emitUpdate)
* continueOnError(postTaskStatusEvent)
* continueOnError(scaleApp) (mesosphere.marathon.core.task.tracker.impl.TaskTrackerUpdateStepProcessorImpl:main)
[2016-04-24 22:03:14,049] INFO Calling reviveOffers is enabled. Use --disable_revive_offers_for_new_apps to disable. (mesosphere.marathon.core.flow.FlowModule:main)
[2016-04-24 22:03:14,054] INFO Started status update processor (mesosphere.marathon.core.task.update.impl.TaskStatusUpdateProcessorImpl$$EnhancerByGuice$$a012a4d:main)
[2016-04-24 22:03:14,064] INFO All actors suspended:
* Actor[akka://marathon/user/offerMatcherManager#1367534127]
* Actor[akka://marathon/user/reviveOffersWhenWanted#817782264]
* Actor[akka://marathon/user/AbdicateOnConnectionLoss#1125008822]
* Actor[akka://marathon/user/offerMatcherLaunchTokens#2074006134]
* Actor[akka://marathon/user/rateLimiter#-1494768479]
* Actor[akka://marathon/user/taskTracker#-1670423325]
* Actor[akka://marathon/user/offersWantedForReconciliation#1108159943]
* Actor[akka://marathon/user/launchQueue#-1541833419]
* Actor[akka://marathon/user/killOverdueStagedTasks#-2135141463] (mesosphere.marathon.core.leadership.impl.LeadershipCoordinatorActor:marathon-akka.actor.default-dispatcher-3)
[2016-04-24 22:03:14,221] INFO Now standing by. Closing existing handles and rejecting new. (mesosphere.marathon.event.http.HttpEventStreamActor:marathon-akka.actor.default-dispatcher-7)
[2016-04-24 22:03:14,265] INFO Adding HTTP support. (mesosphere.chaos.http.HttpModule:main)
[2016-04-24 22:03:14,265] INFO No HTTPS support configured. (mesosphere.chaos.http.HttpModule:main)
[2016-04-24 22:03:14,298] INFO Starting up (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$6213a083:MarathonSchedulerService$$EnhancerByGuice$$6213a083)
[2016-04-24 22:03:14,298] INFO Beginning run (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$6213a083:MarathonSchedulerService$$EnhancerByGuice$$6213a083)
[2016-04-24 22:03:14,300] INFO Will offer leadership after 500 milliseconds backoff (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$6213a083:MarathonSchedulerService$$EnhancerByGuice$$6213a083)
[2016-04-24 22:03:14,315] INFO jetty-9.3.z-SNAPSHOT (org.eclipse.jetty.server.Server:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,547] INFO Registering com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchAdapter as a provider class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.MarathonExceptionMapper as a provider class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.AppsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.TasksResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.EventSubscriptionsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.QueueResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.GroupsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.InfoResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.LeaderResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.DeploymentsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.ArtifactsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.SchemaResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,550] INFO Registering mesosphere.marathon.api.v2.PluginsResource as a root resource class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,552] INFO Initiating Jersey application, version 'Jersey: 1.18.1 02/19/2014 03:28 AM' (com.sun.jersey.server.impl.application.WebApplicationImpl:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,602] INFO Binding com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchAdapter to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,620] INFO Binding mesosphere.marathon.api.MarathonExceptionMapper to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:14,825] INFO Using HA and therefore offering leadership (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$6213a083:ForkJoinPool-2-worker-13)
[2016-04-24 22:03:14,854] INFO Set group member ID to member_0000000008 (com.twitter.common.zookeeper.Group:ForkJoinPool-2-worker-13)
[2016-04-24 22:03:14,869] INFO Candidate /marathon/leader/member_0000000008 is now leader of group: [member_0000000008] (com.twitter.common.zookeeper.CandidateImpl:ForkJoinPool-2-worker-13)
[2016-04-24 22:03:14,871] INFO Elected (Leader Interface) (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$6213a083:ForkJoinPool-2-worker-13)
[2016-04-24 22:03:14,877] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=10000 watcher=com.twitter.zk.EventBroker@78563ce6 (org.apache.zookeeper.ZooKeeper:ForkJoinPool-2-worker-13)
[2016-04-24 22:03:14,884] INFO Opening socket connection to server localhost.localdomain/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn:ForkJoinPool-2-worker-13-SendThread(localhost.localdomain:2181))
[2016-04-24 22:03:14,885] INFO Socket connection established to localhost.localdomain/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn:ForkJoinPool-2-worker-13-SendThread(localhost.localdomain:2181))
[2016-04-24 22:03:14,888] INFO Session establishment complete on server localhost.localdomain/127.0.0.1:2181, sessionid = 0x15449d5fd680005, negotiated timeout = 10000 (org.apache.zookeeper.ClientCnxn:ForkJoinPool-2-worker-13-SendThread(localhost.localdomain:2181))
[2016-04-24 22:03:14,965] INFO Migration successfully applied for version Version(1, 1, 0) (mesosphere.marathon.state.Migration:ForkJoinPool-2-worker-5)
[2016-04-24 22:03:14,966] INFO Call onElected leadership callbacks on EntityStoreCache(MarathonStore(app:)), EntityStoreCache(MarathonStore(group:)), EntityStoreCache(MarathonStore(deployment:)), EntityStoreCache(MarathonStore(framework:)), EntityStoreCache(MarathonStore(taskFailure:)), EntityStoreCache(MarathonStore(events:)) (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$6213a083:ForkJoinPool-2-worker-13)
[2016-04-24 22:03:14,984] INFO Finished onElected leadership callbacks (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$6213a083:ForkJoinPool-2-worker-13)
[2016-04-24 22:03:14,989] INFO no interest in offers for reservation reconciliation anymore. (mesosphere.marathon.core.matcher.reconcile.impl.OffersWantedForReconciliationActor:marathon-akka.actor.default-dispatcher-7)
[2016-04-24 22:03:14,991] INFO Started. Will remain interested in offer reconciliation for 17500 milliseconds when needed. (mesosphere.marathon.core.matcher.reconcile.impl.OffersWantedForReconciliationActor:marathon-akka.actor.default-dispatcher-7)
[2016-04-24 22:03:15,011] INFO started RateLimiterActor (mesosphere.marathon.core.launchqueue.impl.RateLimiterActor:marathon-akka.actor.default-dispatcher-3)
[2016-04-24 22:03:15,018] INFO Register as ZK Listener (mesosphere.marathon.core.leadership.impl.AbdicateOnConnectionLossActor:marathon-akka.actor.default-dispatcher-2)
[2016-04-24 22:03:15,019] INFO TaskTrackerActor is starting. Task loading initiated. (mesosphere.marathon.core.task.tracker.impl.TaskTrackerActor:marathon-akka.actor.default-dispatcher-6)
[2016-04-24 22:03:15,021] INFO All actors active:
* Actor[akka://marathon/user/offerMatcherManager#1367534127]
* Actor[akka://marathon/user/reviveOffersWhenWanted#817782264]
* Actor[akka://marathon/user/AbdicateOnConnectionLoss#1125008822]
* Actor[akka://marathon/user/offerMatcherLaunchTokens#2074006134]
* Actor[akka://marathon/user/rateLimiter#-1494768479]
* Actor[akka://marathon/user/taskTracker#-1670423325]
* Actor[akka://marathon/user/offersWantedForReconciliation#1108159943]
* Actor[akka://marathon/user/launchQueue#-1541833419]
* Actor[akka://marathon/user/killOverdueStagedTasks#-2135141463] (mesosphere.marathon.core.leadership.impl.LeadershipCoordinatorActor:marathon-akka.actor.default-dispatcher-13)
[2016-04-24 22:03:15,028] INFO Create new Scheduler Driver with frameworkId: None (mesosphere.marathon.MarathonSchedulerDriver$:ForkJoinPool-2-worker-13)
[2016-04-24 22:03:15,033] INFO About to load 0 tasks (mesosphere.marathon.core.task.tracker.impl.TaskLoaderImpl:ForkJoinPool-2-worker-9)
[2016-04-24 22:03:15,035] INFO Loaded 0 tasks (mesosphere.marathon.core.task.tracker.impl.TaskLoaderImpl:ForkJoinPool-2-worker-9)
[2016-04-24 22:03:15,043] INFO Task loading complete. (mesosphere.marathon.core.task.tracker.impl.TaskTrackerActor:marathon-akka.actor.default-dispatcher-6)
Failed to load native Mesos library from 
java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: 
	at java.lang.Runtime.load0(Runtime.java:806)
	at java.lang.System.load(System.java:1086)
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:159)
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:188)
	at org.apache.mesos.MesosSchedulerDriver.<clinit>(MesosSchedulerDriver.java:61)
	at mesosphere.marathon.MarathonSchedulerDriver$.newDriver(MarathonSchedulerDriver.scala:81)
	at mesosphere.marathon.MesosSchedulerDriverFactory.createDriver(SchedulerDriverFactory.scala:28)
	at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:62)
	at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27)
	at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:61)
	at mesosphere.marathon.MarathonSchedulerService.liftedTree1$1(MarathonSchedulerService.scala:282)
	at mesosphere.marathon.MarathonSchedulerService.onElected(MarathonSchedulerService.scala:267)
	at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:62)
	at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27)
	at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:61)
	at com.twitter.common.zookeeper.CandidateImpl$4.onGroupChange(CandidateImpl.java:155)
	at com.twitter.common.zookeeper.Group$GroupMonitor.setMembers(Group.java:665)
	at com.twitter.common.zookeeper.Group$GroupMonitor.watchGroup(Group.java:638)
	at com.twitter.common.zookeeper.Group$GroupMonitor.access$900(Group.java:579)
	at com.twitter.common.zookeeper.Group$4.get(Group.java:551)
	at com.twitter.common.zookeeper.Group$4.get(Group.java:548)
	at com.twitter.common.util.BackoffHelper$1.get(BackoffHelper.java:109)
	at com.twitter.common.util.BackoffHelper$1.get(BackoffHelper.java:107)
	at com.twitter.common.util.BackoffHelper.doUntilResult(BackoffHelper.java:127)
	at com.twitter.common.util.BackoffHelper.doUntilSuccess(BackoffHelper.java:107)
	at com.twitter.common.zookeeper.Group.watch(Group.java:548)
	at com.twitter.common.zookeeper.CandidateImpl.offerLeadership(CandidateImpl.java:136)
	at mesosphere.marathon.MarathonSchedulerService$$anonfun$mesosphere$marathon$MarathonSchedulerService$$offerLeadership$1$$anonfun$apply$2.apply(MarathonSchedulerService.scala:370)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2016-04-24 22:03:15,133] INFO interested in offers for reservation reconciliation because of becoming leader (until 2016-04-24T20:03:32.500Z) (mesosphere.marathon.core.matcher.reconcile.impl.OffersWantedForReconciliationActor:marathon-akka.actor.default-dispatcher-7)
[2016-04-24 22:03:15,275] INFO Binding mesosphere.marathon.api.v2.AppsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,330] INFO Loading plugins implementing 'mesosphere.marathon.plugin.auth.Authenticator' from these urls: [] (mesosphere.marathon.core.plugin.impl.PluginManagerImpl:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,334] INFO Found 0 plugins. (mesosphere.marathon.core.plugin.impl.PluginManagerImpl:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,336] INFO Loading plugins implementing 'mesosphere.marathon.plugin.auth.Authorizer' from these urls: [] (mesosphere.marathon.core.plugin.impl.PluginManagerImpl:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,336] INFO Found 0 plugins. (mesosphere.marathon.core.plugin.impl.PluginManagerImpl:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,344] INFO Binding mesosphere.marathon.api.v2.TasksResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,346] INFO Binding mesosphere.marathon.api.v2.EventSubscriptionsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,348] INFO Binding mesosphere.marathon.api.v2.QueueResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,353] INFO Binding mesosphere.marathon.api.v2.GroupsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,355] INFO Binding mesosphere.marathon.api.v2.InfoResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,357] INFO Binding mesosphere.marathon.api.v2.LeaderResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,359] INFO Binding mesosphere.marathon.api.v2.DeploymentsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,369] INFO Binding mesosphere.marathon.api.v2.ArtifactsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,370] INFO Binding mesosphere.marathon.api.v2.SchemaResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,373] INFO Binding mesosphere.marathon.api.v2.PluginsResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,373] INFO Loading plugins implementing 'mesosphere.marathon.plugin.http.HttpRequestHandler' from these urls: [] (mesosphere.marathon.core.plugin.impl.PluginManagerImpl:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,373] INFO Found 0 plugins. (mesosphere.marathon.core.plugin.impl.PluginManagerImpl:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,386] INFO Started o.e.j.s.ServletContextHandler@31700804{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,405] INFO Started ServerConnector@c52a44a{HTTP/1.1,[http/1.1]}{0.0.0.0:8080} (org.eclipse.jetty.server.ServerConnector:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,406] INFO Started @4742ms (org.eclipse.jetty.server.Server:HttpService$$EnhancerByGuice$$77b4f294 STARTING)
[2016-04-24 22:03:15,406] INFO All services up and running. (mesosphere.marathon.Main$:main)
[2016-04-24 22:03:21,457] INFO Do not proxy to myself. Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:21,459] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:21,711] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:21,963] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:22,215] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:22,467] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:22,719] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:22,971] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:23,224] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:23,476] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:23,728] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:23,980] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(asusfedora:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1523957322-38)
[2016-04-24 22:03:24,249] INFO 192.168.1.39 - - [24/Apr/2016:20:03:21 +0000] "GET //192.168.1.39:8080/ HTTP/1.1" 503 344 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36" 279 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$7d007151:qtp1523957322-38)
```

**Comment by sayden** [comment]
Sorry, my fault.

As it points in the output, it failed to load native Mesos library as `MESOS_NATIVE_JAVA_LIBRARY` was not properly set. Once I set it correctly the UI appeard correctly on `localhost:8080`

Can suggest a better output for the error in the UI?
