### ISSUE TITLE
Application show up in Mesos but not in Marathon apps list

### ISSUE THREAD

**Issue by thepolina** [mesosphere/marathon#3892]
**Environment:**
Mapr5, mesos 0.28, marathon 1.1.0, docker 1.9.0, ubuntu 14.04

**Description:**
App has been killed via Marathon
App is still running 
It still showing up in Mesos
CTRL-f on a list of Marathon apps list cannot find this app
Direct link to this app in Marathon still exists ans shows that app is running
If in Marathon I press the button destroy again I get this message

> Error destroying /app-prod-21: App '/app-prod-21' does not exist

Happens randomly

**Comment by thepolina** [comment]
Hey 
Further investigation shows a bug in Marathon apps list. 
**More details:**
Direct link to app remains, but app not in list
Number of tasks is 1
App is still in Mesos
If I manually stop docker container Marathon restarts it
Container still in Zookeeper
When I try to destroy it I got this alert
Error destroying /app0: App '/app0' does not exist
When I try to suspend it I got this
Error scaling /app0: Object is not valid
When I try to scale it I got this
Error scaling /app0: Object is not valid
When I try to restart I got this
Error restarting /app0: App '/app0' does not exist

Looking in source code I see that we get this UnknownAppException when it iterates over apps list but cannot find given app id
https://github.com/mesosphere/marathon/blob/a28e6a68497c4d409cb7eef56275d1af17b67231/src/main/scala/mesosphere/marathon/api/TaskKiller.scala#L50 

Nothing suspicious in logs
Please let me know if you need any additional details according this bug

**Comment by sunshinezeng** [comment]
Seeing the same issue. Not sure whether it is related to us deleting the apps under a higher concurrency

**Comment by miry** [comment]
I have same issue. After upgrade from Marathon 0.14 to 0.15. I had problem with HealthCheck validation. 


```
 mesosphere.marathon.ValidationFailedException: Validation failed
         at mesosphere.marathon.api.v2.Validation$.validateOrThrow(Validation.scala:18) ~[marathon:0.15.6]
         at mesosphere.marathon.state.GroupManager$$anonfun$upgrade$1$$anonfun$2$$anonfun$apply$11.apply(GroupManager.scala:160) ~[marathon:0.15.6]
         at mesosphere.marathon.state.GroupManager$$anonfun$upgrade$1$$anonfun$2$$anonfun$apply$11.apply(GroupManager.scala:158) ~[marathon:0.15.6]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[marathon:0.15.6]
         at scala.util.Try$.apply(Try.scala:192) ~[marathon:0.15.6]
         at scala.util.Success.map(Try.scala:237) ~[marathon:0.15.6]
         at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon:0.15.6]
         at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon:0.15.6]
         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [marathon:0.15.6]
         at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) [marathon:0.15.6]
         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [marathon:0.15.6]
         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [marathon:0.15.6]
         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [marathon:0.15.6]
         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [marathon:0.15.6]
         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [marathon:0.15.6]
````

**Comment by jeschkies** [comment]
Do you have the issue with Marathon 1.3?

**Comment by sunshinezeng** [comment]
Hi Karsten.
We just upgraded to 1.3 recently. Haven't seen this issue yet.
I will keep you posted if we see this in 1.3 again.
Btw, is there any change 1.3 that you think will address this problem?
Thanks!
Yang

2017-01-23 6:25 GMT-08:00 Karsten Jeschkies <notifications@github.com>:

**Comment by sunshinezeng** [comment]
Hi Karsten.
Actually we are seeing it now in our test environment.
Marathon shows no apps but Mesos master still shows 200+ tasks running.
I did a "sudo rm -f /var/run/mesos/meta/slaves/latest" on all the agents
before this happens. Is it related?
Thanks!
Yang

2017-01-23 8:19 GMT-08:00 Sunshine Zeng <sunshine.zengyang@gmail.com>:

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4499. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
