### ISSUE TITLE
Marathon loading application error while restarting mesos

### ISSUE THREAD

**Issue by wenma** [mesosphere/marathon#3905]
```
[2016-05-17 16:32:59,256] INFO About to load 4 tasks (mesosphere.marathon.core.task.tracker.impl.TaskLoaderImpl:ForkJoinPool-2-worker-3)
[2016-05-17 16:32:59,257] INFO Loaded 4 tasks (mesosphere.marathon.core.task.tracker.impl.TaskLoaderImpl:ForkJoinPool-2-worker-3)
[2016-05-17 16:32:59,257] INFO TaskTrackerActor is starting. Task loading initiated. (mesosphere.marathon.core.task.tracker.impl.TaskTrackerActor:marathon-akka.actor.default-dispatcher-11)
[2016-05-17 16:32:59,258] ERROR while loading tasks (akka.actor.OneForOneStrategy:marathon-akka.actor.default-dispatcher-13)
java.lang.IllegalStateException: while loading tasks
    at mesosphere.marathon.core.task.tracker.impl.TaskTrackerActor$$anonfun$initializing$1.applyOrElse(TaskTrackerActor.scala:102) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.impl.TaskTrackerActor.aroundReceive(TaskTrackerActor.scala:63) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [marathon-assembly-1.1.1.jar:1.1.1]
    at akka.actor.ActorCell.invoke(ActorCell.scala:487) [marathon-assembly-1.1.1.jar:1.1.1]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [marathon-assembly-1.1.1.jar:1.1.1]
    at akka.dispatch.Mailbox.run(Mailbox.scala:221) [marathon-assembly-1.1.1.jar:1.1.1]
    at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [marathon-assembly-1.1.1.jar:1.1.1]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [marathon-assembly-1.1.1.jar:1.1.1]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [marathon-assembly-1.1.1.jar:1.1.1]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [marathon-assembly-1.1.1.jar:1.1.1]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [marathon-assembly-1.1.1.jar:1.1.1]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [marathon-assembly-1.1.1.jar:1.1.1]
Caused by: mesosphere.marathon.SerializationFailedException: test_test-es2.2#tmp#b79f4a0a-1be1-11e6-b3cf-56847afe9799 is no valid volumeId
    at mesosphere.marathon.core.task.tracker.impl.ReservationSerializer$$anonfun$1.apply(TaskSerializer.scala:214) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.impl.ReservationSerializer$$anonfun$1.apply(TaskSerializer.scala:212) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.impl.ReservationSerializer$.fromProto(TaskSerializer.scala:212) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.impl.TaskSerializer$.reservation$1(TaskSerializer.scala:41) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.impl.TaskSerializer$.fromProto(TaskSerializer.scala:73) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.TaskTracker$AppTasks$$anonfun$apply$3.apply(TaskTracker.scala:126) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.TaskTracker$AppTasks$$anonfun$apply$3.apply(TaskTracker.scala:126) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.TaskTracker$AppTasks$.apply(TaskTracker.scala:126) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.impl.TaskLoaderImpl$$anonfun$loadTasks$2$$anonfun$apply$4$$anonfun$2.apply(TaskLoaderImpl.scala:27) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.impl.TaskLoaderImpl$$anonfun$loadTasks$2$$anonfun$apply$4$$anonfun$2.apply(TaskLoaderImpl.scala:26) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:370) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.TraversableOnce$class.toMap(TraversableOnce.scala:314) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.collection.AbstractIterator.toMap(Iterator.scala:1194) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.impl.TaskLoaderImpl$$anonfun$loadTasks$2$$anonfun$apply$4.apply(TaskLoaderImpl.scala:28) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at mesosphere.marathon.core.task.tracker.impl.TaskLoaderImpl$$anonfun$loadTasks$2$$anonfun$apply$4.apply(TaskLoaderImpl.scala:22) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.util.Try$.apply(Try.scala:192) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.util.Success.map(Try.scala:237) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[marathon-assembly-1.1.1.jar:1.1.1]
    at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[marathon-assembly-1.1.1.jar:1.1.1]
    ... 5 common frames omitted
```

before restart mesos master, the app test/test-es2.2 is running and active,  but there is someting error when i restarted mesos master.  what should I do ?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4264. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
