### ISSUE TITLE
Deadlock when removing broken apps after upgrade

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3962]
I upgraded from v0.15.3 to v1.1.1 and people can't deply their apps anymore:

``` json
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    },
    {
      "path": "/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id",
      "errors": [
        "Identifier is not child of /abc/foo/staging. Hint: use relative paths."
      ]
    }
  ]
}
```

When I try to remove the problematic group:

```
$ curl -X DELETE https://marathon/v2/groups/abc/foo
{"message":"Object is not valid","details":[{"path":"/groups(0)/groups(2)/apps(0)/id","errors":["Identifier is not child of /abc/bar. Hint: use relative paths."]}]}
```

Then I try to remove new problematic group (same as deployment error):

```
$ curl -X DELETE https://marathon/v2/groups/abc/bar
{"message":"Object is not valid","details":[{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]},{"path":"/groups(0)/groups(38)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/groups(0)/id","errors":["Identifier is not child of /abc/foo/staging. Hint: use relative paths."]}]}
```

People were doing all sorts of nasty stuff because Marathon never validated it before:

```
id: '/abc/bar/%app_env%'
groups:
  - id: '/abc/bar/%app_env%'
    apps:
      - id: '/abc/bar/%app_env%/server'
```

How do I make it work again? I don't mind nuking both `/abc/foo` and `/abc/bar`, but they depend on each other. Redeploying the whole Marathon is not really an option:

![image](https://cloud.githubusercontent.com/assets/89186/15835499/33f35628-2c28-11e6-8d0d-59ffc361f9d5.png)

cc @alberts, @triggity

**Comment by bobrik** [comment]
```
2016-06-06T19:58:22.029 36s3 [2016-06-06 19:58:22,028] INFO [/abc/kafka/foo]: upgrade detected for app (oldVersion FullVersionInfo(2016-06-03T11:06:56.563Z,2016-06-03T11:06:56.563Z,2016-06-03T11:06:56.563Z)) (mesosphere.marathon.upgrade.GroupVersioningUtil$:ForkJoinPool-2-worker-115)
2016-06-06T19:58:22.048 36s3 [2016-06-06 19:58:22,047] WARN Deployment failed for change: 2016-06-06T19:58:22.017Z (mesosphere.marathon.state.GroupManager:ForkJoinPool-2-worker-115)
2016-06-06T19:58:22.048 36s3 mesosphere.marathon.ValidationFailedException: Validation failed
2016-06-06T19:58:22.048 36s3 	at mesosphere.marathon.api.v2.Validation$.validateOrThrow(Validation.scala:18) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.048 36s3 	at mesosphere.marathon.state.GroupManager$$anonfun$upgrade$1$$anonfun$3$$anonfun$apply$12.apply(GroupManager.scala:159) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.049 36s3 	at mesosphere.marathon.state.GroupManager$$anonfun$upgrade$1$$anonfun$3$$anonfun$apply$12.apply(GroupManager.scala:157) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.049 36s3 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.049 36s3 	at scala.util.Try$.apply(Try.scala:192) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.049 36s3 	at scala.util.Success.map(Try.scala:237) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.049 36s3 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.049 36s3 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.050 36s3 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.050 36s3 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.050 36s3 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.050 36s3 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.050 36s3 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.050 36s3 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.051 36s3 [2016-06-06 19:58:22,048] WARN mapping exception to status code (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$3117cf6:qtp83210381-70144)
2016-06-06T19:58:22.051 36s3 mesosphere.marathon.ValidationFailedException: Validation failed
2016-06-06T19:58:22.051 36s3 	at mesosphere.marathon.api.v2.Validation$.validateOrThrow(Validation.scala:18) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.051 36s3 	at mesosphere.marathon.state.GroupManager$$anonfun$upgrade$1$$anonfun$3$$anonfun$apply$12.apply(GroupManager.scala:159) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.051 36s3 	at mesosphere.marathon.state.GroupManager$$anonfun$upgrade$1$$anonfun$3$$anonfun$apply$12.apply(GroupManager.scala:157) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.052 36s3 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.052 36s3 	at scala.util.Try$.apply(Try.scala:192) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.052 36s3 	at scala.util.Success.map(Try.scala:237) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.052 36s3 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.052 36s3 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.052 36s3 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.053 36s3 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.053 36s3 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.053 36s3 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.053 36s3 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[marathon-assembly-1.1.1.jar:1.1.1]
2016-06-06T19:58:22.053 36s3 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[marathon-assembly-1.1.1.jar:1.1.1]
```

**Comment by bobrik** [comment]
Oh cool, I have 2 instances of `/abc/kafka/foo` in Marathon store. I dropped the failing check and now when I delete `/abc/kafka/foo` Marathon just restarts the app.

**Comment by bobrik** [comment]
Okay, looks like I was able to resolve it with my patched Marathon. The issue is still there: Marathon locks itself on upgrade and there's no sane way to fix it.

**Comment by bobrik** [comment]
```diff
ivan@36com10:~/marathon$ git diff
diff --git a/src/main/scala/mesosphere/marathon/state/GroupManager.scala b/src/main/scala/mesosphere/marathon/state/GroupManager.scala
index 059eaa3..5a22eb063 100644
--- a/src/main/scala/mesosphere/marathon/state/GroupManager.scala
+++ b/src/main/scala/mesosphere/marathon/state/GroupManager.scala
@@ -156,7 +156,7 @@ class GroupManager @Inject() (
       from <- rootGroup()
       (toUnversioned, resolve) <- resolveStoreUrls(assignDynamicServicePorts(from, change(from)))
       to = GroupVersioningUtil.updateVersionInfoForChangedApps(version, from, toUnversioned)
-      _ = validateOrThrow(to)(Group.validRootGroup(config.maxApps.get))
+      // _ = validateOrThrow(to)(Group.validRootGroup(config.maxApps.get))
       plan = DeploymentPlan(from, to, resolve, version, toKill)
       _ = validateOrThrow(plan)(DeploymentPlan.deploymentPlanValidator(config))
       _ = log.info(s"Computed new deployment plan:\n$plan")
diff --git a/src/test/scala/mesosphere/marathon/state/GroupManagerTest.scala b/src/test/scala/mesosphere/marathon/state/GroupManagerTest.scala
index eb4ff0a..03a9484 100644
--- a/src/test/scala/mesosphere/marathon/state/GroupManagerTest.scala
+++ b/src/test/scala/mesosphere/marathon/state/GroupManagerTest.scala
@@ -191,18 +191,6 @@ class GroupManagerTest extends MarathonActorSupport with MockitoSugar with Match
   }

   test("Don't store invalid groups") {
-    val f = new Fixture
-
-    val group = Group(PathId.empty, Set(AppDefinition("/app1".toPath)), Set(Group("/group1".toPath)))
-
-    when(f.groupRepo.zkRootName).thenReturn(GroupRepository.zkRootName)
-    when(f.groupRepo.group(GroupRepository.zkRootName)).thenReturn(Future.successful(None))
-
-    intercept[ValidationFailedException] {
-      Await.result(f.manager.update(group.id, _ => group), 3.seconds)
-    }.printStackTrace()
-
-    verify(f.groupRepo, times(0)).store(any(), any())
   }

   test("Store new apps with correct version infos in groupRepo and appRepo") {
```

**Comment by cmluciano** [comment]
We are seeing the same error under the same upgrade conditions. New and existing apps are stuck in this locked state.

```
["Identifier is not child of /statsd-monitor/master-monitor. Hint: use relative paths."]},{"path":"/groups(23)/groups(0)/apps(3)/id","errors":["Identifier is not child of /statsd-monitor/master-monitor. Hint: use relative paths."]}]}
```

**Comment by cmluciano** [comment]
Rolling back to the 0.15.3 masters works for a bit, but they everything gets redeployed after 5 minutes or so

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2600. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
