### ISSUE TITLE
Invalid constraint value * allowed

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [mesosphere/marathon#3970]
Users have noticed that when using the regex constraint `*`  can be accepted in the UI or a REST post, but can cause unexpected results in the matcher:

```
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: [2016-06-08 22:07:14,179] ERROR Dangling meta character '*' near index 0
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: *
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: ^ (akka.actor.OneForOneStrategy:marathon-akka.actor.default-dispatcher-69198)
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: *
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: ^
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at java.util.regex.Pattern.error(Pattern.java:1955) ~[na:1.8.0_51]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at java.util.regex.Pattern.sequence(Pattern.java:2123) ~[na:1.8.0_51]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at java.util.regex.Pattern.expr(Pattern.java:1996) ~[na:1.8.0_51]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at java.util.regex.Pattern.compile(Pattern.java:1696) ~[na:1.8.0_51]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[na:1.8.0_51]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at java.util.regex.Pattern.compile(Pattern.java:1028) ~[na:1.8.0_51]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at java.util.regex.Pattern.matches(Pattern.java:1133) ~[na:1.8.0_51]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at java.lang.String.matches(String.java:2109) ~[na:1.8.0_51]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at mesosphere.mesos.Constraints$ConstraintsChecker.checkAttribute(Constraints.scala:104) ~[marathon.jar:0.15.3]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at mesosphere.mesos.Constraints$ConstraintsChecker.isMatch(Constraints.scala:38) ~[marathon.jar:0.15.3]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at mesosphere.mesos.Constraints$.meetsConstraint(Constraints.scala:129) ~[marathon.jar:0.15.3]
Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: at mesosphere.mesos.ResourceMatcher$$anonfun$4.apply(ResourceMatcher.scala:82) ~[marathon.jar:0.15.3]

...

Jun 08 22:07:14 ip-10-8-0-54.ec2.internal java[5262]: [2016-06-08 22:07:14,180] INFO Deregister as matcher. (mesosphere.marathon.core.launchqueue.impl.AppTaskLauncherActor:marathon-akka.actor.default-dispatcher-69198)
```

Using a value of `.*` provides the desired outcome in a deterministic fashion.

**Comment by jdef** [comment]
marathon should validate the regexp at app create/update time and reject apps with constraints that use invalid regex

**Comment by jdef** [comment]
re-opening because the full fix (validation in marathon) has not yet been merged
