### ISSUE TITLE
Can not retrieve the list of running deployments in time in v1.2.0-RC1

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#4015]
```
2016-06-22T09:17:42.665 myhost [2016-06-22 09:17:42,664] WARN mapping exception to status code (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$9f9c72fc:qtp1296670053-1189)
2016-06-22T09:17:42.665 myhost java.util.concurrent.TimeoutException: Can not retrieve the list of running deployments in time
2016-06-22T09:17:42.665 myhost 	at mesosphere.marathon.MarathonSchedulerService$$anonfun$listRunningDeployments$1.applyOrElse(MarathonSchedulerService.scala:125)
2016-06-22T09:17:42.665 myhost 	at mesosphere.marathon.MarathonSchedulerService$$anonfun$listRunningDeployments$1.applyOrElse(MarathonSchedulerService.scala:123)
2016-06-22T09:17:42.665 myhost 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
2016-06-22T09:17:42.666 myhost 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
2016-06-22T09:17:42.666 myhost 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
2016-06-22T09:17:42.666 myhost 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
2016-06-22T09:17:42.666 myhost 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
2016-06-22T09:17:42.666 myhost 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
2016-06-22T09:17:42.666 myhost 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
2016-06-22T09:17:42.667 myhost 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I also can't deploy anything. This happened ofter 1.1.1 -> 1.2.0-RC1 migration.

**Comment by kensipe** [comment]
hey bobrik,

Thanks for the feedback.  Which mesos version are you using?
Mesos 1.0 is required.  We didn't announce this release as Mesos 1.0 isn't available however we testing against the RC release for 1.0.

ken

**Comment by bobrik** [comment]
I'm on 0.27.2. I can't test mesos 1.0.0 locally, btw:

```
$ docker run --rm -it --net host mesosphere/mesos-slave:1.0.0-1.0.52.rc1.ubuntu1404
mesos-slave: error while loading shared libraries: libevent_openssl-2.0.so.5: cannot open shared object file: No such file or directory
```

**Comment by aquamatthias** [comment]
I can reproduce the same behavior when using mesos < 1.0-RC1

**Comment by aquamatthias** [comment]
@jmlvanre can you help with the Mesos docker image?

**Comment by karya0** [comment]
@bobrik @aquamatthias: I just pushed updated docker images that fix this dependency issue. Please use the `1.0.0-rc1` (`1.0.0-1.0.59.rc1.ubuntu1404`) docker tag to get the updated images

**Comment by karya0** [comment]
@aquamatthias: How are we invoking the master/slave docker images. As in what parameters are we supplying? Do we supply any `--ip` flag to the master? Also, we need to supply `--master` flag to the slave so wondering how are we doing this?

**Comment by bobrik** [comment]
Oh boy.

```
$ docker run --rm -it --net host --entrypoint mesos-slave mesosphere/marathon:v1.2.0-RC1 --version
mesos 0.28.2
```

**Comment by bobrik** [comment]
I think marathon should exit right after this exception:

```
marathon_1   | java.lang.UnsatisfiedLinkError: Mesos JAR version 1.0.0-rc1 is not backwards compatible with Mesos native library version 0.28.2
```

**Comment by aquamatthias** [comment]
@bobrik Ye I agree, this is the original problem...

**Comment by karya0** [comment]
@aquamatthias: It looks like the new docker images fix the dependency information. Can you please confirm that this is the case? Please ping me if you need any help on Mesos side of things!

**Comment by bobrik** [comment]
1.2.0-rc2:

```
marathon_1   | java.lang.UnsatisfiedLinkError: /usr/lib/libmesos-1.0.0.so: libevent_openssl-2.0.so.5: cannot open shared object file: No such file or directory
```

**Comment by aquamatthias** [comment]
@karya0 The native Mesos package does not resolve dependencies correctly. Can you acknowledge? Is there already a Jira for this or should I create one?

**Comment by karya0** [comment]
The Marathon HEAD should be using the updated Mesos package `mesos=1.0.0-1.0.59.rc1.debian81` (which fixes libevent dependency)  instead of `mesos=1.0.0-1.0.52.rc1.debian81`.
