### ISSUE TITLE
TaskLostIntegrationTest is flaky

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4064]
```
[14:35:01][Step 3/3] TaskLostIntegrationTest:
[14:35:01][Step 3/3]  *** ABORTED *** (5 seconds, 573 milliseconds)
[14:35:01][Step 3/3]   java.lang.IllegalStateException: Process slave1 did not come up within time bounds (30 seconds). Give up. [mesos, slave, --no-systemd_enable_support, --master=zk://127.0.0.1:49872/mesos, --work_dir=/tmp/marathon-itest-mesos/slave1, --port=50051]
[14:35:01][Step 3/3]   at mesosphere.marathon.integration.setup.ProcessKeeper$.startProcess(ProcessKeeper.scala:224)
[14:35:01][Step 3/3]   at mesosphere.marathon.integration.setup.ProcessKeeper$.startMesos(ProcessKeeper.scala:121)
[14:35:01][Step 3/3]   at mesosphere.marathon.integration.setup.WithMesosCluster$class.startSlave(WithMesosCluster.scala:43)
[14:35:01][Step 3/3]   at mesosphere.marathon.integration.TaskLostIntegrationTest.startSlave(TaskLostIntegrationTest.scala:9)
[14:35:01][Step 3/3]   at mesosphere.marathon.integration.setup.WithMesosCluster$class.startMesos(WithMesosCluster.scala:51)
[14:35:01][Step 3/3]   at mesosphere.marathon.integration.TaskLostIntegrationTest.startMesos(TaskLostIntegrationTest.scala:9)
[14:35:01][Step 3/3]   at mesosphere.marathon.integration.setup.SingleMarathonIntegrationTest$class.beforeAll(SingleMarathonIntegrationTest.scala:128)
[14:35:01][Step 3/3]   at mesosphere.marathon.integration.TaskLostIntegrationTest.beforeAll(TaskLostIntegrationTest.scala:9)
[14:35:01][Step 3/3]   at org.scalatest.BeforeAndAfterAllConfigMap$class.run(BeforeAndAfterAllConfigMap.scala:244)
[14:35:01][Step 3/3]   at mesosphere.marathon.integration.TaskLostIntegrationTest.org$scalatest$BeforeAndAfter$$super$run(TaskLostIntegrationTest.scala:9)
[14:35:01][Step 3/3]   at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
[14:35:01][Step 3/3]   at mesosphere.marathon.integration.TaskLostIntegrationTest.run(TaskLostIntegrationTest.scala:9)
[14:35:01][Step 3/3]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
[14:35:01][Step 3/3]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
[14:35:01][Step 3/3]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[14:35:01][Step 3/3]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[14:35:01][Step 3/3]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:35:01][Step 3/3]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:35:01][Step 3/3]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:35:01][Step 3/3]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by gkleiman** [comment]
```
[07:51:06][Step 3/3] TaskLostIntegrationTest:
[07:51:06][Step 3/3] 
[07:51:06][Step 3/3] - A task lost with mesos master failover will expunge the task after gc timeout *** FAILED *** (30 seconds, 71 milliseconds)
[07:51:06][Step 3/3]   java.lang.AssertionError: Waiting for event deployment_success to arrive took longer than 30 seconds. Give up.
[07:51:06][Step 3/3]   at mesosphere.marathon.integration.setup.WaitTestSupport$.next$1(WaitTestSupport.scala:30)
[07:51:06][Step 3/3]   at mesosphere.marathon.integration.setup.WaitTestSupport$.waitFor(WaitTestSupport.scala:36)
[07:51:06][Step 3/3]   at mesosphere.marathon.integration.setup.MarathonCallbackTestSupport$class.waitForEventMatching(MarathonCallbackTestSupport.scala:48)
[07:51:06][Step 3/3]   at mesosphere.marathon.integration.TaskLostIntegrationTest.waitForEventMatching(TaskLostIntegrationTest.scala:9)
[07:51:06][Step 3/3]   at mesosphere.marathon.integration.setup.MarathonCallbackTestSupport$class.waitForEventWith(MarathonCallbackTestSupport.scala:52)
[07:51:06][Step 3/3]   at mesosphere.marathon.integration.TaskLostIntegrationTest.waitForEventWith(TaskLostIntegrationTest.scala:9)
[07:51:06][Step 3/3]   at mesosphere.marathon.integration.setup.MarathonCallbackTestSupport$class.waitForEvent(MarathonCallbackTestSupport.scala:32)
```

**Comment by unterstein** [comment]
Closing this, since it seams it is not flaky anymore. Please re-open if it is flaky again.
