### ISSUE TITLE
Unit test failed: MigrationTo1_2Test

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4093]
This could indicate a problem with the migration:

```
 MigrationTo1_2Test:
[10:06:32][Step 3/3] 
[10:06:32][Step 3/3] - should remove deployment version nodes, but keep deployment nodes *** FAILED *** (27 milliseconds)
[10:06:32][Step 3/3]   ArrayBuffer("foo:bar", "deployment:42c6b840-5a4b-4110-a7d9-d4835f7499b9:2016-06-13T18:47:15.862Z", "deployment:fcabfa75-7756-4bc8-94b3-c9d5b2abd38c") did not contain the same elements as List("deployment:fcabfa75-7756-4bc8-94b3-c9d5b2abd38c", "foo:bar") (MigrationTo1_2Test.scala:43)
```

**Comment by gkleiman** [comment]
I ran this test in a loop for over an hour and it always succeeded :(

**Comment by aquamatthias** [comment]
Saw that problem again: https://travis-ci.org/mesosphere/marathon/builds/145976834
```
*** 1 TEST FAILED ***
MigrationTo1_2Test:
- should remove deployment version nodes, but keep deployment nodes *** FAILED *** (26 milliseconds)
  ArrayBuffer("foo:bar", "deployment:265fe17c-2979-4ab6-b906-9c2b34f9c429:2016-06-23T22:16:03.880Z", "deployment:42c6b840-5a4b-4110-a7d9-d4835f7499b9:2016-06-13T18:47:15.862Z", "deployment:fcabfa75-7756-4bc8-94b3-c9d5b2abd38c") did not contain the same elements as List("deployment:fcabfa75-7756-4bc8-94b3-c9d5b2abd38c", "foo:bar") (MigrationTo1_2Test.scala:43)
  org.scalatest.exceptions.TestFailedException:
  at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
  at org.scalatest.words.ResultOfContainWord.theSameElementsAs(ResultOfContainWord.scala:115)
  at mesosphere.marathon.state.MigrationTo1_2Test$$anonfun$1.apply$mcV$sp(MigrationTo1_2Test.scala:43)
  at mesosphere.marathon.state.MigrationTo1_2Test$$anonfun$1.apply(MigrationTo1_2Test.scala:29)
  at mesosphere.marathon.state.MigrationTo1_2Test$$anonfun$1.apply(MigrationTo1_2Test.scala:29)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
  at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
  at mesosphere.marathon.state.MigrationTo1_2Test.withFixture(MigrationTo1_2Test.scala:11)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
  at mesosphere.marathon.state.MigrationTo1_2Test.org$scalatest$BeforeAndAfter$$super$runTest(MigrationTo1_2Test.scala:11)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
  at mesosphere.marathon.state.MigrationTo1_2Test.runTest(MigrationTo1_2Test.scala:11)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
  at mesosphere.marathon.state.MigrationTo1_2Test.runTests(MigrationTo1_2Test.scala:11)
  at org.scalatest.Suite$class.run(Suite.scala:1424)
  at mesosphere.marathon.state.MigrationTo1_2Test.org$scalatest$FunSuiteLike$$super$run(MigrationTo1_2Test.scala:11)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
  at mesosphere.marathon.state.MigrationTo1_2Test.org$scalatest$BeforeAndAfter$$super$run(MigrationTo1_2Test.scala:11)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
  at mesosphere.marathon.state.MigrationTo1_2Test.run(MigrationTo1_2Test.scala:11)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExe
```

**Comment by aquamatthias** [comment]
Did not see this bug again. Close for now.
