### ISSUE TITLE
GracefulTaskKillIntegrationTest is flaky

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4109]
```
[12:49:48][Step 3/3] GracefulTaskKillIntegrationTest:
[12:49:48][Step 3/3]  *** ABORTED *** (43 seconds, 227 milliseconds)
[12:49:48][Step 3/3]   java.lang.AssertionError: Waiting for clean slate in Mesos took longer than 30 seconds. Give up.
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.setup.WaitTestSupport$.next$1(WaitTestSupport.scala:30)
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.setup.WaitTestSupport$.waitFor(WaitTestSupport.scala:36)
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.setup.WaitTestSupport$.waitUntil(WaitTestSupport.scala:22)
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.setup.SingleMarathonIntegrationTest$class.waitForCleanSlateInMesos(SingleMarathonIntegrationTest.scala:315)
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.GracefulTaskKillIntegrationTest.waitForCleanSlateInMesos(GracefulTaskKillIntegrationTest.scala:10)
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.setup.SingleMarathonIntegrationTest$class.cleanUp(SingleMarathonIntegrationTest.scala:299)
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.GracefulTaskKillIntegrationTest.cleanUp(GracefulTaskKillIntegrationTest.scala:10)
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.GracefulTaskKillIntegrationTest$$anonfun$1.apply$mcV$sp(GracefulTaskKillIntegrationTest.scala:18)
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.GracefulTaskKillIntegrationTest$$anonfun$1.apply(GracefulTaskKillIntegrationTest.scala:18)
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.GracefulTaskKillIntegrationTest$$anonfun$1.apply(GracefulTaskKillIntegrationTest.scala:18)
[12:49:48][Step 3/3]   at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:195)
[12:49:48][Step 3/3]   at mesosphere.marathon.integration.GracefulTaskKillIntegrationTest.runTest(GracefulTaskKillIntegrationTest.scala:10)
[12:49:48][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
[12:49:48][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
[12:49:48][Step 3/3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[12:49:48][Step 3/3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[12:49:48][Step 3/3]   at scala.collection.immutable.List.foreach(List.scala:381)
[12:49:48][Step 3/3]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[12:49:48][Step 3/3]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[12:49:48][Step 3/3]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[12:49:48][Step 3/3]   at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
[12:49:48][Step 3/3]   at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
[12:49:48][Step 3/3]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[12:49:48][Step 3/3]   at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
```

**Comment by gkleiman** [comment]
cc/ @unterstein

**Comment by unterstein** [comment]
:-/

**Comment by unterstein** [comment]
rebuild integration tests several times for https://github.com/mesosphere/marathon/pull/4122, not occurred there and in current other development. Closed this until occurs again *fingers crossed*
