### ISSUE TITLE
ElectionServiceBaseTest has a flaky test

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4134]
```
ElectionServiceBaseTest:
- offerLeadership while abdicating *** FAILED *** (2 seconds, 966 milliseconds)
  Abdicating(Mock for ElectionCandidate, hashCode: 60248519,true,false) did not equal Abdicating(Mock for ElectionCandidate, hashCode: 60248519,false,false) (ElectionServiceBaseTest.scala:142)
  org.scalatest.exceptions.TestFailedException:
  at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6254)
  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6300)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest$$anonfun$5$$anonfun$apply$mcV$sp$10.apply$mcV$sp(ElectionServiceBaseTest.scala:142)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest$$anonfun$5$$anonfun$apply$mcV$sp$10.apply(ElectionServiceBaseTest.scala:142)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest$$anonfun$5$$anonfun$apply$mcV$sp$10.apply(ElectionServiceBaseTest.scala:142)
  at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:266)
  at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:277)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest.awaitAssert(ElectionServiceBaseTest.scala:20)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest$$anonfun$5.apply$mcV$sp(ElectionServiceBaseTest.scala:142)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest$$anonfun$5.apply(ElectionServiceBaseTest.scala:130)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest$$anonfun$5.apply(ElectionServiceBaseTest.scala:130)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
  at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest.withFixture(ElectionServiceBaseTest.scala:20)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest.org$scalatest$BeforeAndAfter$$super$runTest(ElectionServiceBaseTest.scala:20)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest.runTest(ElectionServiceBaseTest.scala:20)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest.runTests(ElectionServiceBaseTest.scala:20)
  at org.scalatest.Suite$class.run(Suite.scala:1424)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest.org$scalatest$BeforeAndAfterAll$$super$run(ElectionServiceBaseTest.scala:20)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest.org$scalatest$FunSuiteLike$$super$run(ElectionServiceBaseTest.scala:20)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest.org$scalatest$BeforeAndAfter$$super$run(ElectionServiceBaseTest.scala:20)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
  at mesosphere.marathon.core.election.impl.ElectionServiceBaseTest.run(ElectionServiceBaseTest.scala:20)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by zen-dog** [comment]
I've run the test in question and the test suite 1k time locally with 0 fails. Teamcity also doesn't seem to have troubles with it so I just gonna close the ticket.
