### ISSUE TITLE
MarathonSchedulerActorTest has a flaky test

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4135]
```
MarathonSchedulerActorTest:
- Kill tasks with scaling *** FAILED *** (5 seconds, 27 milliseconds)
  org.mockito.exceptions.verification.WantedButNotInvoked: Wanted but not invoked:
taskFailureRepository.store(
    /test-app,
    TaskFailure(/test-app,value: "test-app.e9bfaf7d-5255-11e6-98a4-4a78e4b13508"
,TASK_FAILED,,,1970-01-01T00:00:00.000Z,2016-07-25T10:52:42.874Z,Some(value: ""
))
);
-> at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$5$$anonfun$apply$mcV$sp$6.apply(MarathonSchedulerActorTest.scala:173)
Actually, there were zero interactions with this mock.
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$5$$anonfun$apply$mcV$sp$6.apply(MarathonSchedulerActorTest.scala:173)
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$5$$anonfun$apply$mcV$sp$6.apply(MarathonSchedulerActorTest.scala:173)
  at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:266)
  at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:277)
  at mesosphere.marathon.MarathonSchedulerActorTest.awaitAssert(MarathonSchedulerActorTest.scala:39)
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$5.apply$mcV$sp(MarathonSchedulerActorTest.scala:173)
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$5.apply(MarathonSchedulerActorTest.scala:131)
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$5.apply(MarathonSchedulerActorTest.scala:131)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
  at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
  at mesosphere.marathon.MarathonSchedulerActorTest.withFixture(MarathonSchedulerActorTest.scala:39)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$runTest(MarathonSchedulerActorTest.scala:39)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
  at mesosphere.marathon.MarathonSchedulerActorTest.runTest(MarathonSchedulerActorTest.scala:39)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
  at mesosphere.marathon.MarathonSchedulerActorTest.runTests(MarathonSchedulerActorTest.scala:39)
  at org.scalatest.Suite$class.run(Suite.scala:1424)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfterAll$$super$run(MarathonSchedulerActorTest.scala:39)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$FunSuiteLike$$super$run(MarathonSchedulerActorTest.scala:39)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$run(MarathonSchedulerActorTest.scala:39)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
  at mesosphere.marathon.MarathonSchedulerActorTest.run(MarathonSchedulerActorTest.scala:39)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by aquamatthias** [comment]
TestCase "Kill tasks with scaling" is not marked as Unstable and runs green.
