### ISSUE TITLE
[RC6] Migration for 1.2 fails - zk node can not be read

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4158]
```
 [2016-07-29 14:27:00,560] ERROR Failed to take over leadership (mesosphere.marathon.core.election.impl.CuratorElectionService:ForkJoinPool-2-worker-43-EventThread)
 mesosphere.marathon.MigrationFailedException: while migrating storage to 1.2
         at mesosphere.marathon.state.Migration$$anonfun$migrations$5$$anonfun$apply$4.applyOrElse(Migration.scala:64)
         at mesosphere.marathon.state.Migration$$anonfun$migrations$5$$anonfun$apply$4.applyOrElse(Migration.scala:63)
         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
         at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
         at scala.util.Try$.apply(Try.scala:192)
         at scala.util.Failure.recover(Try.scala:216)
         at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
         at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
         at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
 Caused by: mesosphere.marathon.StoreCommandFailedException: Could not fetch MarathonTaskState with key: tools_reviewbot:tools_reviewbot.f55b1484-81c7-11e5-8b11-56b91e7a505b
         at mesosphere.marathon.state.MarathonStore$$anonfun$mesosphere$marathon$state$MarathonStore$$exceptionTransform$1.applyOrElse(MarathonStore.scala:84)
         at mesosphere.marathon.state.MarathonStore$$anonfun$mesosphere$marathon$state$MarathonStore$$exceptionTransform$1.applyOrElse(MarathonStore.scala:83)
         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
         at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
         at scala.util.Try$.apply(Try.scala:192)
         at scala.util.Failure.recover(Try.scala:216)
         at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
         at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
         at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
         ... 2 common frames omitted
 Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
         at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:94)
         at com.google.protobuf.CodedInputStream.checkLastTagWas(CodedInputStream.java:174)
         at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:139)
         at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168)
         at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)
         at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
         at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
         at mesosphere.marathon.Protos$MarathonTask.parseFrom(Protos.java:16197)
         at mesosphere.marathon.state.MarathonTaskState.mergeFromProto(MarathonTaskState.scala:15)
         at mesosphere.marathon.state.MarathonTaskState.mergeFromProto(MarathonTaskState.scala:9)
         at mesosphere.marathon.state.MarathonStore.mesosphere$marathon$state$MarathonStore$$stateFromBytes(MarathonStore.scala:88)
         at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1$$anonfun$apply$2.apply(MarathonStore.scala:36)
         at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1$$anonfun$apply$2.apply(MarathonStore.scala:34)
         at scala.Option.map(Option.scala:146)
         at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1.apply(MarathonStore.scala:34)
         at mesosphere.marathon.state.MarathonStore$$anonfun$fetch$1.apply(MarathonStore.scala:34)
         at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
         at scala.util.Try$.apply(Try.scala:192)
```

**Comment by unterstein** [comment]
Tested this and it seems that this failure occurred because of a leadership election problem (the library for leadership election was changed). I will update the upgrading instructions.
