### ISSUE TITLE
Error during marathon 1.2 build with sbt or docker.

### ISSUE THREAD

**Issue by alfredcs** [mesosphere/marathon#4223]
Using sbt and docker build to build Marathon 1.2 jar and container image but ran into error during test with following errors. Wondering if anyone else had similar issue and if so how to resolve it? Thx!

===== with sbt ========

........
Run completed in 18 seconds, 587 milliseconds.
Total number of tests run: 1647
Suites: completed 201, aborted 0
Tests: succeeded 1643, failed 4, canceled 0, ignored 20, pending 0
**\* 4 TESTS FAILED ***
ContinueOnErrorStepTest:
- A successful step should not produce logging output **\* FAILED **\* (353 milliseconds)
  java.lang.ClassCastException: org.slf4j.helpers.SubstituteLoggerFactory cannot be cast to ch.qos.logback.core.Context
  at mesosphere.marathon.test.CaptureLogEvents$CapturingAppender.appendToRootLogger(CaptureLogEvents.scala:24)
  at mesosphere.marathon.test.CaptureLogEvents$.forBlock(CaptureLogEvents.scala:12)
  at mesosphere.marathon.core.task.update.impl.steps.ContinueOnErrorStepTest$$anonfun$4.apply(ContinueOnErrorStepTest.scala:33)
  at mesosphere.marathon.core.task.update.impl.steps.ContinueOnErrorStepTest$$anonfun$4.apply(ContinueOnErrorStepTest.scala:27)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at org.scalatest.FunSuite.run(FunSuite.scala:1560)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  ContinueOnErrorStepTest:
- A failing step should log the error but proceed **\* FAILED **\* (30 milliseconds)
  java.lang.ClassCastException: org.slf4j.helpers.SubstituteLoggerFactory cannot be cast to ch.qos.logback.core.Context
  at mesosphere.marathon.test.CaptureLogEvents$CapturingAppender.appendToRootLogger(CaptureLogEvents.scala:24)
  at mesosphere.marathon.test.CaptureLogEvents$.forBlock(CaptureLogEvents.scala:12)
  at mesosphere.marathon.core.task.update.impl.steps.ContinueOnErrorStepTest$$anonfun$5.apply(ContinueOnErrorStepTest.scala:51)
  at mesosphere.marathon.core.task.update.impl.steps.ContinueOnErrorStepTest$$anonfun$5.apply(ContinueOnErrorStepTest.scala:44)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at org.scalatest.FunSuite.run(FunSuite.scala:1560)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  DVDIProviderRootGroupValidationTest:
- two volumes with different names should not result in an error **\* FAILED **\* (2 seconds, 288 milliseconds)
  {
    "message" : "Object is not valid",
    "details" : [ {
      "path" : "/groups(0)/apps(0)/container/volumes(0)",
      "errors" : [ "Feature external_volumes is not enabled. Enable with --enable_features external_volumes)" ]
    }, {
      "path" : "/groups(0)/apps(1)/container/volumes(0)",
      "errors" : [ "Feature external_volumes is not enabled. Enable with --enable_features external_volumes)" ]
    } ]
  } true was not false (DVDIProviderRootGroupValidationTest.scala:129)
  org.scalatest.exceptions.TestFailedException:
  at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$Fixture$$anonfun$checkResult$3.apply(DVDIProviderRootGroupValidationTest.scala:129)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$Fixture$$anonfun$checkResult$3.apply(DVDIProviderRootGroupValidationTest.scala:129)
  at org.scalatest.Assertions$class.withClue(Assertions.scala:1221)
  at org.scalatest.FunSuite.withClue(FunSuite.scala:1560)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$Fixture.checkResult(DVDIProviderRootGroupValidationTest.scala:129)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$$anonfun$1.apply$mcV$sp(DVDIProviderRootGroupValidationTest.scala:34)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$$anonfun$1.apply(DVDIProviderRootGroupValidationTest.scala:16)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$$anonfun$1.apply(DVDIProviderRootGroupValidationTest.scala:16)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at org.scalatest.FunSuite.run(FunSuite.scala:1560)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  AppsResourceTest:
- Create a new app (that uses secrets) successfully **\* FAILED **\* (162 milliseconds)
  422 was not equal to 201 (AppsResourceTest.scala:471)
  org.scalatest.exceptions.TestFailedException:
  at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
  at mesosphere.marathon.api.v2.AppsResourceTest$$anonfun$11.apply$mcV$sp(AppsResourceTest.scala:471)
  at mesosphere.marathon.api.v2.AppsResourceTest$$anonfun$11.apply(AppsResourceTest.scala:456)
  at mesosphere.marathon.api.v2.AppsResourceTest$$anonfun$11.apply(AppsResourceTest.scala:456)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at mesosphere.marathon.api.v2.AppsResourceTest.withFixture(AppsResourceTest.scala:32)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at mesosphere.marathon.api.v2.AppsResourceTest.org$scalatest$BeforeAndAfter$$super$runTest(AppsResourceTest.scala:32)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.marathon.api.v2.AppsResourceTest.runTest(AppsResourceTest.scala:32)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at mesosphere.marathon.api.v2.AppsResourceTest.runTests(AppsResourceTest.scala:32)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at mesosphere.marathon.api.v2.AppsResourceTest.org$scalatest$FunSuiteLike$$super$run(AppsResourceTest.scala:32)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at mesosphere.marathon.api.v2.AppsResourceTest.org$scalatest$BeforeAndAfter$$super$run(AppsResourceTest.scala:32)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.marathon.api.v2.AppsResourceTest.org$scalatest$BeforeAndAfterAll$$super$run(AppsResourceTest.scala:32)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.marathon.api.v2.AppsResourceTest.run(AppsResourceTest.scala:32)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  [info] Run completed in 18 seconds, 587 milliseconds.
  [info] Total number of tests run: 1647
  [info] Suites: completed 201, aborted 0
  [info] Tests: succeeded 1643, failed 4, canceled 0, ignored 20, pending 0
  [info] **\* 4 TESTS FAILED ***
  [error] Failed tests:
  [error]     mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest
  [error]     mesosphere.marathon.api.v2.AppsResourceTest
  [error]     mesosphere.marathon.core.task.update.impl.steps.ContinueOnErrorStepTest
  [error](marathon/test:test) sbt.TestsFailedException: Tests unsuccessful
  [error] Total time: 249 s, completed Aug 15, 2016 4:50:02 PM

===== with docker build ========

.......
Run completed in 18 seconds, 242 milliseconds.
Total number of tests run: 1647
Suites: completed 201, aborted 0
Tests: succeeded 1646, failed 1, canceled 0, ignored 20, pending 0
**\* 1 TEST FAILED ***
DVDIProviderRootGroupValidationTest:
- two volumes with different names should not result in an error **\* FAILED **\* (1 second, 390 milliseconds)
  {
    "message" : "Object is not valid",
    "details" : [ {
      "path" : "/groups(0)/apps(0)/container/volumes(0)",
      "errors" : [ "Feature external_volumes is not enabled. Enable with --enable_features external_volumes)" ]
    }, {
      "path" : "/groups(0)/apps(1)/container/volumes(0)",
      "errors" : [ "Feature external_volumes is not enabled. Enable with --enable_features external_volumes)" ]
    } ]
  } true was not false (DVDIProviderRootGroupValidationTest.scala:129)
  org.scalatest.exceptions.TestFailedException:
  at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$Fixture$$anonfun$checkResult$3.apply(DVDIProviderRootGroupValidationTest.scala:129)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$Fixture$$anonfun$checkResult$3.apply(DVDIProviderRootGroupValidationTest.scala:129)
  at org.scalatest.Assertions$class.withClue(Assertions.scala:1221)
  at org.scalatest.FunSuite.withClue(FunSuite.scala:1560)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$Fixture.checkResult(DVDIProviderRootGroupValidationTest.scala:129)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$$anonfun$1.apply$mcV$sp(DVDIProviderRootGroupValidationTest.scala:34)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$$anonfun$1.apply(DVDIProviderRootGroupValidationTest.scala:16)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$$anonfun$1.apply(DVDIProviderRootGroupValidationTest.scala:16)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at org.scalatest.FunSuite.run(FunSuite.scala:1560)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  [info] Run completed in 18 seconds, 242 milliseconds.
  [info] Total number of tests run: 1647
  [info] Suites: completed 201, aborted 0
  [info] Tests: succeeded 1646, failed 1, canceled 0, ignored 20, pending 0
  [info] **\* 1 TEST FAILED ***
  [error] Failed tests:
  [error]     mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest
  [error](marathon/test:test) sbt.TestsFailedException: Tests unsuccessful
  [error] Total time: 251 s, completed Aug 15, 2016 4:42:36 PM
  The command '/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E56151BF &&     echo "deb http://repos.mesosphere.com/debian jessie-testing main" | tee -a /etc/apt/sources.list.d/mesosphere.list &&     echo "deb http://repos.mesosphere.com/debian jessie main" | tee -a /etc/apt/sources.list.d/mesosphere.list &&     apt-get update &&     apt-get install --no-install-recommends -y --force-yes mesos=1.0.0-2.0.89.debian81 &&     apt-get clean &&     eval $(sed s/sbt.version/SBT_VERSION/ </marathon/project/build.properties) &&     mkdir -p /usr/local/bin &&     wget -P /usr/local/bin/ http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/$SBT_VERSION/sbt-launch.jar &&     cp /marathon/project/sbt /usr/local/bin && chmod +x /usr/local/bin/sbt &&     sbt -Dsbt.log.format=false assembly &&     mv $(find target -name 'marathon-assembly-_.jar' | sort | tail -1) ./ &&     rm -rf target/_ ~/.sbt ~/.ivy2 &&     mv marathon-assembly-_.jar target &&     rm -rf /var/lib/apt/lists/_ /tmp/\* /var/tmp/*' returned a non-zero code: 1

**Comment by unterstein** [comment]
Hi  @alfredcs,

which commit/tag are you trying to build? Which commands do you execute?

Thanks
Johannes

**Comment by jasongilanfarr** [comment]
I believe this is fixed in 1.3.x
