### ISSUE TITLE
Unit tests are broken

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4245]
```
*** 1 SUITE ABORTED ***
*** 2 TESTS FAILED ***
DVDIProviderRootGroupValidationTest:

- two volumes with different names should not result in an error *** FAILED *** (3 seconds, 173 milliseconds)
  {
    "message" : "Object is not valid",
    "details" : [ {
      "path" : "/groups(0)/apps(0)/container/volumes(0)",
      "errors" : [ "Feature external_volumes is not enabled. Enable with --enable_features external_volumes)" ]
    }, {
      "path" : "/groups(0)/apps(1)/container/volumes(0)",
      "errors" : [ "Feature external_volumes is not enabled. Enable with --enable_features external_volumes)" ]
    } ]
  } true was not false (DVDIProviderRootGroupValidationTest.scala:129)
  org.scalatest.exceptions.TestFailedException:
  at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$Fixture$$anonfun$checkResult$3.apply(DVDIProviderRootGroupValidationTest.scala:129)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$Fixture$$anonfun$checkResult$3.apply(DVDIProviderRootGroupValidationTest.scala:129)
  at org.scalatest.Assertions$class.withClue(Assertions.scala:1221)
  at org.scalatest.FunSuite.withClue(FunSuite.scala:1560)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$Fixture.checkResult(DVDIProviderRootGroupValidationTest.scala:129)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$$anonfun$1.apply$mcV$sp(DVDIProviderRootGroupValidationTest.scala:34)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$$anonfun$1.apply(DVDIProviderRootGroupValidationTest.scala:16)
  at mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest$$anonfun$1.apply(DVDIProviderRootGroupValidationTest.scala:16)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at org.scalatest.FunSuite.run(FunSuite.scala:1560)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
MigrationTo1_4_PersistenceStoreTest:
Migration to PersistenceStore when migrating EventSubscribers should
- migrate an existing value *** FAILED *** (3 seconds, 7 milliseconds)
  A timeout occurred waiting for a future to complete. Queried 145 times, sleeping 15 milliseconds between each query. (MigrationTo1_4_PersistenceStoreTest.scala:85)
  org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
  at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
  at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
  at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
  at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
  at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
  at mesosphere.marathon.storage.migration.MigrationTo1_4_PersistenceStoreTest$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$10.apply(MigrationTo1_4_PersistenceStoreTest.scala:85)
  at mesosphere.marathon.storage.migration.MigrationTo1_4_PersistenceStoreTest$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$10.apply(MigrationTo1_4_PersistenceStoreTest.scala:80)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
  at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
  at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
  at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
  at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:48)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:48)
  at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
  at mesosphere.AkkaUnitTest.runTest(UnitTest.scala:48)
  at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
  at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
  at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
  at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
  at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
  at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:48)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:48)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.AkkaUnitTest.run(UnitTest.scala:48)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
EventSubscribersTest:
 *** ABORTED *** (4 milliseconds)
  java.lang.NoSuchMethodError: mesosphere.marathon.Protos$EventSubscribers.getCallbackUrlsList()Lcom/google/protobuf/ProtocolStringList;
  at mesosphere.marathon.core.event.EventSubscribers.mergeFromProto(EventSubscribers.scala:12)
  at mesosphere.marathon.core.event.impl.callback.EventSubscribersTest$$anonfun$3.apply(EventSubscribersTest.scala:28)
  at mesosphere.marathon.core.event.impl.callback.EventSubscribersTest$$anonfun$3.apply(EventSubscribersTest.scala:25)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at mesosphere.marathon.core.event.impl.callback.EventSubscribersTest.withFixture(EventSubscribersTest.scala:6)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at mesosphere.marathon.core.event.impl.callback.EventSubscribersTest.org$scalatest$BeforeAndAfter$$super$runTest(EventSubscribersTest.scala:6)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.marathon.core.event.impl.callback.EventSubscribersTest.runTest(EventSubscribersTest.scala:6)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at mesosphere.marathon.core.event.impl.callback.EventSubscribersTest.runTests(EventSubscribersTest.scala:6)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at mesosphere.marathon.core.event.impl.callback.EventSubscribersTest.org$scalatest$FunSuiteLike$$super$run(EventSubscribersTest.scala:6)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at mesosphere.marathon.core.event.impl.callback.EventSubscribersTest.org$scalatest$BeforeAndAfter$$super$run(EventSubscribersTest.scala:6)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.marathon.core.event.impl.callback.EventSubscribersTest.run(EventSubscribersTest.scala:6)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[info] Run completed in 23 seconds, 138 milliseconds.
[info] Total number of tests run: 1647
[info] Suites: completed 200, aborted 1
[info] Tests: succeeded 1645, failed 2, canceled 0, ignored 20, pending 0
[info] *** 1 SUITE ABORTED ***
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error]        	mesosphere.marathon.core.externalvolume.impl.providers.DVDIProviderRootGroupValidationTest
[error]        	mesosphere.marathon.storage.migration.MigrationTo1_4_PersistenceStoreTest
[error] Error during tests:
[error]        	mesosphere.marathon.core.event.impl.callback.EventSubscribersTest
[error] (marathon/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 79 s, completed Aug 23, 2016 12:11:16 PM
```

**Comment by unterstein** [comment]
@gkleiman does this break locally or in CI?

locally in 1.3 release branch I get this:

```
Run completed in 55 seconds, 634 milliseconds.
Total number of tests run: 1422
Suites: completed 194, aborted 0
Tests: succeeded 1422, failed 0, canceled 0, ignored 10, pending 0
All tests passed.
[info] Run completed in 55 seconds, 634 milliseconds.
[info] Total number of tests run: 1422
[info] Suites: completed 194, aborted 0
[info] Tests: succeeded 1422, failed 0, canceled 0, ignored 10, pending 0
[info] All tests passed.
```

and on master I am receiving (probably) randomly failing unit tests :(

Cheers
Johannes

**Comment by gkleiman** [comment]
cc/ @jasongilanfarr
