### ISSUE TITLE
unresponsive deployments after Finalization failed, killing JVM.

### ISSUE THREAD

**Issue by ac0v** [mesosphere/marathon#4265]
Hi,

I've an issue with a 3 ZK, 3 Master, 3 Slave mesos system. 

Versions:
- Mesos 0.28.2
- Marathon: 1.1.2

The marathon.log shows:

1821672720 [marathon-akka.actor.default-dispatcher-30] INFO  m.m.event.http.HttpEventActor - POSTing to all endpoints. 
1821672720 [marathon-akka.actor.default-dispatcher-30] INFO  m.marathon.health.HealthCheckActor - Stopped health check actor for app [/example/db] version [2016-08-25T15:37:27.548Z] and hea
lthCheck [HealthCheck(None,TCP,Some(0),None,30 seconds,10 seconds,3 seconds,3,false,None)] 
1821672737 [ZookeeperClient-watcherProcessor-SendThread(10.11.1.205:2181)] INFO  org.apache.zookeeper.ClientCnxn - Socket connection established to 10.11.1.205/10.11.1.205:2181, initiatin
g session 
1821672737 [marathon-akka.actor.default-dispatcher-31] INFO  m.marathon.health.HealthCheckActor - Stopped health check actor for app [/example/feed] version [2016-07-07T11:54:35.300Z] and 
healthCheck [HealthCheck(Some(/status),HTTP,Some(0),None,30 seconds,10 seconds,10 seconds,5,false,None)] 
1821672737 [marathon-akka.actor.default-dispatcher-36] INFO  m.marathon.health.HealthCheckActor - Stopped health check actor for app [/another-test] version [2016-05-18T15:49:17.350Z] and healthCheck
 [HealthCheck(Some(/status),HTTP,Some(0),None,300 seconds,30 seconds,5 seconds,1,false,None)] 
1821672740 [ZookeeperClient-watcherProcessor-SendThread(10.11.1.205:2181)] INFO  org.apache.zookeeper.ClientCnxn - Session establishment complete on server 10.11.1.205/10.11.1.205:2181, s
essionid = 0x153ca16564401de, negotiated timeout = 10000 
1821672996 [shutdownHook1] INFO  mesosphere.marathon.Main$ - Shutting down services 
1821672807 [Thread-2] INFO  m.marathon.core.base.ActorsModule - Shutting down actor system akka://marathon 
1821674152 [qtp2134357721-88755] INFO  m.marathon.api.LeaderProxyFilter$ - Leadership info is consistent again! 
1821674222 [marathon-akka.actor.default-dispatcher-36] ERROR akka.actor.OneForOneStrategy - not currently active (Actor[akka://marathon/user/taskTracker#-1503399591]) 
java.lang.IllegalStateException: not currently active (Actor[akka://marathon/user/taskTracker#-1503399591])
        at mesosphere.marathon.core.leadership.impl.WhenLeaderActor$$anonfun$1.applyOrElse(WhenLeaderActor.scala:38) ~[marathon:1.1.2]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[marathon:1.1.2]
        at mesosphere.marathon.core.leadership.impl.WhenLeaderActor.aroundReceive(WhenLeaderActor.scala:20) ~[marathon:1.1.2]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [marathon:1.1.2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [marathon:1.1.2]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [marathon:1.1.2]
        at akka.dispatch.Mailbox.run(Mailbox.scala:221) [marathon:1.1.2]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [marathon:1.1.2]
1821674244 [marathon-akka.actor.default-dispatcher-36] ERROR akka.actor.OneForOneStrategy - not currently active (Actor[akka://marathon/user/taskTracker#-1503399591]) 

...
1821674638 [marathon-akka.actor.default-dispatcher-36] ERROR akka.actor.OneForOneStrategy - not currently active (Actor[akka://marathon/user/taskTracker#-1503399591]) 
java.lang.IllegalStateException: not currently active (Actor[akka://marathon/user/taskTracker#-1503399591])
        at mesosphere.marathon.core.leadership.impl.WhenLeaderActor$$anonfun$1.applyOrElse(WhenLeaderActor.scala:38) ~[marathon:1.1.2]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[marathon:1.1.2]
        at mesosphere.marathon.core.leadership.impl.WhenLeaderActor.aroundReceive(WhenLeaderActor.scala:20) ~[marathon:1.1.2]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[marathon:1.1.2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [marathon:1.1.2]
1821674641 [qtp2134357721-88757] INFO  m.m.a.JavaUrlConnectionRequestForwarder$ - Proxying request to GET http://master1.example.com:8080/v2/events from master3.example.com:8080 
1821674686 [marathon-akka.actor.default-dispatcher-36] ERROR akka.actor.OneForOneStrategy - not currently active (Actor[akka://marathon/user/taskTracker#-1503399591]) 
java.lang.IllegalStateException: not currently active (Actor[akka://marathon/user/taskTracker#-1503399591])
        at mesosphere.marathon.core.leadership.impl.WhenLeaderActor$$anonfun$1.applyOrElse(WhenLeaderActor.scala:38) ~[marathon:1.1.2]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[marathon:1.1.2]
        at mesosphere.marathon.core.leadership.impl.WhenLeaderActor.aroundReceive(WhenLeaderActor.scala:20) ~[marathon:1.1.2]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[marathon:1.1.2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [marathon:1.1.2]
1821674712 [marathon-akka.actor.default-dispatcher-36] ERROR akka.actor.OneForOneStrategy - not currently active (Actor[akka://marathon/user/taskTracker#-1503399591]) 
1821674712 [marathon-akka.actor.default-dispatcher-36] ERROR akka.actor.OneForOneStrategy - not currently active (Actor[akka://marathon/user/taskTracker#-1503399591]) 
java.lang.IllegalStateException: not currently active (Actor[akka://marathon/user/taskTracker#-1503399591])
        at mesosphere.marathon.core.leadership.impl.WhenLeaderActor$$anonfun$1.applyOrElse(WhenLeaderActor.scala:38) ~[marathon:1.1.2]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[marathon:1.1.2]
        at mesosphere.marathon.core.leadership.impl.WhenLeaderActor.aroundReceive(WhenLeaderActor.scala:20) ~[marathon:1.1.2]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[marathon:1.1.2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [marathon:1.1.2]
1821674890 [marathon-akka.actor.default-dispatcher-36] ERROR akka.actor.OneForOneStrategy - not currently active (Actor[akka://marathon/user/taskTracker#-1503399591]) 
java.lang.IllegalStateException: not currently active (Actor[akka://marathon/user/taskTracker#-1503399591])
        at mesosphere.marathon.core.leadership.impl.WhenLeaderActor$$anonfun$1.applyOrElse(WhenLeaderActor.scala:38) ~[marathon:1.1.2]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[marathon:1.1.2]
        at mesosphere.marathon.core.leadership.impl.WhenLeaderActor.aroundReceive(WhenLeaderActor.scala:20) ~[marathon:1.1.2]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[marathon:1.1.2]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[marathon:1.1.2]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [marathon:1.1.2]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [marathon:1.1.2]

...
1821675003 [marathon-akka.actor.default-dispatcher-36] INFO  m.marathon.health.HealthCheckActor - Stopped health check actor for app [/example/foo] version [2016-08-26T14:02:45.437Z] and 
healthCheck [HealthCheck(Some(/),HTTP,Some(0),None,30 seconds,30 seconds,30 seconds,3,false,None)] 
...
1821675053 [main-EventThread] INFO  org.apache.zookeeper.ClientCnxn - EventThread shut down 
1821676980 [ForkJoinPool-2-worker-1] ERROR mesosphere.marathon.Main$ - Finalization failed, killing JVM. 
1821677022 [shutdownHook1] INFO  m.m.MarathonSchedulerService$$EnhancerByGuice$$121ac490 - Shutdown triggered 
1821677022 [shutdownHook1] INFO  m.m.MarathonSchedulerService$$EnhancerByGuice$$121ac490 - Stopping driver 
1821677022 [shutdownHook1] INFO  m.m.MarathonSchedulerService$$EnhancerByGuice$$121ac490 - Cancelling timer 
1821677022 [shutdownHook1] INFO  m.m.MarathonSchedulerService$$EnhancerByGuice$$121ac490 - Removing the blocking of run() `

**Comment by jeschkies** [comment]
Could you change the log level to debug an try again?

**Comment by ac0v** [comment]
Thx for your fast reply. I've enabled the debug log's and will come back with more details after the issue occurs again (I think during the next few days).

**Comment by kangman** [comment]
@ac0v Hi, was curious if you made any headway on this issue you've reported.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4582. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
