### ISSUE TITLE
[Pods] Exception during ForwardTaskOp

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4493]
I started a pod with 2 containers (both sleep tasks).
I restarted Marathon and got this exception:

```
marathon[ERROR] I0927 11:01:51.432931 88170496 sched.cpp:1473] Sending ACK for status update 1�M��л<ZI�y� of task mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6.sleep1 on agent 9a01f2b3-0086-4386-8042-51ba3f811281-S0 to master@127.0.0.1:5050
marathon [2016-09-27 11:01:51,443] ERROR while processing task status update task_id {
marathon   value: "mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6.sleep2"
marathon }
marathon state: TASK_FINISHED
marathon message: "Command exited with status 0"
marathon slave_id {
marathon   value: "9a01f2b3-0086-4386-8042-51ba3f811281-S0"
marathon }
marathon timestamp: 1.474966899411525E9
marathon executor_id {
marathon   value: "instance-mypod2.fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6"
marathon }
marathon healthy: true
marathon source: SOURCE_EXECUTOR
marathon uuid: "`\226\n\255\f\313K\244\275N\365\362\253+\031\211"
marathon container_status {
marathon   network_infos {
marathon     ip_addresses {
marathon       ip_address: "192.168.178.41"
marathon     }
marathon   }
marathon   executor_pid: 66208
marathon }
marathon  (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$1c750585:ForkJoinPool-2-worker-19)
marathon java.lang.RuntimeException: while asking for ForwardTaskOp(2016-09-27T09:02:01.392Z,instance [mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6],MesosUpdate(Instance(instance [mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6],AgentInfo(wrk.fritz.box,Some(9a01f2b3-0086-4386-8042-51ba3f811281-S0),List()),InstanceState(Running,2016-09-27T09:01:31.249Z,2016-09-27T08:45:52.570Z,Some(true)),Map(task [mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6.sleep1] -> LaunchedEphemeral(task [mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6.sleep1],AgentInfo(wrk.fritz.box,Some(9a01f2b3-0086-4386-8042-51ba3f811281-S0),List()),2016-09-27T08:45:52.570Z,Status(2016-09-27T09:01:31.076Z,Some(2016-09-27T09:01:31.241Z),Some(task_id {
marathon   value: "mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6.sleep1"
marathon }
marathon state: TASK_RUNNING
marathon slave_id {
marathon   value: "9a01f2b3-0086-4386-8042-51ba3f811281-S0"
marathon }
marathon timestamp: 1.4749668912414E9
marathon executor_id {
marathon   value: "instance-mypod2.fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6"
marathon }
marathon healthy: true
marathon source: SOURCE_EXECUTOR
marathon uuid: "\2373\215KW\251O\345\214pp\200w!\203\343"
marathon container_status {
marathon   network_infos {
marathon     ip_addresses {
marathon       ip_address: "192.168.178.41"
marathon     }
marathon   }
marathon   executor_pid: 66208
marathon }
marathon ),Running),List()), task [mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6.sleep2] -> LaunchedEphemeral(task [mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6.sleep2],AgentInfo(wrk.fritz.box,Some(9a01f2b3-0086-4386-8042-51ba3f811281-S0),List()),2016-09-27T08:45:52.570Z,Status(2016-09-27T09:01:31.076Z,Some(2016-09-27T09:01:31.241Z),Some(task_id {
marathon   value: "mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6.sleep2"
marathon }
marathon state: TASK_RUNNING
marathon slave_id {
marathon   value: "9a01f2b3-0086-4386-8042-51ba3f811281-S0"
marathon }
marathon timestamp: 1.474966891241516E9
marathon executor_id {
marathon   value: "instance-mypod2.fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6"
marathon }
marathon healthy: true
marathon source: SOURCE_EXECUTOR
marathon uuid: "\200\365\230vj\231N\376\260\331\360W\2701\212\""
marathon container_status {
marathon   network_infos {
marathon     ip_addresses {
marathon       ip_address: "192.168.178.41"
marathon     }
marathon   }
marathon   executor_pid: 66208
marathon }
marathon ),Running),List()))),Finished,task_id {
marathon   value: "mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6.sleep2"
marathon }
marathon state: TASK_FINISHED
marathon message: "Command exited with status 0"
marathon slave_id {
marathon   value: "9a01f2b3-0086-4386-8042-51ba3f811281-S0"
marathon }
marathon timestamp: 1.474966899411525E9
marathon executor_id {
marathon   value: "instance-mypod2.fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6"
marathon }
marathon healthy: true
marathon source: SOURCE_EXECUTOR
marathon uuid: "`\226\n\255\f\313K\244\275N\365\362\253+\031\211"
marathon container_status {
marathon   network_infos {
marathon     ip_addresses {
marathon       ip_address: "192.168.178.41"
marathon     }
marathon   }
marathon   executor_pid: 66208
marathon }
marathon ,2016-09-27T09:01:51.360Z)) on runSpec [/mypod2] and instance [mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6]
marathon 	at mesosphere.marathon.core.task.tracker.impl.InstanceCreationHandlerAndUpdaterDelegate$$anonfun$taskUpdate$1.applyOrElse(InstanceCreationHandlerAndUpdaterDelegate.scala:53)
marathon 	at mesosphere.marathon.core.task.tracker.impl.InstanceCreationHandlerAndUpdaterDelegate$$anonfun$taskUpdate$1.applyOrElse(InstanceCreationHandlerAndUpdaterDelegate.scala:51)
marathon 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
marathon 	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
marathon 	at scala.util.Try$.apply(Try.scala:192)
marathon 	at scala.util.Failure.recover(Try.scala:216)
marathon 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
marathon 	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
marathon 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
marathon 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
marathon 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
marathon 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
marathon 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
marathon 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
marathon Caused by: java.lang.IllegalStateException: instance [mypod2.instance-fb7c1a2a-8490-11e6-862b-2a2bf4e4eca6] of app [/mypod2] does not exist
marathon 	at mesosphere.marathon.core.task.tracker.impl.InstanceOpProcessorImpl$InstanceUpdateOpResolver$$anonfun$updateExistingInstance$1.apply(InstanceOpProcessorImpl.scala:65)
marathon 	at mesosphere.marathon.core.task.tracker.impl.InstanceOpProcessorImpl$InstanceUpdateOpResolver$$anonfun$updateExistingInstance$1.apply(InstanceOpProcessorImpl.scala:59)
marathon 	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
marathon 	at scala.util.Try$.apply(Try.scala:192)
marathon 	at scala.util.Success.map(Try.scala:237)
marathon 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
marathon 	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
marathon 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
marathon 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
marathon 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
marathon 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
marathon 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
marathon 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
marathon 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
marathon 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
marathon 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
marathon 	... 4 common frames omitted

```

**Comment by aquamatthias** [comment]
Can not reproduce after the #4457 has been applied.
