### ISSUE TITLE
Test flake: mesosphere.marathon.core.election.impl.CuratorElectionServiceTest.The CuratorElectionService when given an unresolvable hostname should shut Marathon down on a NonFatal

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#4559]
https://jenkins.mesosphere.com/service/jenkins/job/marathon-snapshot-packages-pulls/1629/testReport/junit/mesosphere.marathon.core.election.impl/CuratorElectionServiceTest/The_CuratorElectionService_when_given_an_unresolvable_hostname_should_shut_Marathon_down_on_a_NonFatal/

**Comment by jasongilanfarr** [comment]
See https://phabricator.mesosphere.com/D47

**Comment by timcharper** [comment]
Error Message

```
java.util.NoSuchElementException: head of empty list
```

Stacktrace

```
sbt.ForkMain$ForkError: java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420)
	at scala.collection.immutable.Nil$.head(List.scala:417)
	at scala.collection.generic.TraversableForwarder$class.head(TraversableForwarder.scala:56)
	at scala.collection.mutable.ListBuffer.head(ListBuffer.scala:45)
	at mesosphere.marathon.core.election.impl.CuratorElectionServiceTest$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$4.apply(CuratorElectionServiceTest.scala:42)
	at mesosphere.marathon.core.election.impl.CuratorElectionServiceTest$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$4.apply(CuratorElectionServiceTest.scala:40)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
	at mesosphere.UnitTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:27)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
	at mesosphere.UnitTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:27)
	at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
	at mesosphere.UnitTest.runTest(UnitTest.scala:27)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
	at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
	at mesosphere.UnitTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:27)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
	at mesosphere.marathon.core.election.impl.CuratorElectionServiceTest.org$scalatest$BeforeAndAfterAll$$super$run(CuratorElectionServiceTest.scala:14)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
	at mesosphere.marathon.core.election.impl.CuratorElectionServiceTest.run(CuratorElectionServiceTest.scala:14)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by timcharper** [comment]
This test does not fail in the unstable build, and, unfortunately, we don’t have any logs of it failing since https://github.com/mesosphere/marathon/commit/e32c3dd26a222226daeee3c3ee5a72690142f4ae; it was disabled again in https://phabricator.mesosphere.com/D223

**Comment by timcharper** [comment]
Jenkins unstable runner is currently down for the count. Need to wait for it to be resumed, run with D454, and collect some data.

**Comment by timcharper** [comment]
Jenkins marathon-unstable loop build is running again

**Comment by timcharper** [comment]
After at least 15 builds with the new unstable test run approach, this hasn’t shown up. Will monitor over the weekend. If it fails to show up, I don’t know what to do except assume it is now stable. If it fails again then we should take the opportunity to archive the logs.

**Comment by aquamatthias** [comment]
Patch is here: https://phabricator.mesosphere.com/D469

**Comment by timcharper** [comment]
After about 30 runs of unstable building the same way that stable does, we’ve not seen this fail. Seems safe to mark as stable.
