### ISSUE TITLE
 ERROR Promise already completed. (akka.actor.OneForOneStrategy:marathon-akka.actor.default-dispatcher-75166)

### ISSUE THREAD

**Issue by langtu329** [mesosphere/marathon#4570]
```Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]: [2016-10-10 16:03:52,288] INFO Synchronize tasks: 0 instances to kill (mesosphere.marathon.upgrade.TaskKillActor:marathon-akka.actor.default-dispatcher-75166)
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]: [2016-10-10 16:03:52,288] INFO Successfully killed all the tasks (mesosphere.marathon.upgrade.TaskKillActor:marathon-akka.actor.default-dispatcher-75166)

Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]: [2016-10-10 16:03:52,289] ERROR Promise already completed. (akka.actor.OneForOneStrategy:marathon-akka.actor.default-dispatcher-75166)

Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]**: java.lang.IllegalStateException: Promise already completed.**
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at scala.concurrent.Promise$class.complete(Promise.scala:55) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at scala.concurrent.Promise$class.success(Promise.scala:86) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:153) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at mesosphere.marathon.upgrade.StoppingBehavior$class.checkFinished(StoppingBehavior.scala:85) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at mesosphere.marathon.upgrade.TaskKillActor.checkFinished(TaskKillActor.scala:13) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at mesosphere.marathon.upgrade.StoppingBehavior$class.synchronizeTasks(StoppingBehavior.scala:79) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at mesosphere.marathon.upgrade.TaskKillActor.synchronizeTasks(TaskKillActor.scala:13) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at mesosphere.marathon.upgrade.StoppingBehavior$$anonfun$receive$1.applyOrElse(StoppingBehavior.scala:60) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at mesosphere.marathon.upgrade.TaskKillActor.aroundReceive(TaskKillActor.scala:13) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at akka.dispatch.Mailbox.exec(Mailbox.scala:231) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) ~[marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]:    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [marathon:1.1.2]
Oct 10 16:03:52 iZ23ieqxj0fZ marathon[1674]: [2016-10-10 16:03:52,289] INFO Killing 1 instances from 1 (mesosphere.marathon.upgrade.TaskKillActor:marathon-akka.actor.default-dispatcher-75161)```

marathon:Version 1.1.2  
who can help me? what should I do?

**Comment by aquamatthias** [comment]
@langtu329 Is that an ephemeral problem? Does this problem remain, after restarting Marathon?
Can you try to upgrade to the latest Marathon (1.3.2) - do you see the same failure?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2239. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
