### ISSUE TITLE
KillServiceActorTest.The KillServiceActor when asked to kill single known unreachable instance should issue no kill to the driver because the task is unreachable and send an expunge is flaky

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4721]
Reported by @nfnt 

Fails with the following error message:
A timeout occurred waiting for a future to complete. Queried 634 times, sleeping 15 milliseconds between each query.

Stacktrace:
```
      org.scalatest.concurrent.Futures$FutureConcept$$anon$1: A timeout occurred waiting for a future to complete. Queried 634 times, sleeping 15 milliseconds between each query.
      at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
      at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
      at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
      at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
      at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
      at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$27.apply(KillServiceActorTest.scala:90)
      at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$27.apply(KillServiceActorTest.scala:79)
      at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest.withActor(KillServiceActorTest.scala:319)
      at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply$mcV$sp(KillServiceActorTest.scala:79)
      at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply(KillServiceActorTest.scala:79)
      at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply(KillServiceActorTest.scala:79)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
      at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:77)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:77)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.AkkaUnitTest.runTest(UnitTest.scala:77)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
      at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
      at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:77)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:77)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.AkkaUnitTest.run(UnitTest.scala:77)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
```

**Comment by aquamatthias** [comment]
Review is here: https://phabricator.mesosphere.com/D423
