### ISSUE TITLE
KillServiceActorTest is broken

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4722]
Reported by @jeschkies 

https://jenkins.mesosphere.com/service/jenkins/job/public-test-marathon-phabricator/252/console

```
KillServiceActorTest:
The KillServiceActor when asked to kill single known unreachable instance should 
- issue no kill to the driver because the task is unreachable and send an expunge *** FAILED *** (10 seconds, 44 milliseconds)
  A timeout occurred waiting for a future to complete. Queried 634 times, sleeping 15 milliseconds between each query. (KillServiceActorTest.scala:90)
  org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
  at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
  at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
  at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
  at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
  at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
  at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$27.apply(KillServiceActorTest.scala:90)
  at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$27.apply(KillServiceActorTest.scala:79)
  at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest.withActor(KillServiceActorTest.scala:319)
  at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply$mcV$sp(KillServiceActorTest.scala:79)
  at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply(KillServiceActorTest.scala:79)
  at mesosphere.marathon.core.task.termination.impl.KillServiceActorTest$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply(KillServiceActorTest.scala:79)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
  at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
  at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
  at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
  at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:77)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:77)
  at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
  at mesosphere.AkkaUnitTest.runTest(UnitTest.scala:77)
  at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
  at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
  at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
  at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
  at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
  at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:77)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.AkkaUnitTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:77)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.AkkaUnitTest.run(UnitTest.scala:77)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by jeschkies** [comment]
See last failing tests
* https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/14/
* https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/15/
* https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/16/
* https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/18/
* https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/19
*

**Comment by jeschkies** [comment]
https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/21/

**Comment by jeschkies** [comment]
I think the issue is that the `InstanceKillProgressActor` did not subscribe to the kill events yet

```
DEBUG[12:21:57 KillServiceActor] started (mesosphere.marathon.core.task.termination.impl.KillServiceActor@6d4d954)
DEBUG[12:21:57 KillServiceActor] now watched by Actor[akka://KillServiceActorTest/system/eventStreamUnsubscriber-1#-1342581717]
INFO [12:21:57 InstanceUpdater$] all tasks of instance [test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5] are terminal, requesting to expunge
DEBUG[12:21:57 KillServiceActor] Adding 3 instances to queue; setting up child actor to track progress
INFO [12:21:57 KillServiceActorTest$] publish InstanceChanged(instance [test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5],1970-01-01T00:00:00.000Z,/test,Killed,Instance(instance [test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5],AgentInfo(host.some,None,List()),InstanceState(Killed,2015-02-03T11:30:00.000Z,None,None),Map(task [test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5.$anon] -> LaunchedEphemeral(task [test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5.$anon],2015-04-09T10:
30:00.000Z,Status(2015-04-09T10:30:00.000Z,None,Some(task_id {
  value: "test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5.$anon"
}
state: TASK_KILLED
timestamp: 0.0
),Killed,NetworkInfo(host.some,List(),List())))),1970-01-01T00:00:00.000Z,UnreachableStrategy(5 minutes,10 minutes))) on the event stream
INFO [12:21:57 InstanceUpdater$] all tasks of instance [test.instance-7be0627a-e2f0-11e6-93a2-0e1df3f5ede5] are terminal, requesting to expunge
INFO [12:21:57 KillServiceActor] processing 3 kills
WARN [12:21:57 KillServiceActor] Killing known task [test.instance-7be0627b-e2f0-11e6-93a2-0e1df3f5ede5.$anon] of instance instance [test.instance-7be0627b-e2f0-11e6-93a2-0e1df3f5ede5]
INFO [12:21:57 KillServiceActorTest$] publish InstanceChanged(instance [test.instance-7be0627a-e2f0-11e6-93a2-0e1df3f5ede5],1970-01-01T00:00:00.000Z,/test,Gone,Instance(instance [test.instance-7be0627a-e2f0-11e6-93a2-0e1df3f5ede5],AgentInfo(host.some,None,List()),InstanceState(Gone,2015-02-03T11:30:00.000Z,None,None),Map(task [test.instance-7be0627a-e2f0-11e6-93a2-0e1df3f5ede5.$anon] -> LaunchedEphemeral(task [test.instance-7be0627a-e2f0-11e6-93a2-0e1df3f5ede5.$anon],2015-04-09T10:30:0
0.000Z,Status(2015-04-09T10:30:00.000Z,None,Some(task_id {
  value: "test.instance-7be0627a-e2f0-11e6-93a2-0e1df3f5ede5.$anon"
}
state: TASK_GONE
timestamp: 0.0
),Gone,NetworkInfo(host.some,List(),List())))),1970-01-01T00:00:00.000Z,UnreachableStrategy(5 minutes,10 minutes))) on the event stream
INFO [12:21:57 InstanceKillProgressActor] Starting InstanceKillProgressActor600199689 to track kill progress of 3 instances
WARN [12:21:57 KillServiceActor] Killing known task [test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5.$anon] of instance instance [test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5]
DEBUG[12:21:57 InstanceKillProgressActor] started (mesosphere.marathon.core.task.termination.impl.InstanceKillProgressActor@10d02462)
DEBUG[12:21:57 InstanceKillProgressActor] now watched by Actor[akka://KillServiceActorTest/system/eventStreamUnsubscriber-1#-1342581717]
WARN [12:21:57 KillServiceActor] Expunging instance [test.instance-7be0627a-e2f0-11e6-93a2-0e1df3f5ede5] from state because it is lost
DEBUG[12:21:57 KillServiceActor] now supervising Actor[akka://KillServiceActorTest/user/KillService-1a4d7235-d5b9-432b-9619-48f48987d793/$a#600199689]
DEBUG[12:21:57 KillServiceActor] instance [test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5] is terminal. (0 kills queued, 2 in flight)
INFO [12:21:57 KillServiceActor] processing 0 kills
DEBUG[12:21:57 KillServiceActor] instance [test.instance-7be0627a-e2f0-11e6-93a2-0e1df3f5ede5] is terminal. (0 kills queued, 1 in flight)
DEBUG[12:21:57 InstanceKillProgressActor] Received terminal update for instance [test.instance-7be0627a-e2f0-11e6-93a2-0e1df3f5ede5]
INFO [12:21:57 KillServiceActor] processing 0 kills
INFO [12:21:57 InstanceKillProgressActor] InstanceKillProgressActor600199689 still waiting for 2 instances to be killed
INFO [12:21:57 KillServiceActorTest$] publish InstanceChanged(instance [test.instance-7be0627b-e2f0-11e6-93a2-0e1df3f5ede5],1970-01-01T00:00:00.000Z,/test,UnreachableInactive,Instance(instance [test.instance-7be0627b-e2f0-11e6-93a2-0e1df3f5ede5],AgentInfo(host.some,None,List()),InstanceState(UnreachableInactive,2015-02-03T11:30:00.000Z,None,None),Map(task [test.instance-7be0627b-e2f0-11e6-93a2-0e1df3f5ede5.$anon] -> LaunchedEphemeral(task [test.instance-7be0627b-e2f0-11e6-93a2-0e1df3f5ede5.$anon],2015-04-09T10:30:00.000Z,Status(2015-04-09T10:30:00.000Z,None,Some(task_id {
  value: "test.instance-7be0627b-e2f0-11e6-93a2-0e1df3f5ede5.$anon"
}
state: TASK_UNREACHABLE
timestamp: 0.0
unreachable_time {
  nanoseconds: 0
}
),Unreachable,NetworkInfo(host.some,List(),List())))),1970-01-01T00:00:00.000Z,UnreachableStrategy(5 minutes,10 minutes))) on the event stream
DEBUG[12:21:57 KillServiceActor] instance [test.instance-7be0627b-e2f0-11e6-93a2-0e1df3f5ede5] is terminal. (0 kills queued, 0 in flight)
INFO [12:21:57 KillServiceActor] processing 0 kills
DEBUG[12:21:57 InstanceKillProgressActor] Received terminal update for instance [test.instance-7be0627b-e2f0-11e6-93a2-0e1df3f5ede5]
INFO [12:21:57 InstanceKillProgressActor] InstanceKillProgressActor600199689 still waiting for 1 instances to be killed
DEBUG[12:22:08 KillServiceActor] received AutoReceiveMessage Envelope(PoisonPill,Actor[akka://KillServiceActorTest/deadLetters])
DEBUG[12:22:08 KillServiceActor] stopping
DEBUG[12:22:08 KillServiceActor] now watched by Actor[akka://KillServiceActorTest/system/testProbe-5#508210566]
ERROR[12:22:08 InstanceKillProgressActor] InstanceKillProgressActor600199689 was stopped before all instances are killed. Outstanding: instance [test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5]
DEBUG[12:22:08 InstanceKillProgressActor] stopped
DEBUG[12:22:08 KillServiceActor] stopped
[info]   - should issue three kill requests to the driver *** FAILED ***
[info]     A timeout occurred waiting for a future to complete. Queried 604 times, sleeping 15 milliseconds between each query. (KillServiceActorTest.scala:114)
```

Note that `publish InstanceChanged(instance [test.instance-7be06279-e2f0-11e6-93a2-0e1df3f5ede5]` comes before `Starting InstanceKillProgressActor600199689 to track kill progress of 3 instances`. Thus the actor misses the update for that instance.

**Comment by jeschkies** [comment]
I see multiple options:

* Wait in the test until the progress actor is ready.
* Replace the progress actor with something else. E.g. communicate the kill with another promise.
* Start the progress actor faster by subscribing in a non blocking way and stash all messages until ready.

**Comment by jeschkies** [comment]
I verified my assumption with an evil `Thread.sleep` in the test.

**Comment by jeschkies** [comment]
https://phabricator.mesosphere.com/D443
