### ISSUE TITLE
ResidentTaskIntegrationTest.Config Change is flaky

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4723]
Reported by @nfnt 

Stack trace from a test failure in CI:

```
[info] - Config Change *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [60 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at mesosphere.marathon.integration.setup.WaitTestSupport$.waitFor(WaitTestSupport.scala:35)
[info]   at mesosphere.marathon.integration.setup.MarathonCallbackTestSupport$class.waitForEventMatching(MarathonCallbackTestSupport.scala:65)
[info]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForEventMatching(ResidentTaskIntegrationTest.scala:21)
[info]   at mesosphere.marathon.integration.setup.MarathonCallbackTestSupport$class.waitForEventWith(MarathonCallbackTestSupport.scala:72)
[info]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForEventWith(ResidentTaskIntegrationTest.scala:21)
[info]   ...
[info]   + Given a resident app with 5 instances 
[info]   + When we change the config onintegrationtest/app-8, taskId -> marathonintegrationtest_app-8.e143ee1f-ab44-11e6-a7d3-024235695b2d))
```

**Comment by marcomonaco** [comment]
Duplicate #4779

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1881. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
