### ISSUE TITLE
TaskUnreachableIntegrationTest is broken

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4724]
Reported by @nfnt  

"A task unreachable update will trigger a replacement task" doesn't work.
see: https://phabricator.mesosphere.com/D190

**Comment by jeschkies** [comment]
I've seen 

```
*** 1 SUITE ABORTED ***
TaskUnreachableIntegrationTest:
 *** ABORTED *** (4 minutes, 6 seconds)
  The code passed to eventually never returned normally. Attempted 4808 times over 1.5000334424833333 minutes. Last failure message: No content to map due to end-of-input
   at [Source: ; line: 1, column: 0]. (WaitTestSupport.scala:26)
  org.scalatest.exceptions.TestFailedDueToTimeoutException:
  at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
  at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
  at mesosphere.marathon.integration.setup.WaitTestSupport$.eventually(WaitTestSupport.scala:12)
  at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)
  at mesosphere.marathon.integration.setup.WaitTestSupport$.eventually(WaitTestSupport.scala:12)
  at mesosphere.marathon.integration.setup.WaitTestSupport$.waitUntil(WaitTestSupport.scala:26)
  at mesosphere.marathon.integration.setup.MarathonTest$class.cleanUp(MarathonTest.scala:402)
  at mesosphere.marathon.integration.TaskUnreachableIntegrationTest.cleanUp(TaskUnreachableIntegrationTest.scala:13)
  at mesosphere.marathon.integration.TaskUnreachableIntegrationTest$$anonfun$1.apply$mcV$sp(TaskUnreachableIntegrationTest.scala:42)
```

That's an error during the clean up. This might be related.

**Comment by jeschkies** [comment]
Has been fixed.
