### ISSUE TITLE
EOFException

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4729]
Reported by @jeschkies 

```
[2016-11-03 23:00:48,588] ERROR [] Could not process offer '1'
java.lang.RuntimeException: failed matching
	at mesosphere.marathon.core.launcher.impl.OfferProcessorImplTest$$anonfun$7.apply$mcV$sp(OfferProcessorImplTest.scala:270)
	at mesosphere.marathon.core.launcher.impl.OfferProcessorImplTest$$anonfun$7.apply(OfferProcessorImplTest.scala:266)
	at mesosphere.marathon.core.launcher.impl.OfferProcessorImplTest$$anonfun$7.apply(OfferProcessorImplTest.scala:266)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at mesosphere.marathon.core.launcher.impl.OfferProcessorImplTest.withFixture(OfferProcessorImplTest.scala:23)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
	at mesosphere.marathon.core.launcher.impl.OfferProcessorImplTest.org$scalatest$BeforeAndAfter$$super$runTest(OfferProcessorImplTest.scala:23)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
	at mesosphere.marathon.core.launcher.impl.OfferProcessorImplTest.runTest(OfferProcessorImplTest.scala:23)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
	at mesosphere.marathon.core.launcher.impl.OfferProcessorImplTest.runTests(OfferProcessorImplTest.scala:23)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at mesosphere.marathon.core.launcher.impl.OfferProcessorImplTest.org$scalatest$FunSuiteLike$$super$run(OfferProcessorImplTest.scala:23)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
	at mesosphere.marathon.core.launcher.impl.OfferProcessorImplTest.org$scalatest$BeforeAndAfter$$super$run(OfferProcessorImplTest.scala:23)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
	at mesosphere.marathon.core.launcher.impl.OfferProcessorImplTest.run(OfferProcessorImplTest.scala:23)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-11-03 23:00:48,603] INFO [] actor system InstanceCreationHandlerAndUpdaterDelegateTest: starting
[2016-11-03 23:00:48,797] INFO [] actor system InstanceCreationHandlerAndUpdaterDelegateTest: shutting down
[2016-11-03 23:00:48,831] INFO [] Slf4jLogger started
[info] - should have no ids
[32m- should have no ids (1 second, 36 milliseconds)[0m
[2016-11-03 23:00:48,932] INFO [] Starting
[2016-11-03 23:00:48,935] INFO [] State change: CONNECTED
[info] - backwards compatibility with old TASK_LOST status
[info]   + Given two unreachable tasks, one overdue 
[info]   + When a check is performed 
[info]   + And one expunge is issued 
[2016-11-03 23:00:48,971] INFO [akka://default/user/$a] ExpungeOverdueLostTasksActor has stopped
[32m- backwards compatibility with old TASK_LOST status (3 seconds, 22 milliseconds)[0m
[32m  + Given two unreachable tasks, one overdue [0m
[32m  + When a check is performed [0m
[32m  + And one expunge is issued [0m
[2016-11-03 23:00:49,065] ERROR [] while executing step nested for [test.instance-5c78039d-a219-11e6-b70a-0242833ea540], continue with other steps
java.lang.RuntimeException: error!
	at mesosphere.marathon.core.task.update.impl.steps.ContinueOnErrorStepTest$$anonfun$5.apply(ContinueOnErrorStepTest.scala:47)
	at mesosphere.marathon.core.task.update.impl.steps.ContinueOnErrorStepTest$$anonfun$5.apply(ContinueOnErrorStepTest.scala:43)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
	at 
```

https://jenkins.mesosphere.com/service/jenkins/job/marathon-unit-integration-tests-pushes/2543/
https://jenkins.mesosphere.com/service/jenkins/job/marathon-unit-integration-tests-pushes/2537/
https://jenkins.mesosphere.com/service/jenkins/job/public-marathon-phabricator-legacy/987/

**Comment by jeschkies** [comment]
Haven't seen this in a fail. Let's close it.
