### ISSUE TITLE
java.io.IOException: Cannot run program "jps": error=23, Too many open files in system

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4730]
Reported by @jeschkies 

```
mesosphere.marathon.integration.AppDeployWithLeaderAbdicationIntegrationTest *** ABORTED *** (2 minutes, 35 seconds)
  java.io.IOException: Cannot run program "jps": error=23, Too many open files in system
  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
  at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:113)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:129)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
  at mesosphere.marathon.integration.setup.LocalMarathon.stop(MarathonTest.scala:153)
  at mesosphere.marathon.integration.setup.LocalMarathon.close(MarathonTest.scala:162)
  at mesosphere.marathon.integration.setup.MarathonClusterTest$$anonfun$afterAll$2.apply(MarathonTest.scala:564)
  at mesosphere.marathon.integration.setup.MarathonClusterTest$$anonfun$afterAll$2.apply(MarathonTest.scala:564)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at mesosphere.marathon.integration.setup.MarathonClusterTest$class.afterAll(MarathonTest.scala:564)
  at mesosphere.marathon.integration.AppDeployWithLeaderAbdicationIntegrationTest.afterAll(AppDeployWithLeaderAbdicationIntegrationTest.scala:19)
  at org.scalatest.BeforeAndAfterAll$$anonfun$1.apply$mcV$sp(BeforeAndAfterAll.scala:225)
  at org.scalatest.Status$$anonfun$withAfterEffect$1.apply(Status.scala:379)
  at org.scalatest.Status$$anonfun$withAfterEffect$1.apply(Status.scala:375)
  at org.scalatest.CompositeStatus.whenCompleted(Status.scala:886)
  at org.scalatest.Status$class.withAfterEffect(Status.scala:375)
  at org.scalatest.CompositeStatus.withAfterEffect(Status.scala:782)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:223)
  at mesosphere.FunTest.run(UnitTest.scala:97)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  Cause: java.io.IOException: error=23, Too many open files in system
  at java.lang.UNIXProcess.forkAndExec(Native Method)
  at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
  at java.lang.ProcessImpl.start(ProcessImpl.java:134)
  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
  at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:113)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:129)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
  at mesosphere.marathon.integration.setup.LocalMarathon.stop(MarathonTest.scala:153)
  at mesosphere.marathon.integration.setup.LocalMarathon.close(MarathonTest.scala:162)
  at mesosphere.marathon.integration.setup.MarathonClusterTest$$anonfun$afterAll$2.apply(MarathonTest.scala:564)
  at mesosphere.marathon.integration.setup.MarathonClusterTest$$anonfun$afterAll$2.apply(MarathonTest.scala:564)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at mesosphere.marathon.integration.setup.MarathonClusterTest$class.afterAll(MarathonTest.scala:564)
  at mesosphere.marathon.integration.AppDeployWithLeaderAbdicationIntegrationTest.afterAll(AppDeployWithLeaderAbdicationIntegrationTest.scala:19)
  at org.scalatest.BeforeAndAfterAll$$anonfun$1.apply$mcV$sp(BeforeAndAfterAll.scala:225)
  at org.scalatest.Status$$anonfun$withAfterEffect$1.apply(Status.scala:379)
  at org.scalatest.Status$$anonfun$withAfterEffect$1.apply(Status.scala:375)
  at org.scalatest.CompositeStatus.whenCompleted(Status.scala:886)
  at org.scalatest.Status$class.withAfterEffect(Status.scala:375)
  at org.scalatest.CompositeStatus.withAfterEffect(Status.scala:782)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:223)
  at mesosphere.FunTest.run(UnitTest.scala:97)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by jeschkies** [comment]
Haven't seen this in a while. Let's close it.
