### ISSUE TITLE
Test coverage is not checked in CI

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#4785]
Currently our test coverage is actually too low:

```
[info] Written Cobertura report [/Users/kjeschkies/Projects/marathon/target/scala-2.11/coverage-report/cobertura.xml]
[info] Written XML coverage report [/Users/kjeschkies/Projects/marathon/target/scala-2.11/scoverage-report/scoverage.xml]
[info] Written HTML coverage report [/Users/kjeschkies/Projects/marathon/target/scala-2.11/scoverage-report/index.html]
[info] Statement coverage.: 68.24%
[info] Branch coverage....: 62.38%
[info] Coverage reports completed
[error] Coverage is below minimum [68.24% < 69.0%]
java.lang.RuntimeException: Coverage minimum was not reached
	at scoverage.ScoverageSbtPlugin$.scoverage$ScoverageSbtPlugin$$checkCoverage(ScoverageSbtPlugin.scala:261)
	at scoverage.ScoverageSbtPlugin$$anonfun$coverageReport0$1.apply(ScoverageSbtPlugin.scala:125)
	at scoverage.ScoverageSbtPlugin$$anonfun$coverageReport0$1.apply(ScoverageSbtPlugin.scala:104)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Also [public-test-marathon-phabricator](https://jenkins.mesosphere.com/service/jenkins/job/public-test-marathon-phabricator/538/) parses the wrong coverage file.

**Comment by jeschkies** [comment]
Seems coverage report is on integration tests? 

```bash
sudo -E sbt -Dsbt.log.format=false coverage test:compile scapegoat doc test integration:test mesos-simulation/integration:test coverageReport
```

**Comment by jeschkies** [comment]
Done with https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-unit-integration-tests-pushes/jobConfigHistory/showDiffFiles?timestamp1=2016-12-15_16-32-03&timestamp2=2016-12-20_15-32-21
