### ISSUE TITLE
PODs API should not drop silently endpoint node, if name property is missing

### ISSUE THREAD

**Issue by unterstein** [mesosphere/marathon#4826]
When adding a pod with the following spec, the endpoint is not created, but a `201` is returned:

```
{
 "id": "/sleepypod",
 "version": "2016-09-22T09:18:05.928Z",
 "user": null,
 "environment": null,
 "containers": [
   {
     "name": "sleep1",
     "exec": {
       "command": {
         "shell": "sleep 1000"
       }
     },
     "resources": {
       "cpus": 0.1,
       "mem": 32,
       "disk": 0,
       "gpus": 0
     },
     "endpoints": [
     { "hostPort": 80, "protocol": [ "http" ] }
     ],
     "image": null,
     "environment": null,
     "user": null,
     "healthCheck": null,
     "volumeMounts": [],
     "artifacts": [],
     "labels": null,
     "lifecycle": null
   }
 ],
 "secrets": null,
 "volumes": [],
 "networks": [
   {
     "mode": "host"
   }
 ],
 "scaling": {
   "kind": "fixed",
   "instances": 2,
   "maxInstances": null
 },
 "scheduling": {
   "backoff": {
     "backoff": 1,
     "backoffFactor": 1.15,
     "maxLaunchDelay": 3600
   },
   "upgrade": {
     "minimumHealthCapacity": 1,
     "maximumOverCapacity": 1
   },
   "placement": {
     "constraints": [],
     "acceptedResourceRoles": []
   }
 }
}
```

The issue is `{ "hostPort": 80, "protocol": [ "http" ] }`. When this part is changed to `{ "name": "web", "hostPort": 80, "protocol": [ "http" ] }` the API works as expected.

Expected behavior: The API should not drop the endpoint silently, if the name is not defined.

**Comment by unterstein** [comment]
// cc @orlandohohmeier @Poltergeist

**Comment by jdef** [comment]
very strange. the RAML says that `name` is a required field with no default value. wonder why we don't see a failure at JSON-parse time

**Comment by jdef** [comment]
I wonder ... is the endpoint silently dropped all together when `name` isn't present?

**Comment by unterstein** [comment]
yep

**Comment by unterstein** [comment]
only the one endpoint node

**Comment by jdef** [comment]
hm .. our RAML-to-scala generator has a bug then

**Comment by jdef** [comment]
currently the generated JSON parsing code for endpoints (see `PodContainer`) looks like this:
```scala
val endpoints = json.\("endpoints").validateOpt[scala.collection.immutable.Seq[Endpoint]].map(_.getOrElse(scala.collection.immutable.Seq[Endpoint]()))
```
which says to me "if validation of the sequence fails, then disqualify all endpoints" .. and that seems wrong

**Comment by jdef** [comment]
this appears to be fixed. what version of Marathon was this bug generated against?
```
scala> val obj3 = play.api.libs.json.Json.parse("""{ "id": "someid", "cmd": "bar", "containers": [ { "name": "foo", "resources": {}, "endpoints": [ { "hostPort": 0, "protocol": [ "tcp" ] } ] } ] }""")
obj3: play.api.libs.json.JsValue = {"id":"someid","cmd":"bar","containers":[{"name":"foo","resources":{},"endpoints":[{"hostPort":0,"protocol":["tcp"]}]}]}

scala> val ct = obj3.as[mesosphere.marathon.raml.Pod]
play.api.libs.json.JsResultException: JsResultException(errors:List((/containers(0)/endpoints(0)/name,List(ValidationError(List('name' is undefined on object: {"hostPort":0,"protocol":["tcp"]}),WrappedArray())))))
  at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
  at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
  at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
  at play.api.libs.json.JsError.fold(JsResult.scala:13)
  at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
  at play.api.libs.json.JsObject.as(JsValue.scala:76)
  ... 42 elided

```

**Comment by jdef** [comment]
pretty sure it's resolved by https://github.com/mesosphere/marathon/commit/59dafc55100e3cd67b5e604ce83de2201cf77e25#diff-e7dfc9d789e1c8cbb9133f77b5774e39

**Comment by unterstein** [comment]
MarathonVersion 1.4.0-snap29, current dcos testing/master

**Comment by jdef** [comment]
OK, snap30 was the first build w/ the validation fix

**Comment by unterstein** [comment]
Great! 

RC3 works as expected

```
{
"message": "Invalid JSON",
"details":[
{
"path": "/containers(0)/endpoints(0)/name",
"errors":[
"'name' is undefined on object: {\"hostPort\":80,\"protocol\":[\"http\"]}"
]
}
]
}
```

**Comment by unterstein** [comment]
Thanks for pointing to the fixing commit James :)
