### ISSUE TITLE
java.lang.ClassCastException: Cannot cast akka.Done$ to mesosphere.marathon.core.launchqueue.LaunchQueue$QueuedInstanceInfo

### ISSUE THREAD

**Issue by mpark** [mesosphere/marathon#4831]
While running the following script:

```
#!/bin/bash

for i in {1..300}; do
http POST :8080/v2/apps <<EOF
{
  "id" : "/$(($i % 17))/$(($i % 13))/$(($i % 11))/$(($i % 7))/simple-app-$i",
  "cmd": "sleep 1000",
  "instances": 1,
  "cpus": 0.01,
  "mem": 1,
  "disk": 0
}
EOF
done
```

Running Marathon HEAD with `SimulatedMesosMain`, I keep observing the following error messages:

```
[2016-12-12 13:48:47,180] ERROR while executing step notifyLaunchQueue for [4_9_6_3_simple-app-633.marathon-c22e5046-c0b4-11e6-8a64-ea6731f846a1], continue with other steps (mesosphere.marathon.core.task.update.impl.steps.ContinueOnErrorStep:ForkJoinPool-2-worker-127)
java.lang.ClassCastException: Cannot cast akka.Done$ to mesosphere.marathon.core.launchqueue.LaunchQueue$QueuedInstanceInfo
    at java.lang.Class.cast(Class.java:3369)
    at scala.concurrent.Future$$anonfun$mapTo$1.apply(Future.scala:407)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
    at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
    at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
    at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
    at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
    at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
    at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:534)
    at mesosphere.marathon.core.launchqueue.impl.TaskLauncherActor$$anonfun$receiveInstanceUpdate$1.applyOrElse(TaskLauncherActor.scala:286)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
    at mesosphere.marathon.core.launchqueue.impl.TaskLauncherActor.aroundReceive(TaskLauncherActor.scala:76)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
    at akka.actor.ActorCell.invoke(ActorCell.scala:495)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by aquamatthias** [comment]
https://phabricator.mesosphere.com/D323

**Comment by aquamatthias** [comment]
The TaskLauncherActor implemented the change, but not the LaunchQueue.
The exception is fetched and ignored in the UpdateStep, so the update works as expected.
