### ISSUE TITLE
Unstable test: MarathonStoreTest "names() correctly uses timeouts"

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4840]
https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-marathon-unstable/1062/testReport/mesosphere.marathon.state/MarathonStoreTest/names___correctly_uses_timeouts/

```
Error Message

An unexpected java.util.concurrent.TimeoutException was thrown.
Stacktrace

      org.scalatest.exceptions.TestFailedException: An unexpected java.util.concurrent.TimeoutException was thrown.
      at org.scalatest.MatchersHelper$.checkNoException(MatchersHelper.scala:329)
      at org.scalatest.words.ResultOfBeWordForNoException.thrownBy(ResultOfBeWordForNoException.scala:39)
      at mesosphere.marathon.state.MarathonStoreTest$$anonfun$27.apply(MarathonStoreTest.scala:216)
      at mesosphere.marathon.state.MarathonStoreTest$$anonfun$27.apply(MarathonStoreTest.scala:202)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at mesosphere.marathon.state.MarathonStoreTest.withFixture(MarathonStoreTest.scala:19)
      at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
      at mesosphere.marathon.state.MarathonStoreTest.org$scalatest$BeforeAndAfter$$super$runTe
```

**Comment by timcharper** [comment]
These tests are part of the legacy storage which is going to be purged from the codebase. Wiping out the test suite.

**Comment by timcharper** [comment]
This test looks to have been broken since this change: https://github.com/mesosphere/marathon/commit/c9a69efecb0baf0b5b192f8d45a57d17c648a81c#diff-fa1148618ee993b9bcf48ebc02e5a968L118

The behavior used to be to swallow exceptions and return nothing (arguably not ideal). Also, it previously used the `BackToTheFuture.futureToFuture` method (as seen [here](https://github.com/mesosphere/mesos-utils/blob/v0.22.1-1/src/main/scala/mesosphere/util/BackToTheFuture.scala#L31) which had a timeout. There is no longer a timeout.

I'm going to delete this test because it is testing a special behavior that seems to have been removed over a year ago, and I'm assuming the new behavior is correct since it has stayed like that for so long.

**Comment by timcharper** [comment]
https://phabricator.mesosphere.com/D330
