### ISSUE TITLE
MesosAppIntegrationTest "delete pod instances" is Unstable

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4844]
Marked as such in 8bf7ac157f11acb3a59f6d3ee9780b84b6172f74

Seen here:  https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-loop-tests/1963/testReport/

## Error Message

```
List(PodInstanceStatus(simplepod.instance-df62c3ec-c18d-11e6-bdab-0242a0890e80,STABLE,2016-12-13T23:42:56.860Z,None,List(),Some(localhost),Some(Resources(0.2,64.0,10.0,0)),List(NetworkStatus(None,List(127.0.0.1))),List(ContainerStatus(task1,TASK_RUNNING,2016-12-13T23:42:56.860Z,None,List(),Some(simplepod.instance-df62c3ec-c18d-11e6-bdab-0242a0890e80.task1),List(),Some(Resources(0.1,32.0,0.0,0)),None,2016-12-13T23:42:56.860Z,2016-12-13T23:42:56.860Z)),Some(/v2/pods/simplepod::versions/2016-12-13T23:42:56.302Z),2016-12-13T23:42:56.860Z,2016-12-13T23:42:56.860Z), PodInstanceStatus(simplepod.instance-df5f8f9b-c18d-11e6-bdab-0242a0890e80,STABLE,2016-12-13T23:42:56.783Z,None,List(),Some(localhost),Some(Resources(0.2,64.0,10.0,0)),List(NetworkStatus(None,List(127.0.0.1))),List(ContainerStatus(task1,TASK_RUNNING,2016-12-13T23:42:56.783Z,None,List(),Some(simplepod.instance-df5f8f9b-c18d-11e6-bdab-0242a0890e80.task1),List(),Some(Resources(0.1,32.0,0.0,0)),None,2016-12-13T23:42:56.783Z,2016-12-13T23:42:56.783Z)),Some(/v2/pods/simplepod::versions/2016-12-13T23:42:56.302Z),2016-12-13T23:42:56.783Z,2016-12-13T23:42:56.783Z), PodInstanceStatus(simplepod.instance-dfd5d10f-c18d-11e6-bdab-0242a0890e80,STABLE,2016-12-13T23:42:57.330Z,None,List(),Some(localhost),Some(Resources(0.2,64.0,10.0,0)),List(NetworkStatus(None,List(127.0.0.1))),List(ContainerStatus(task1,TASK_RUNNING,2016-12-13T23:42:57.330Z,None,List(),Some(simplepod.instance-dfd5d10f-c18d-11e6-bdab-0242a0890e80.task1),List(),Some(Resources(0.1,32.0,0.0,0)),None,2016-12-13T23:42:57.330Z,2016-12-13T23:42:57.330Z)),Some(/v2/pods/simplepod::versions/2016-12-13T23:42:56.302Z),2016-12-13T23:42:57.330Z,2016-12-13T23:42:57.330Z), PodInstanceStatus(simplepod.instance-dfd534ce-c18d-11e6-bdab-0242a0890e80,PENDING,2016-12-13T23:42:57.123Z,None,List(),Some(localhost),Some(Resources(0.1,32.0,10.0,0)),List(),List(ContainerStatus(task1,TASK_STAGING,2016-12-13T23:42:57.123Z,None,List(),Some(simplepod.instance-dfd534ce-c18d-11e6-bdab-0242a0890e80.task1),List(),None,None,2016-12-13T23:42:57.123Z,2016-12-13T23:42:57.123Z)),Some(/v2/pods/simplepod::versions/2016-12-13T23:42:56.302Z),2016-12-13T23:42:57.123Z,2016-12-13T23:42:57.123Z)) had size 4 instead of expected size 3
```

## Stacktrace

```
      org.scalatest.exceptions.TestFailedException: List(PodInstanceStatus(simplepod.instance-df62c3ec-c18d-11e6-bdab-0242a0890e80,STABLE,2016-12-13T23:42:56.860Z,None,List(),Some(localhost),Some(Resources(0.2,64.0,10.0,0)),List(NetworkStatus(None,List(127.0.0.1))),List(ContainerStatus(task1,TASK_RUNNING,2016-12-13T23:42:56.860Z,None,List(),Some(simplepod.instance-df62c3ec-c18d-11e6-bdab-0242a0890e80.task1),List(),Some(Resources(0.1,32.0,0.0,0)),None,2016-12-13T23:42:56.860Z,2016-12-13T23:42:56.860Z)),Some(/v2/pods/simplepod::versions/2016-12-13T23:42:56.302Z),2016-12-13T23:42:56.860Z,2016-12-13T23:42:56.860Z), PodInstanceStatus(simplepod.instance-df5f8f9b-c18d-11e6-bdab-0242a0890e80,STABLE,2016-12-13T23:42:56.783Z,None,List(),Some(localhost),Some(Resources(0.2,64.0,10.0,0)),List(NetworkStatus(None,List(127.0.0.1))),List(ContainerStatus(task1,TASK_RUNNING,2016-12-13T23:42:56.783Z,None,List(),Some(simplepod.instance-df5f8f9b-c18d-11e6-bdab-0242a0890e80.task1),List(),Some(Resources(0.1,32.0,0.0,0)),None,2016-12-13T23:42:56.783Z,2016-12-13T23:42:56.783Z)),Some(/v2/pods/simplepod::versions/2016-12-13T23:42:56.302Z),2016-12-13T23:42:56.783Z,2016-12-13T23:42:56.783Z), PodInstanceStatus(simplepod.instance-dfd5d10f-c18d-11e6-bdab-0242a0890e80,STABLE,2016-12-13T23:42:57.330Z,None,List(),Some(localhost),Some(Resources(0.2,64.0,10.0,0)),List(NetworkStatus(None,List(127.0.0.1))),List(ContainerStatus(task1,TASK_RUNNING,2016-12-13T23:42:57.330Z,None,List(),Some(simplepod.instance-dfd5d10f-c18d-11e6-bdab-0242a0890e80.task1),List(),Some(Resources(0.1,32.0,0.0,0)),None,2016-12-13T23:42:57.330Z,2016-12-13T23:42:57.330Z)),Some(/v2/pods/simplepod::versions/2016-12-13T23:42:56.302Z),2016-12-13T23:42:57.330Z,2016-12-13T23:42:57.330Z), PodInstanceStatus(simplepod.instance-dfd534ce-c18d-11e6-bdab-0242a0890e80,PENDING,2016-12-13T23:42:57.123Z,None,List(),Some(localhost),Some(Resources(0.1,32.0,10.0,0)),List(),List(ContainerStatus(task1,TASK_STAGING,2016-12-13T23:42:57.123Z,None,List(),Some(simplepod.instance-dfd534ce-c18d-11e6-bdab-0242a0890e80.task1),List(),None,None,2016-12-13T23:42:57.123Z,2016-12-13T23:42:57.123Z)),Some(/v2/pods/simplepod::versions/2016-12-13T23:42:56.302Z),2016-12-13T23:42:57.123Z,2016-12-13T23:42:57.123Z)) had size 4 instead of expected size 3
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
      at org.scalatest.Matchers$ResultOfHaveWordForExtent.size(Matchers.scala:2707)
      at mesosphere.marathon.integration.MesosAppIntegrationTest$$anonfun$18.apply(MesosAppIntegrationTest.scala:371)
      at mesosphere.marathon.integration.MesosAppIntegrationTest$$anonfun$18.apply(MesosAppIntegrationTest.scala:344)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.FunTest.runTest(UnitTest.scala:99)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
      at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.FunTest.run(UnitTest.scala:99)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
```

**Comment by timcharper** [comment]
Marking as serial did not help

**Comment by unterstein** [comment]
Get exactly the same error message around each 20th run of this test.

I think the relevant log lines looks like:

```
DEBUG[08:49:01 MesosAppIntegrationTest-LocalMarathon-41853] INFO [08:49:01 SchedulerActions] Need to scale /simplepod from 2 up to 3 instances
DEBUG[08:49:01 MesosAppIntegrationTest-LocalMarathon-41853] INFO [08:49:01 ScaleAppUpdateStepImpl$$EnhancerByGuice$$3ae17765] initiating a scale check for runSpec [/simplepod] due to [instance [simplepod.instance-e5d9f0a4-e39b-11e6-b12a-02426d360459]] Killed
DEBUG[08:49:01 MesosAppIntegrationTest-LocalMarathon-41853] INFO [08:49:01 SchedulerActions] Need to scale /simplepod from 2 up to 3 instances
DEBUG[08:49:01 MesosAppIntegrationTest-LocalMarathon-41853] INFO [08:49:01 SchedulerActions] Queueing 1 new instances for /simplepod to the already 0 queued ones
DEBUG[08:49:01 MesosAppIntegrationTest-LocalMarathon-41853] INFO [08:49:01 OfferMatcherManagerActor] activating matcher ActorOfferMatcher(Actor[akka://marathon/user/launchQueue/1/11-simplepod#-2034005459]).
DEBUG[08:49:01 MesosAppIntegrationTest-LocalMarathon-41853] INFO [08:49:01 SchedulerActions] Queueing 1 new instances for /simplepod to the already 0 queued ones
```

So two new instances are scheduled, but only one newly scheduled instance come from `ScaleAppUpdateStepImpl`. Therefore I think this could be a race between ScaleAppUpdateStepImpl and this periodic scale check thingy.

**Comment by unterstein** [comment]
Currently testing if adjusting `scale_apps_initial_delay` leads to less occurrences by running this test in a longer loop. If so, the hypothesis of a race between scale checks is correct.

**Comment by unterstein** [comment]
Sounds similar to https://github.com/mesosphere/marathon/commit/d097b5c41525fd689620c7c808476abe2abc3198

**Comment by jeschkies** [comment]
The scaling issue should definitely be fixed by https://github.com/mesosphere/marathon/commit/d097b5c41525fd689620c7c808476abe2abc3198.

**Comment by unterstein** [comment]
40 runs today: 0 failures.

I think https://github.com/mesosphere/marathon/commit/d097b5c41525fd689620c7c808476abe2abc3198 fixes this flaky tests.
