### ISSUE TITLE
ResidentTaskIntegrationTest "Scale Up" is unstable

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4848]
Marked here: f03285b20817909a1c08169436b26af5520c0a1b

Seen here: https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-loop-tests/1924/testReport/mesosphere.marathon.integration/ResidentTaskIntegrationTest/Scale_Up/

## Error Message

```
The code passed to eventually never returned normally. Attempted 5775 times over 1.5000559859166667 minutes. Last failure message: requirement failed: No events matched <event deployment_success to arrive>.
```

## Stacktrace

```
      org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 5775 times over 1.5000559859166667 minutes. Last failure message: requirement failed: No events matched <event deployment_success to arrive>.
      at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.eventually(ResidentTaskIntegrationTest.scala:21)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.eventually(ResidentTaskIntegrationTest.scala:21)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForEventMatching(MarathonTest.scala:478)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForEventMatching(ResidentTaskIntegrationTest.scala:21)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForEventWith(MarathonTest.scala:459)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForEventWith(ResidentTaskIntegrationTest.scala:21)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForDeploymentId(MarathonTest.scala:443)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForDeploymentId(ResidentTaskIntegrationTest.scala:21)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForDeployment(MarathonTest.scala:516)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForDeployment(ResidentTaskIntegrationTest.scala:21)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$Fixture.scaleToSuccessfully(ResidentTaskIntegrationTest.scala:327)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$6.apply(ResidentTaskIntegrationTest.scala:149)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$6.apply(ResidentTaskIntegrationTest.scala:144)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply$mcV$sp(ResidentTaskIntegrationTest.scala:255)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:255)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:255)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.FunTest.runTest(UnitTest.scala:99)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
      at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.FunTest.run(UnitTest.scala:99)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
      Cause: java.lang.IllegalArgumentException: requirement failed: No events matched <event deployment_success to arrive>
      at scala.Predef$.require(Predef.scala:224)
      at mesosphere.marathon.integration.setup.MarathonTest$$anonfun$waitForEventMatching$1.apply(MarathonTest.scala:479)
      at mesosphere.marathon.integration.setup.MarathonTest$$anonfun$waitForEventMatching$1.apply(MarathonTest.scala:478)
      at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
      at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.eventually(ResidentTaskIntegrationTest.scala:21)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.eventually(ResidentTaskIntegrationTest.scala:21)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForEventMatching(MarathonTest.scala:478)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForEventMatching(ResidentTaskIntegrationTest.scala:21)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForEventWith(MarathonTest.scala:459)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForEventWith(ResidentTaskIntegrationTest.scala:21)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForDeploymentId(MarathonTest.scala:443)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForDeploymentId(ResidentTaskIntegrationTest.scala:21)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForDeployment(MarathonTest.scala:516)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForDeployment(ResidentTaskIntegrationTest.scala:21)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$Fixture.scaleToSuccessfully(ResidentTaskIntegrationTest.scala:327)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$6.apply(ResidentTaskIntegrationTest.scala:149)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$6.apply(ResidentTaskIntegrationTest.scala:144)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply$mcV$sp(ResidentTaskIntegrationTest.scala:255)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:255)
      at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:255)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.FunTest.runTest(UnitTest.scala:99)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
      at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:99)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.FunTest.run(UnitTest.scala:99)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
```

**Comment by timcharper** [comment]
Marking as serial did not help

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2179. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2179. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
