### ISSUE TITLE
NetworkPartitionIntegrationTest is unstable

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4851]

**Comment by timcharper** [comment]
This appears to be an actual bug.

**Comment by jeschkies** [comment]
We've found that when the Marathon lost connection to Zookeeper and Mesos master it also looses leadership and never regains it even when Zookeeper and Mesos are running again.

Here is this code https://github.com/mesosphere/marathon/blob/master/src/test/scala/mesosphere/marathon/integration/NetworkPartitionIntegrationTest.scala#L52


```
   5713 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741] org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /marathon/leader-curator/_c_ab228197-7592-460
   5713 a-9ded-c9192e1e2ed0-latch-0000000000
   5714 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.zookeeper.KeeperException.create(KeeperException.java:115)
   5715 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
   5716 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1611)
   5717 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:310)
   5718 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:299)
   5719 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
   5720 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:296)
   5721 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:287)
   5722 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:34)
   5723 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.recipes.leader.LeaderSelector.participantForPath(LeaderSelector.java:375)
   5724 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.recipes.leader.LeaderSelector.getLeader(LeaderSelector.java:346)
   5725 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.recipes.leader.LeaderLatch.getLeader(LeaderLatch.java:454)
   5726 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at mesosphere.marathon.core.election.impl.CuratorElectionService$$anonfun$leaderHostPortImpl$1.apply(CuratorElectionService.
   5726 scala:43)
   5727 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at mesosphere.marathon.core.election.impl.CuratorElectionService$$anonfun$leaderHostPortImpl$1.apply(CuratorElectionService.
   5727 scala:42)
   5728 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at scala.Option.flatMap(Option.scala:171)
   5729 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at mesosphere.marathon.core.election.impl.CuratorElectionService.leaderHostPortImpl(CuratorElectionService.scala:42)
   5730 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at mesosphere.marathon.core.election.impl.ElectionServiceBase$$anonfun$leaderHostPort$1.liftedTree1$1(ElectionServiceBase.sc
   5730 ala:62)
   5731 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at mesosphere.marathon.core.election.impl.ElectionServiceBase$$anonfun$leaderHostPort$1.apply(ElectionServiceBase.scala:61)
   5732 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at mesosphere.marathon.core.election.impl.ElectionServiceBase$$anonfun$leaderHostPort$1.apply(ElectionServiceBase.scala:60)
   5733 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at mesosphere.marathon.metrics.Metrics$Timer.apply(Metrics.scala:105)
   5734 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at mesosphere.marathon.core.election.impl.ElectionServiceBase.leaderHostPort(ElectionServiceBase.scala:60)
   5735 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at mesosphere.marathon.core.election.impl.CuratorElectionService$Listener$.notLeader(CuratorElectionService.scala:74)
   5736 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.recipes.leader.LeaderLatch$8.apply(LeaderLatch.java:640)
   5737 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.recipes.leader.LeaderLatch$8.apply(LeaderLatch.java:636)
   5738 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
   5739 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   5740 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   5741 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741]     at java.lang.Thread.run(Thread.java:745)
   5742 DEBUG[18:34:01 NetworkPartitionIntegrationTest-LocalMarathon-57741] INFO [18:34:01 CuratorElectionService] Defeated (LeaderLatchListener Interface). New leader: -
```

**Comment by jdef** [comment]
Marathon should die now when it loses leadership. If/when Marathon is
restarted it normally "waits" for ZK to come up before attempting to
actually do anything (I think).

**Comment by jeschkies** [comment]
This is probably related to https://github.com/mesosphere/marathon/issues/4786.

**Comment by jeschkies** [comment]
The tests for this are actually commented out: https://github.com/mesosphere/marathon/blob/master/src/test/scala/mesosphere/marathon/integration/LeaderIntegrationTest.scala#L30

It seems Marathon does not suicide on connection loss. Why is that a behaviour we wish?

**Comment by jeschkies** [comment]
Might also be related to https://github.com/mesosphere/marathon/issues/3566

**Comment by jeschkies** [comment]
Sweet. Simulating Marathon's suicide and then restarting it fixes the integration test:
https://github.com/mesosphere/marathon/commit/59c59f83f92859ebba30a1790d822149ff9c6a24

**Comment by jeschkies** [comment]
Waiting for suicide with `eventually { marathonServer.isRunning should be (true) }` fails from time to time. See comments here https://phabricator.mesosphere.com/D351.

**Comment by jeschkies** [comment]
See branch for a solution https://github.com/mesosphere/marathon/tree/tharper/network-partition

**Comment by jeschkies** [comment]
Review https://phabricator.mesosphere.com/D391
