### ISSUE TITLE
AppDeployIntegrationTest "kill a task of an App" is Unstable

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4885]
Marked in cc82191e0fffff21b1d6b1c3380089513473affb

This failed even while the tests were marked as serial.

https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-test-marathon-phabricator/812/testReport/junit/mesosphere.marathon.integration/AppDeployIntegrationTest/kill_a_task_of_an_App/

# Error Message

```
The code passed to eventually never returned normally. Attempted 2361 times over 1.5002844022833333 minutes. Last failure message: requirement failed: Waiting for 1 tasks to be launched.
```

# Stacktrace

```
      org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 2361 times over 1.5002844022833333 minutes. Last failure message: requirement failed: Waiting for 1 tasks to be launched.
      at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
      at mesosphere.marathon.integration.AppDeployIntegrationTest.eventually(AppDeployIntegrationTest.scala:20)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)
      at mesosphere.marathon.integration.AppDeployIntegrationTest.eventually(AppDeployIntegrationTest.scala:20)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForTasks(MarathonTest.scala:380)
      at mesosphere.marathon.integration.AppDeployIntegrationTest.waitForTasks(AppDeployIntegrationTest.scala:20)
      at mesosphere.marathon.integration.AppDeployIntegrationTest$$anonfun$22.apply(AppDeployIntegrationTest.scala:438)
      at mesosphere.marathon.integration.AppDeployIntegrationTest$$anonfun$22.apply(AppDeployIntegrationTest.scala:423)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.FunTest.runTest(UnitTest.scala:107)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
      at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.FunTest.run(UnitTest.scala:107)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
      Cause: java.lang.IllegalArgumentException: requirement failed: Waiting for 1 tasks to be launched
      at scala.Predef$.require(Predef.scala:224)
      at mesosphere.marathon.integration.setup.MarathonTest$$anonfun$waitForTasks$1.apply(MarathonTest.scala:383)
      at mesosphere.marathon.integration.setup.MarathonTest$$anonfun$waitForTasks$1.apply(MarathonTest.scala:380)
      at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
      at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
      at mesosphere.marathon.integration.AppDeployIntegrationTest.eventually(AppDeployIntegrationTest.scala:20)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)
      at mesosphere.marathon.integration.AppDeployIntegrationTest.eventually(AppDeployIntegrationTest.scala:20)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForTasks(MarathonTest.scala:380)
      at mesosphere.marathon.integration.AppDeployIntegrationTest.waitForTasks(AppDeployIntegrationTest.scala:20)
      at mesosphere.marathon.integration.AppDeployIntegrationTest$$anonfun$22.apply(AppDeployIntegrationTest.scala:438)
      at mesosphere.marathon.integration.AppDeployIntegrationTest$$anonfun$22.apply(AppDeployIntegrationTest.scala:423)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.FunTest.runTest(UnitTest.scala:107)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
      at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.FunTest.run(UnitTest.scala:107)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
```

**Comment by jeschkies** [comment]
In review https://phabricator.mesosphere.com/D462
