### ISSUE TITLE
Shared integration test code appears to introduce low-probability failure in a wide spread of our tests

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4920]
https://jenkins.mesosphere.com/service/jenkins/job/public-test-marathon-phabricator/962/testReport/junit/mesosphere.marathon.integration/HealthDeploymentLeaderAbdicationIntegrationTest/deployment_with_1_healthy_and_1_unhealthy_instance_is_continued_properly_after_master_abdication/

# Error Message

```
The code passed to eventually never returned normally. Attempted 55 times over 1.5005619527833332 minutes. Last failure message: requirement failed: No events matched <event deployment_success to arrive>.
```

# Stacktrace

```
      org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 55 times over 1.5005619527833332 minutes. Last failure message: requirement failed: No events matched <event deployment_success to arrive>.
      at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
      at mesosphere.marathon.integration.LeaderIntegrationTest.eventually(LeaderIntegrationTest.scala:14)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)
      at mesosphere.marathon.integration.LeaderIntegrationTest.eventually(LeaderIntegrationTest.scala:14)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForEventMatching(MarathonTest.scala:478)
      at mesosphere.marathon.integration.LeaderIntegrationTest.waitForEventMatching(LeaderIntegrationTest.scala:14)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForEventWith(MarathonTest.scala:459)
      at mesosphere.marathon.integration.LeaderIntegrationTest.waitForEventWith(LeaderIntegrationTest.scala:14)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForDeploymentId(MarathonTest.scala:443)
      at mesosphere.marathon.integration.LeaderIntegrationTest.waitForDeploymentId(LeaderIntegrationTest.scala:14)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForDeployment(MarathonTest.scala:516)
      at mesosphere.marathon.integration.LeaderIntegrationTest.waitForDeployment(LeaderIntegrationTest.scala:14)
      at mesosphere.marathon.integration.DeploymentLeaderAbdicationIntegrationTest.test(DeploymentLeaderAbdicationIntegrationTest.scala:23)
      at mesosphere.marathon.integration.HealthDeploymentLeaderAbdicationIntegrationTest$$anonfun$2.apply(HealthDeploymentLeaderAbdicationIntegrationTest.scala:28)
      at mesosphere.marathon.integration.HealthDeploymentLeaderAbdicationIntegrationTest$$anonfun$2.apply(HealthDeploymentLeaderAbdicationIntegrationTest.scala:18)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.FunTest.runTest(UnitTest.scala:107)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
      at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.FunTest.run(UnitTest.scala:107)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
      Cause: java.lang.IllegalArgumentException: requirement failed: No events matched <event deployment_success to arrive>
      at scala.Predef$.require(Predef.scala:224)
      at mesosphere.marathon.integration.setup.MarathonTest$$anonfun$waitForEventMatching$1.apply(MarathonTest.scala:479)
      at mesosphere.marathon.integration.setup.MarathonTest$$anonfun$waitForEventMatching$1.apply(MarathonTest.scala:478)
      at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
      at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
      at mesosphere.marathon.integration.LeaderIntegrationTest.eventually(LeaderIntegrationTest.scala:14)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)
      at mesosphere.marathon.integration.LeaderIntegrationTest.eventually(LeaderIntegrationTest.scala:14)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForEventMatching(MarathonTest.scala:478)
      at mesosphere.marathon.integration.LeaderIntegrationTest.waitForEventMatching(LeaderIntegrationTest.scala:14)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForEventWith(MarathonTest.scala:459)
      at mesosphere.marathon.integration.LeaderIntegrationTest.waitForEventWith(LeaderIntegrationTest.scala:14)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForDeploymentId(MarathonTest.scala:443)
      at mesosphere.marathon.integration.LeaderIntegrationTest.waitForDeploymentId(LeaderIntegrationTest.scala:14)
      at mesosphere.marathon.integration.setup.MarathonTest$class.waitForDeployment(MarathonTest.scala:516)
      at mesosphere.marathon.integration.LeaderIntegrationTest.waitForDeployment(LeaderIntegrationTest.scala:14)
      at mesosphere.marathon.integration.DeploymentLeaderAbdicationIntegrationTest.test(DeploymentLeaderAbdicationIntegrationTest.scala:23)
      at mesosphere.marathon.integration.HealthDeploymentLeaderAbdicationIntegrationTest$$anonfun$2.apply(HealthDeploymentLeaderAbdicationIntegrationTest.scala:28)
      at mesosphere.marathon.integration.HealthDeploymentLeaderAbdicationIntegrationTest$$anonfun$2.apply(HealthDeploymentLeaderAbdicationIntegrationTest.scala:18)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.FunTest.runTest(UnitTest.scala:107)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
      at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.FunTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:107)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.FunTest.run(UnitTest.scala:107)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
```

**Comment by timcharper** [comment]
This test is not failing in the loop test; closing for now.

**Comment by timcharper** [comment]
Investigated and found the cause of this low-probability cause: timing issue. This underlying cause could explain other very-low probabilistic failures (when combined not so low) in the integration suite that we are seeing.

We try to launch 2 tasks in a simulated cluster with a single agent (and master).

A brief timeline:

` 0.0` secs - deployment starts
` 0.1` secs - we send revive
` 0.1` secs - we get an offer
` 0.2` secs - we send revive
` 0.3` secs - we send revive
` 1.2` secs - we receive response from the first task launcher actor; Marathon's self-imposed deadline exceeded. 
` 1.2` secs - we send the offer response with 1 operation rather than 2. Since an accept is also an implicit decline (or else you would use all resources on a machine), this causes the agent in question to hold on to it's resources.
`90.0` secs - at this point we still have not received another offer, and the test fails. We've launched one task, and still would like to launch another one.
`12x.x` secs or so - we would've been re-offered the remaining resources from the agent in the simulation cluster, and the deployment would've succeeded.

A few things would've made this test pass:

- If `TaskLauncherActor` responded in < 1.0 secs (I can't explain why other actors were clearly responding in a somewhat timely fashion, such as the revival actor, while the task launcher actor took so long; this appears to contradict a hypothesis that this occurred due to clusters of severe load)
- If we revives were scheduled 1s apart, rather than 100ms. (a revival would've occurred after the first timeout, and we would've gotten another chance to evaluate the offers)
- If Marathon's self-imposed deadline were longer.

**Comment by timcharper** [comment]
https://phabricator.mesosphere.com/D414

**Comment by marcomonaco** [comment]
Not sure, can we close that?
