### ISSUE TITLE
Test failed for sbt assembly

### ISSUE THREAD

**Issue by HackToday** [mesosphere/marathon#4922]
Step to reproduce:
1. git clone 
2. cd marathon
3. sbt assembly

Then the result is like following:
```
Run completed in 2 minutes, 39 seconds.
Total number of tests run: 2742
Suites: completed 240, aborted 0
Tests: succeeded 2738, failed 4, canceled 0, ignored 1, pending 2
*** 4 TESTS FAILED ***
AppStartActorTest:

- With Health Checks *** FAILED *** (36 milliseconds)
  org.mockito.exceptions.verification.WantedButNotInvoked: Wanted but not invoked:
schedulerActions.startRunSpec(
    AppDefinition(/app,None,List(),None,Map(),2,Resources(1.0,128.0,0.0,0),,Set(),List(),List(),List(PortDefinition(0,tcp,None,Map())),false,BackoffStrategy(1 second,1 hour,1.15),None,Set(MarathonHttpHealthCheck(5 minutes,1 minute,20 seconds,3,Some(ByIndex(0)),None,None,HTTP,false)),List(),None,Set(),UpgradeStrategy(1.0,1.0),Map(),Set(),None,OnlyVersion(2017-01-05T00:53:36.102Z),None,Map(),UnreachableStrategy(5 minutes,10 minutes),YoungestFirst)
);
-> at mesosphere.marathon.upgrade.AppStartActorTest$$anonfun$2.apply(AppStartActorTest.scala:58)
Actually, there were zero interactions with this mock.
  at mesosphere.marathon.upgrade.AppStartActorTest$$anonfun$2.apply(AppStartActorTest.scala:58)
  at mesosphere.marathon.upgrade.AppStartActorTest$$anonfun$2.apply(AppStartActorTest.scala:43)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at mesosphere.marathon.upgrade.AppStartActorTest.withFixture(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfter$$super$runTest(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.marathon.upgrade.AppStartActorTest.runTest(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at mesosphere.marathon.upgrade.AppStartActorTest.runTests(AppStartActorTest.scala:20)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$FunSuiteLike$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfter$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfterAll$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.marathon.upgrade.AppStartActorTest.run(AppStartActorTest.scala:20)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
AppStartActorTest:

- Failed *** FAILED *** (76 milliseconds)
  java.lang.AssertionError: assertion failed: expected: Terminated TestActor[akka://AppStartActorTest/user/$$qc] but got unexpected message Terminated(TestActor[akka://AppStartActorTest/user/$$pc])
  at scala.Predef$.assert(Predef.scala:170)
  at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:406)
  at mesosphere.marathon.upgrade.AppStartActorTest.expectMsgPF(AppStartActorTest.scala:20)
  at akka.testkit.TestKitBase$class.expectTerminated(TestKit.scala:417)
  at mesosphere.marathon.upgrade.AppStartActorTest.expectTerminated(AppStartActorTest.scala:20)
  at mesosphere.marathon.upgrade.AppStartActorTest$$anonfun$3.apply(AppStartActorTest.scala:79)
  at mesosphere.marathon.upgrade.AppStartActorTest$$anonfun$3.apply(AppStartActorTest.scala:62)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at mesosphere.marathon.upgrade.AppStartActorTest.withFixture(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfter$$super$runTest(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.marathon.upgrade.AppStartActorTest.runTest(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at mesosphere.marathon.upgrade.AppStartActorTest.runTests(AppStartActorTest.scala:20)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$FunSuiteLike$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfter$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfterAll$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.marathon.upgrade.AppStartActorTest.run(AppStartActorTest.scala:20)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
AppStartActorTest:

- No tasks to start without health checks *** FAILED *** (33 milliseconds)
  java.lang.AssertionError: assertion failed: expected: Terminated TestActor[akka://AppStartActorTest/user/$$rc] but got unexpected message Terminated(TestActor[akka://AppStartActorTest/user/$$qc])
  at scala.Predef$.assert(Predef.scala:170)
  at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:406)
  at mesosphere.marathon.upgrade.AppStartActorTest.expectMsgPF(AppStartActorTest.scala:20)
  at akka.testkit.TestKitBase$class.expectTerminated(TestKit.scala:417)
  at mesosphere.marathon.upgrade.AppStartActorTest.expectTerminated(AppStartActorTest.scala:20)
  at mesosphere.marathon.upgrade.AppStartActorTest$$anonfun$4.apply(AppStartActorTest.scala:92)
  at mesosphere.marathon.upgrade.AppStartActorTest$$anonfun$4.apply(AppStartActorTest.scala:82)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at mesosphere.marathon.upgrade.AppStartActorTest.withFixture(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfter$$super$runTest(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.marathon.upgrade.AppStartActorTest.runTest(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at mesosphere.marathon.upgrade.AppStartActorTest.runTests(AppStartActorTest.scala:20)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$FunSuiteLike$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfter$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfterAll$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.marathon.upgrade.AppStartActorTest.run(AppStartActorTest.scala:20)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
AppStartActorTest:

- No tasks to start with health checks *** FAILED *** (27 milliseconds)
  java.lang.AssertionError: assertion failed: expected: Terminated TestActor[akka://AppStartActorTest/user/$$sc] but got unexpected message Terminated(TestActor[akka://AppStartActorTest/user/$$rc])
  at scala.Predef$.assert(Predef.scala:170)
  at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:406)
  at mesosphere.marathon.upgrade.AppStartActorTest.expectMsgPF(AppStartActorTest.scala:20)
  at akka.testkit.TestKitBase$class.expectTerminated(TestKit.scala:417)
  at mesosphere.marathon.upgrade.AppStartActorTest.expectTerminated(AppStartActorTest.scala:20)
  at mesosphere.marathon.upgrade.AppStartActorTest$$anonfun$5.apply(AppStartActorTest.scala:108)
  at mesosphere.marathon.upgrade.AppStartActorTest$$anonfun$5.apply(AppStartActorTest.scala:95)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at mesosphere.marathon.upgrade.AppStartActorTest.withFixture(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfter$$super$runTest(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.marathon.upgrade.AppStartActorTest.runTest(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at mesosphere.marathon.upgrade.AppStartActorTest.runTests(AppStartActorTest.scala:20)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$FunSuiteLike$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfter$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.marathon.upgrade.AppStartActorTest.org$scalatest$BeforeAndAfterAll$$super$run(AppStartActorTest.scala:20)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.marathon.upgrade.AppStartActorTest.run(AppStartActorTest.scala:20)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[info] ScalaTest

```

It seems this failed test which cause final jar failed. As when I run

```
$ ./bin/build-distribution 
Concatenating
  bin/marathon-framework
  target/scala-2.11/marathon-assembly-*.jar
to form
  target/marathon-runnable.jar
shasum: target/scala-2.11/marathon-assembly-*.jar: 
cat: 'target/scala-2.11/marathon-assembly-*.jar': No such file or directory

```

**Comment by aquamatthias** [comment]
@HackToday Thanks for reporting this. We marked the test unstable and created a ticket to fix it: #4921

**Comment by HackToday** [comment]
Hi @aquamatthias  after  use latest which was fixed in https://github.com/mesosphere/marathon/commit/affe91aa4eb90d2228ddc772bd94f97b63a3b1b1


still found one failed with 

```
Tests: succeeded 2742, failed 1, canceled 0, ignored 1, pending 2
*** 1 TEST FAILED ***
MarathonSchedulerActorTest:

- Restart deployments after failover *** FAILED *** (31 milliseconds)
  java.lang.AssertionError: assertion failed: expected class mesosphere.marathon.MarathonSchedulerActor$CommandFailed, found class mesosphere.marathon.MarathonSchedulerActor$DeploymentStarted (DeploymentStarted(DeploymentPlan id=1f970f2e-215d-4859-83d3-bd7d62bda0fe,2017-01-10T00:29:53.655Z
step 1:
  * Start(App(app1, cmd="cmd"List())), instances=0)
step 2:
  * Scale(App(app1, cmd="cmd"List())), instances=2)
))
  at scala.Predef$.assert(Predef.scala:170)
  at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:473)
  at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:445)
  at mesosphere.marathon.MarathonSchedulerActorTest.expectMsgType(MarathonSchedulerActorTest.scala:37)
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$16.apply(MarathonSchedulerActorTest.scala:459)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at mesosphere.marathon.MarathonSchedulerActorTest.withFixture(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$runTest(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.marathon.MarathonSchedulerActorTest.runTest(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at mesosphere.marathon.MarathonSchedulerActorTest.runTests(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$FunSuiteLike$$super$run(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$run(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfterAll$$super$run(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.marathon.MarathonSchedulerActorTest.run(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[info] ScalaTest
[info] Run completed in 2 minutes, 58 seconds.
[info] Total number of tests run: 2743
[info] Suites: completed 239, aborted 0
[info] Tests: succeeded 2742, failed 1, canceled 0, ignored 1, pending 2
[info] *** 1 TEST FAILED ***

```

**Comment by HackToday** [comment]
Please help take a look at the failed test. Thanks
