### ISSUE TITLE
Integration Test Succeed but Process fails with 137

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#4929]
See this build: https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/pipelines%252Fkarsten/30/console

```
INFO [07:45:08 MarathonApp] Waiting for services to shut down
Exception in thread "Thread-13" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2626)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1321)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:809)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:798)
	at java.lang.Thread.run(Thread.java:745)
[36mRun completed in 6 minutes, 7 seconds.[0m
[36mTotal number of tests run: 29[0m
[36mSuites: completed 129, aborted 0[0m
[36mTests: succeeded 29, failed 0, canceled 0, ignored 0, pending 0[0m
[32mAll tests passed.[0m
[info] ScalaTest
[info] Run completed in 6 minutes, 7 seconds.
[info] Total number of tests run: 29
[info] Suites: completed 129, aborted 0
[info] Tests: succeeded 29, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error] 	Running java with options -classpath ... sbt.ForkMain 14559 failed with exit code 137
```

I think we have a similar issue somewhere.

**Comment by jeschkies** [comment]
https://phabricator.mesosphere.com/D404
