### ISSUE TITLE
MarathonSchedulerActorTest is Unstable

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4933]
See: 
https://github.com/mesosphere/marathon/issues/4922#issuecomment-271526081

```
Tests: succeeded 2742, failed 1, canceled 0, ignored 1, pending 2
*** 1 TEST FAILED ***
MarathonSchedulerActorTest:

- Restart deployments after failover *** FAILED *** (31 milliseconds)
  java.lang.AssertionError: assertion failed: expected class mesosphere.marathon.MarathonSchedulerActor$CommandFailed, found class mesosphere.marathon.MarathonSchedulerActor$DeploymentStarted (DeploymentStarted(DeploymentPlan id=1f970f2e-215d-4859-83d3-bd7d62bda0fe,2017-01-10T00:29:53.655Z
step 1:
  * Start(App(app1, cmd="cmd"List())), instances=0)
step 2:
  * Scale(App(app1, cmd="cmd"List())), instances=2)
))
  at scala.Predef$.assert(Predef.scala:170)
  at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:473)
  at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:445)
  at mesosphere.marathon.MarathonSchedulerActorTest.expectMsgType(MarathonSchedulerActorTest.scala:37)
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$16.apply(MarathonSchedulerActorTest.scala:459)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at mesosphere.marathon.MarathonSchedulerActorTest.withFixture(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$runTest(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.marathon.MarathonSchedulerActorTest.runTest(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at mesosphere.marathon.MarathonSchedulerActorTest.runTests(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$FunSuiteLike$$super$run(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$run(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfterAll$$super$run(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.marathon.MarathonSchedulerActorTest.run(MarathonSchedulerActorTest.scala:37)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[info] ScalaTest
[info] Run completed in 2 minutes, 58 seconds.
[info] Total number of tests run: 2743
[info] Suites: completed 239, aborted 0
[info] Tests: succeeded 2742, failed 1, canceled 0, ignored 1, pending 2
[info] *** 1 TEST FAILED ***

```

**Comment by HackToday** [comment]
Looking forward this fix, BTW. how can build the jars while ignoring the sbt failed test ?  I want to build jars. but always blocked by failed sbt test.  Thanks

**Comment by timcharper** [comment]
A possible workaround is to just delete the test that is failing.

**Comment by HackToday** [comment]
@aquamatthias  Just pull latest code, still have test failed

```
nated(Actor[akka://default/user]),Actor[akka://default/user])
[DEBUG] [01/22/2017 08:44:35.325] [default-akka.actor.default-dispatcher-7] [EventStream] shutting down: StandardOutLogger started
Run completed in 2 minutes, 44 seconds.
Total number of tests run: 2758
Suites: completed 239, aborted 0
Tests: succeeded 2757, failed 1, canceled 0, ignored 1, pending 2
*** 1 TEST FAILED ***
MarathonSchedulerActorTest:

- Restart deployments after failover *** FAILED *** (28 milliseconds)
  java.lang.AssertionError: assertion failed: expected class mesosphere.marathon.MarathonSchedulerActor$CommandFailed, found class mesosphere.marathon.MarathonSchedulerActor$DeploymentStarted (DeploymentStarted(DeploymentPlan id=f91ef6f1-5227-4889-840c-d77c575beee6,2017-01-22T00:44:08.152Z
step 1:
  * Start(App(app1, cmd="cmd"List())), instances=0)
step 2:
  * Scale(App(app1, cmd="cmd"List())), instances=2)
))
  at scala.Predef$.assert(Predef.scala:170)
  at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:473)
  at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:445)
  at mesosphere.marathon.MarathonSchedulerActorTest.expectMsgType(MarathonSchedulerActorTest.scala:38)
  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$18.apply(MarathonSchedulerActorTest.scala:450)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at mesosphere.marathon.MarathonSchedulerActorTest.withFixture(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$runTest(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.marathon.MarathonSchedulerActorTest.runTest(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at mesosphere.marathon.MarathonSchedulerActorTest.runTests(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$FunSuiteLike$$super$run(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$run(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfterAll$$super$run(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.marathon.MarathonSchedulerActorTest.run(MarathonSchedulerActorTest.scala:38)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[info] ScalaTest
[info] Run completed in 2 minutes, 44 seconds.
[info] Total number of tests run: 2758
[info] Suites: completed 239, aborted 0
[info] Tests: succeeded 2757, failed 1, canceled 0, ignored 1, pending 2
[info] *** 1 TEST FAILED ***
[error] Failed: Total 2758, Failed 1, Errors 0, Passed 2757, Ignored 1, Pending 2
[error] Failed tests:
[error] 	mesosphere.marathon.MarathonSchedulerActorTest
[error] (marathon/test:test) sbt.TestsFailedException: Tests unsuccessful

```

**Comment by zen-dog** [comment]
@HackToday Interesting, I can't make it fail locally. Could you pls attach the complete log?
