### ISSUE TITLE
Jenkins Pipeline timeout does not work for deadlocked jobs

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5036]
https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-marathon-unstable/ has a timeout configured but it did not help to prevent the master being filled with logs.

**Comment by timcharper** [comment]
Remember those times when you type `cat logfile` and it outputs a TON. You realize your mistake and try and hit `ctrl-c` only to have it seemingly ignored until the `cat logfile` is done?

This feels like that.

**Comment by timcharper** [comment]
Related: https://github.com/mesosphere/marathon/issues/5033

**Comment by jeschkies** [comment]
We should tackle this soon. Otherwise we won't be able to run jobs in a loop.

**Comment by jeschkies** [comment]
It seems the curator framework end up in an endless deadlock here https://github.com/apache/curator/blob/master/curator-framework/src/main/java/org/apache/curator/framework/imps/FailedDeleteManager.java#L43. We don't have the start of the stack trace which is odd.

**Comment by jeschkies** [comment]
The code checks for Thread interruptions so I'm wondering why it does not receive an interrupt.

**Comment by jeschkies** [comment]
We also never close the Curator client for our storage. This means its state will always be `CuratorFrameworkState.STARTED`. Thus it would always retry to connect.

**Comment by jeschkies** [comment]
We've finally got the beginning of the stack trace: [deadlock.log.gz](https://github.com/mesosphere/marathon/files/755263/deadlock.log.gz)

It starts at roughly line 34389.

**Comment by jeschkies** [comment]
Ok, it's probably the leader election:

```
34907 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956] ERROR[15:26:04 ConnectionState] Connection timed out for connection string (127.0.0.1:55819) and timeout (2000) / elapsed (2164)
  34908 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956] org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
  34909 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:200)
  34910 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:90)
  34911 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
  34912 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835)
  34913 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:507)
  34914 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:221)
  34915 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
  34916 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.FailedDeleteManager.addFailedDelete(FailedDeleteManager.java:55)
  34917 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl$4.retriesExhausted(DeleteBuilderImpl.java:217)
  34918 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:716)
  34919 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
  34920 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:507)
  34921 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:221)
  34922 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
  34923 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.FailedDeleteManager.addFailedDelete(FailedDeleteManager.java:55)
  34924 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl$4.retriesExhausted(DeleteBuilderImpl.java:217)
  34925 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:716)
  34926 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
  34927 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:507)
  34928 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:221)
  34929 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
  34930 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.FailedDeleteManager.addFailedDelete(FailedDeleteManager.java:55)
  34931 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl$4.retriesExhausted(DeleteBuilderImpl.java:217)
  34932 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:716)
  34933 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
  34934 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:507)
  34935 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:221)
  34936 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
  34937 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.FailedDeleteManager.addFailedDelete(FailedDeleteManager.java:55)
  34938 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl$4.retriesExhausted(DeleteBuilderImpl.java:217)
  34939 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:716)
  34940 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
  34941 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:507)
  34942 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:221)
  34943 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
  34944 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.FailedDeleteManager.addFailedDelete(FailedDeleteManager.java:55)
  34945 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl$4.retriesExhausted(DeleteBuilderImpl.java:217)
  34946 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:716)
  34947 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
  34948 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:507)
  34949 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:221)
  34950 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
  34951 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.FailedDeleteManager.addFailedDelete(FailedDeleteManager.java:55)
  34952 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl$4.retriesExhausted(DeleteBuilderImpl.java:217)
  34953 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:716)
  34954 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:857)
  34955 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:507)
  34956 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:221)
  34957 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
  34958 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.recipes.leader.LeaderLatch.setNode(LeaderLatch.java:666)
  34959 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.recipes.leader.LeaderLatch.close(LeaderLatch.java:209)
  34960 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.recipes.leader.LeaderLatch.close(LeaderLatch.java:189)
  34961 DEBUG[15:26:04 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.core.election.impl.CuratorElectionService.mesosphere$marathon$core$election$impl$CuratorElectionService$$onAbdicate(CuratorElectionService.scala:107)
```

The stack trace grows with each time.

**Comment by jeschkies** [comment]
Here is the bottom of these stack traces

```
  35649 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at org.apache.curator.framework.recipes.leader.LeaderLatch.close(LeaderLatch.java:189)
  35650 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.core.election.impl.CuratorElectionService.mesosphere$marathon$core$election$impl$CuratorElectionService$$onAbdicate(CuratorElectionService.scala:107)
  35651 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.core.election.impl.CuratorElectionService$Listener$$anonfun$isLeader$1$$anonfun$apply$mcV$sp$2.apply(CuratorElectionService.scala:98)
  35652 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.core.election.impl.CuratorElectionService$Listener$$anonfun$isLeader$1$$anonfun$apply$mcV$sp$2.apply(CuratorElectionService.scala:98)
  35653 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.core.election.impl.ElectionServiceBase.mesosphere$marathon$core$election$impl$ElectionServiceBase$$backoffAbdicate$1(ElectionServiceBase.scala:182)
  35654 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.core.election.impl.ElectionServiceBase$$anonfun$startLeadership$1.apply(ElectionServiceBase.scala:192)
  35655 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.core.election.impl.ElectionServiceBase$$anonfun$startLeadership$1.apply(ElectionServiceBase.scala:192)
  35656 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.core.election.impl.ElectionServiceBase.abdicateLeadership(ElectionServiceBase.scala:83)
  35657 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonSchedulerService.triggerShutdown(MarathonSchedulerService.scala:175)
  35658 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$ca1854b0.CGLIB$triggerShutdown$19(<generated>)
  35659 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$ca1854b0$$FastClassByGuice$$6c1173d9.invoke(<generated>)
  35660 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
  35661 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
  35662 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:82)
  35663 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:28)
  35664 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:82)
  35665 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
  35666 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
  35667 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$ca1854b0.triggerShutdown(<generated>)
  35668 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at com.google.common.util.concurrent.AbstractExecutionThreadService$1.doStop(AbstractExecutionThreadService.java:86)
  35669 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:232)
  35670 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at com.google.common.util.concurrent.AbstractExecutionThreadService.stopAsync(AbstractExecutionThreadService.java:195)
  35671 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at com.google.common.util.concurrent.ServiceManager.stopAsync(ServiceManager.java:325)
  35672 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonApp$$anonfun$shutdown$1.apply(Main.scala:100)
  35673 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonApp$$anonfun$shutdown$1.apply(Main.scala:100)
  35674 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at scala.Option.foreach(Option.scala:257)
  35675 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonApp.shutdown(Main.scala:100)
  35676 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonApp$$anonfun$shutdownAndWait$1.apply(Main.scala:105)
  35677 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonApp$$anonfun$shutdownAndWait$1.apply(Main.scala:104)
  35678 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at scala.Option.foreach(Option.scala:257)
  35679 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonApp.shutdownAndWait(Main.scala:104)
  35680 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at mesosphere.marathon.MarathonApp$$anonfun$start$1.apply$mcV$sp(Main.scala:81)
  35681 DEBUG[15:26:05 NetworkPartitionIntegrationTest-LocalMarathon-24956]     at scala.sys.ShutdownHookThread$$anon$1.run(ShutdownHookThread.scala:34)
```

I wonder what retriggers the shutdown.

**Comment by jeschkies** [comment]
The first delete starts in [LeaderLatch.setNode](https://github.com/apache/curator/blob/022de3921a120c6f86cc6e21442327cc04b66cd2/curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java#L666).

**Comment by jeschkies** [comment]
We probably enter the loop in the retry policy defined in [CuratorElectionService.provideCuratorClient](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/core/election/impl/CuratorElectionService.scala#L143).

Here is an example

```
2783192-DEBUG[15:26:35 NetworkPartitionIntegrationTest-LocalMarathon-24956] 	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:221)
2783193-DEBUG[15:26:35 NetworkPartitionIntegrationTest-LocalMarathon-24956] 	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35)
2783194-DEBUG[15:26:35 NetworkPartitionIntegrationTest-LocalMarathon-24956] 	at org.apache.curator.framework.imps.FailedDeleteManager.addFailedDelete(FailedDeleteManager.java:55)
2783195-DEBUG[15:26:35 NetworkPartitionIntegrationTest-LocalMarathon-24956] 	at org.apache.curator.framework.imps.DeleteBuilderImpl$4.retriesExhausted(DeleteBuilderImpl.java:217)
2783196:DEBUG[15:26:35 NetworkPartitionIntegrationTest-LocalMarathon-24956] ERROR[15:26:35 CuratorElectionService] ZooKeeper access failed - Committing suicide to avoid invalidating ZooKeeper state
2783197-DEBUG[15:26:35 NetworkPartitionIntegrationTest-LocalMarathon-24956] ERROR[15:26:35 CuratorFrameworkImpl] Background operation retry gave up
2783198-DEBUG[15:26:35 NetworkPartitionIntegrationTest-LocalMarathon-24956] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
2783199-DEBUG[15:26:35 NetworkPartitionIntegrationTest-LocalMarathon-24956] 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
2783200-DEBUG[15:26:35 NetworkPartitionIntegrationTest-LocalMarathon-24956] 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:728)
```

**Comment by jeschkies** [comment]
It seems now we enter this cycle:

1. An exit is issued.
2. `CuratorElectionService` tries to close its leader latch.
3. This fails probably because the ZooKeeper server is gone.
4. The retry policy issues another exit call which brings us back to 1.

**Comment by jeschkies** [comment]
I can force a similar effect by killing the ZooKeeper service in `ReelectionLeaderIntegrationTest` before deleting the leader

```scala
val client = leadingProcess.client

zkServer.close() // Trigger error

When("calling DELETE /v2/leader")
val result = client.abdicate()
```

The test does not deadlock because we throw `java.lang.InterruptedException: sleep interrupted` at some point.

**Comment by jeschkies** [comment]
In review [D491](https://phabricator.mesosphere.com/D491)

**Comment by jeschkies** [comment]
https://github.com/mesosphere/marathon/commit/bbc208e5c357cf6977ca9dbd8d9d3b8e363bb44d did not fix this issue :/.

**Comment by jeschkies** [comment]
Ok, I've came close to a solution. Please see changes in [karsten/stop-leadership-on-connection-lost](https://github.com/mesosphere/marathon/tree/karsten/stop-leadership-on-connection-lost).

The fix makes `NetworkPartitionIntegrationTest` flaky. Here is a log dump with DEBUG level
[failing_NetworkPartitionIntegrationTest.log.gz](https://github.com/mesosphere/marathon/files/761120/failing_NetworkPartitionIntegrationTest.log.gz)

As far as I can tell the ZooKeeper client tries to reconnect in an infinite loop. There is probably a race condition in `leaderHostPortImpl`. As soon as the leader latch is called we trigger a reconnect. Very strange. At least that's my assumption.

It would help a lot to refactor the election service into a FSM (e.g. http://doc.akka.io/docs/akka/current/scala/fsm.html) and just remove the latch on connection loss. We cannot do so right now because it's not thread safe.

**Comment by jeschkies** [comment]
At least I can trigger the error 50% of the times in a loop run of the `NetworkPartitionIntegrationTest `.

**Comment by jasongilanfarr** [comment]
I think I have an idea of how to fix this.

**Comment by jeschkies** [comment]
@jasongilanfarr do you mean [D499](https://phabricator.mesosphere.com/D499)?

I like that solution. However, I think we should tackle it at multiple levels. My branch hopefully has a fix that avoids being stuck in the first place. Luckily `NetworkPartitionIntegrationTest` seems to reproduce the issue.

**Comment by jeschkies** [comment]
The `CuratorElectionSerivce` should be refactored. See discussion in https://github.com/mesosphere/marathon/issues/4908.

**Comment by jeschkies** [comment]
Final patch is in review [D504](https://phabricator.mesosphere.com/D504).
