### ISSUE TITLE
TaskUnreachableIntegrationTest.scaling down an app with constraints and unreachable task fails

### ISSUE THREAD

**Issue by zen-dog** [mesosphere/marathon#5042]
See this build: https://jenkins.mesosphere.com/service/jenkins/job/public-test-marathon-phabricator/1124/
```
scaling down an app with constraints and unreachable task will succeed *** FAILED *** (7 seconds, 266 milliseconds)
  "TASK_[UNREACHABLE]" was not equal to "TASK_[RUNNING]",
  inside List(ITEnrichedTask(/regression,regression.e67d8af8-e717-11e6-89a0-02424f4c4c02,0,Some(List(31658)),Some(List(IpAddress(List(),Map(),DiscoveryInfo(List()),None))),Some(Mon Jan 30 00:00:00 UTC 2017),Some(Mon Jan 30 00:00:00 UTC 2017),TASK_UNREACHABLE,Some(2017-01-30T18:14:11.671Z))) (TaskUnreachableIntegrationTest.scala:123)
  org.scalatest.exceptions.TestFailedException:
  at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
  at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
  at mesosphere.marathon.integration.TaskUnreachableIntegrationTest$$anonfun$4$$anonfun$apply$2.applyOrElse(TaskUnreachableIntegrationTest.scala:123)
  at mesosphere.marathon.integration.TaskUnreachableIntegrationTest$$anonfun$4$$anonfun$apply$2.applyOrElse(TaskUnreachableIntegrationTest.scala:121)
  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
  at org.scalatest.Inside$class.inside(Inside.scala:128)
  at mesosphere.marathon.integration.TaskUnreachableIntegrationTest.inside(TaskUnreachableIntegrationTest.scala:15)
  at mesosphere.marathon.integration.TaskUnreachableIntegrationTest$$anonfun$4.apply(TaskUnreachableIntegrationTest.scala:121)
  at mesosphere.marathon.integration.TaskUnreachableIntegrationTest$$anonfun$4.apply(TaskUnreachableIntegrationTest.scala:81)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:107)
  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
  at mesosphere.FunTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:107)
  at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
  at mesosphere.FunTest.runTest(UnitTest.scala:107)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at mesosphere.FunTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:107)
  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
  at mesosphere.FunTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:107)
  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
  at mesosphere.FunTest.run(UnitTest.scala:107)
  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
  at sbt.ForkMain$Run$2.call(ForkMain.java:296)
  at sbt.ForkMain$Run$2.call(ForkMain.java:286)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by aquamatthias** [comment]
See https://phabricator.mesosphere.com/D484
Close for now to see if this already solves the problem.
