### ISSUE TITLE
Build from source failed with java.lang.AssertionError: assertion failed

### ISSUE THREAD

**Issue by HackToday** [mesosphere/marathon#5091]
[debug] Load.resolveProject(plugin-interface): expandSettings(...): settings(ArrayBuffer()) took 0.002297 ms
[debug] Load.resolveProject(plugin-interface): expandSettings(...) took 7.968188 ms
[debug] Load.resolveProject(plugin-interface) took 8.210009 ms
[debug] [Loading] Done in /home/kennan/marathon, returning: (marathon, benchmark, mesos-simulation, plugin-interface)
[debug] Load.loadUnit: loadedProjectsRaw took 1779.490757 ms
[debug] Load.loadUnit: cleanEvalClasses took 8.122408 ms
[debug] Load.loadUnit(file:/home/kennan/marathon/, ...) took 11194.501776 ms
[debug] Load.apply: load took 11225.015134 ms
[debug] Load.apply: resolveProjects took 3.217457 ms
[debug] Load.apply: finalTransforms took 223.107434 ms
[debug] Load.apply: config.delegates took 43.598817 ms
java.lang.AssertionError: assertion failed: Limit must be at least 1.
	at scala.Predef$.assert(Predef.scala:179)
	at sbt.Tags$.sbt$Tags$$checkMax(Tags.scala:56)
	at sbt.Tags$Single.<init>(Tags.scala:37)
	at sbt.Tags$.limit(Tags.scala:86)
	at sbt.Tags$.limitAll(Tags.scala:80)
	at $561038ba0164fed256ec$$anonfun$commonSettings$34.apply(build.sbt:161)
	at $561038ba0164fed256ec$$anonfun$commonSettings$34.apply(build.sbt:161)
	at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:609)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.AssertionError: assertion failed: Limit must be at least 1.
[error] Use 'last' for the full log.
[debug] > load-failed
[debug] > last

**Comment by HackToday** [comment]
How to reproduce:

1. clone latest code
2. run assembly

**Comment by HackToday** [comment]
@aquamatthias  did you know such issue ?

**Comment by aquamatthias** [comment]
@HackToday Thanks for reporting this. Marathon runs the integration tests in parallel - with a concurrency level of `availableProcessors/2`. On systems with one processor this leads to a wrong setup. Patch is here: https://phabricator.mesosphere.com/D482

**Comment by HackToday** [comment]
Thanks, works now
