### ISSUE TITLE
HealthCheckActor throws NullPointerException in tests

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5092]
See https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-test-marathon-phabricator/1175

```
INFO [09:46:55 HealthCheckActorTest$Fixture$$anonfun$actorWithLatch$1$$anon$1] Restarting health check actor for app [/test] version [2017-02-03T08:34:58.577Z] and healthCheck [MarathonHttpHealthCheck(5 minutes,1 minute,20 seconds,3,Some(ByIndex(0)),None,None,HTTP,false)]
INFO [09:46:55 HealthCheckActorTest$Fixture$$anonfun$actorWithLatch$1$$anon$1] Starting health check actor for app [/test] version [2017-02-03T08:34:58.577Z] and healthCheck [MarathonHttpHealthCheck(5 minutes,1 minute,20 seconds,3,Some(ByIndex(0)),None,None,HTTP,false)]
ERROR[09:46:55 OneForOneStrategy] null
java.lang.NullPointerException: null
	at mesosphere.marathon.core.health.impl.HealthCheckActor.updateInstances(HealthCheckActor.scala:63)
	at mesosphere.marathon.core.health.impl.HealthCheckActor$$anonfun$receive$1.applyOrElse(HealthCheckActor.scala:213)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
	at mesosphere.marathon.core.health.impl.HealthCheckActor.aroundReceive(HealthCheckActor.scala:17)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.testkit.CallingThreadDispatcher.process$1(CallingThreadDispatcher.scala:250)
	at akka.testkit.CallingThreadDispatcher.runQueue(CallingThreadDispatcher.scala:283)
	at akka.testkit.CallingThreadDispatcher.dispatch(CallingThreadDispatcher.scala:207)
	at akka.actor.dungeon.Dispatch$class.sendMessage(Dispatch.scala:144)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:374)
	at akka.actor.Cell$class.sendMessage(ActorCell.scala:295)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:374)
	at akka.actor.LocalActorRef.$bang(ActorRef.scala:406)
	at mesosphere.marathon.core.health.impl.HealthCheckActor$$anonfun$scheduleNextHealthCheck$1.apply$mcV$sp(HealthCheckActor.scala:92)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.testkit.CallingThreadDispatcher.executeTask(CallingThreadDispatcher.scala:212)
	at akka.dispatch.MessageDispatcher.unbatchedExecute(AbstractDispatcher.scala:145)
	at akka.dispatch.BatchingExecutor$class.execute(BatchingExecutor.scala:123)
	at akka.dispatch.MessageDispatcher.execute(AbstractDispatcher.scala:85)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236)
	at java.lang.Thread.run(Thread.java:745)
INFO [09:46:55 HealthCheckActor] Restarting health check actor for app [/test] version [2017-02-03T08:34:58.766Z] and healthCheck [MarathonHttpHealthCheck(5 minutes,1 minute,20 seconds,3,Some(ByIndex(0)),None,None,HTTP,false)]
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4782. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
