### ISSUE TITLE
NetworkPartitionIntegrationTest is unstable

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5185]
https://jenkins.mesosphere.com/service/jenkins/job/public-test-marathon-phabricator/1393/

# Error Message

```
The code passed to eventually never returned normally. Attempted 46 times over 50.99773594300001 seconds. Last failure message: true was not false.
```

# Stacktrace

```
      org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 46 times over 50.99773594300001 seconds. Last failure message: true was not false.
      at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
      at mesosphere.marathon.integration.NetworkPartitionIntegrationTest.eventually(NetworkPartitionIntegrationTest.scala:20)
      at mesosphere.marathon.integration.NetworkPartitionIntegrationTest$$anonfun$2$$anonfun$apply$mcV$sp$3.apply(NetworkPartitionIntegrationTest.scala:71)
      at mesosphere.marathon.integration.NetworkPartitionIntegrationTest$$anonfun$2$$anonfun$apply$mcV$sp$3.apply(NetworkPartitionIntegrationTest.scala:47)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.IntegrationTest.runTest(UnitTest.scala:86)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
      at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.IntegrationTest.run(UnitTest.scala:86)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
      Cause: org.scalatest.exceptions.TestFailedException: true was not false
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
      at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
      at mesosphere.marathon.integration.NetworkPartitionIntegrationTest$$anonfun$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$1.apply(NetworkPartitionIntegrationTest.scala:72)
      at mesosphere.marathon.integration.NetworkPartitionIntegrationTest$$anonfun$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$1.apply(NetworkPartitionIntegrationTest.scala:72)
      at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
      at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
      at mesosphere.marathon.integration.NetworkPartitionIntegrationTest.eventually(NetworkPartitionIntegrationTest.scala:20)
      at mesosphere.marathon.integration.NetworkPartitionIntegrationTest$$anonfun$2$$anonfun$apply$mcV$sp$3.apply(NetworkPartitionIntegrationTest.scala:71)
      at mesosphere.marathon.integration.NetworkPartitionIntegrationTest$$anonfun$2$$anonfun$apply$mcV$sp$3.apply(NetworkPartitionIntegrationTest.scala:47)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.IntegrationTest.runTest(UnitTest.scala:86)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
      at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.IntegrationTest.run(UnitTest.scala:86)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
```

**Comment by timcharper** [comment]
https://phabricator.mesosphere.com/D522

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2128. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
