### ISSUE TITLE
ReelectionLeaderIntegrationTest is unstable

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5187]
https://jenkins.mesosphere.com/service/jenkins/job/public-test-marathon-phabricator/1394/testReport/junit/mesosphere.marathon.integration/ReelectionLeaderIntegrationTest/Reelecting_a_leader_should_it_survives_a_small_reelection_test/

# Error Message

```
The code passed to eventually never returned normally. Attempted 155 times over 30.018360277 seconds. Last failure message: the former leading marathon process dies not satisfied.
```

# Stacktrace

```
      org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 155 times over 30.018360277 seconds. Last failure message: the former leading marathon process dies not satisfied.
      at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
      at mesosphere.marathon.integration.setup.WaitTestSupport$.eventually(WaitTestSupport.scala:12)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)
      at mesosphere.marathon.integration.setup.WaitTestSupport$.eventually(WaitTestSupport.scala:12)
      at mesosphere.marathon.integration.setup.WaitTestSupport$.waitUntil(WaitTestSupport.scala:26)
      at mesosphere.marathon.integration.ReelectionLeaderIntegrationTest$$anonfun$3$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$9.apply(LeaderIntegrationTest.scala:131)
      at mesosphere.marathon.integration.ReelectionLeaderIntegrationTest$$anonfun$3$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$9.apply(LeaderIntegrationTest.scala:114)
      at scala.collection.immutable.Range.foreach(Range.scala:160)
      at mesosphere.marathon.integration.ReelectionLeaderIntegrationTest$$anonfun$3$$anonfun$apply$mcV$sp$6.apply$mcV$sp(LeaderIntegrationTest.scala:114)
      at mesosphere.marathon.integration.ReelectionLeaderIntegrationTest$$anonfun$3$$anonfun$apply$mcV$sp$6.apply(LeaderIntegrationTest.scala:114)
      at mesosphere.marathon.integration.ReelectionLeaderIntegrationTest$$anonfun$3$$anonfun$apply$mcV$sp$6.apply(LeaderIntegrationTest.scala:114)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.IntegrationTest.runTest(UnitTest.scala:86)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
      at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.IntegrationTest.run(UnitTest.scala:86)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
      Cause: java.lang.RuntimeException: the former leading marathon process dies not satisfied
      at mesosphere.marathon.integration.setup.WaitTestSupport$$anonfun$waitUntil$1.apply$mcV$sp(WaitTestSupport.scala:27)
      at mesosphere.marathon.integration.setup.WaitTestSupport$$anonfun$waitUntil$1.apply(WaitTestSupport.scala:27)
      at mesosphere.marathon.integration.setup.WaitTestSupport$$anonfun$waitUntil$1.apply(WaitTestSupport.scala:27)
      at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)
      at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
      at mesosphere.marathon.integration.setup.WaitTestSupport$.eventually(WaitTestSupport.scala:12)
      at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)
      at mesosphere.marathon.integration.setup.WaitTestSupport$.eventually(WaitTestSupport.scala:12)
      at mesosphere.marathon.integration.setup.WaitTestSupport$.waitUntil(WaitTestSupport.scala:26)
      at mesosphere.marathon.integration.ReelectionLeaderIntegrationTest$$anonfun$3$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$9.apply(LeaderIntegrationTest.scala:131)
      at mesosphere.marathon.integration.ReelectionLeaderIntegrationTest$$anonfun$3$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$9.apply(LeaderIntegrationTest.scala:114)
      at scala.collection.immutable.Range.foreach(Range.scala:160)
      at mesosphere.marathon.integration.ReelectionLeaderIntegrationTest$$anonfun$3$$anonfun$apply$mcV$sp$6.apply$mcV$sp(LeaderIntegrationTest.scala:114)
      at mesosphere.marathon.integration.ReelectionLeaderIntegrationTest$$anonfun$3$$anonfun$apply$mcV$sp$6.apply(LeaderIntegrationTest.scala:114)
      at mesosphere.marathon.integration.ReelectionLeaderIntegrationTest$$anonfun$3$$anonfun$apply$mcV$sp$6.apply(LeaderIntegrationTest.scala:114)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.IntegrationTest.runTest(UnitTest.scala:86)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
      at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:86)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.IntegrationTest.run(UnitTest.scala:86)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
```

**Comment by timcharper** [comment]
https://phabricator.mesosphere.com/D522#16633

**Comment by meichstedt** [comment]
In the current implementation/test setup, zk will throw an exception every once in a while, which will lead to Marathon restarting although the process doesn't exit:

```
46778:DEBUG[20:30:04 ReelectionLeaderIntegrationTest-LocalMarathon-39501] DEBUG[20:30:04 ClientCnxn] Disconnecting client for session: 0x15a437693d10005
46779:DEBUG[20:30:04 ReelectionLeaderIntegrationTest-LocalMarathon-39501] INFO [20:30:04 ZooKeeper] Session: 0x15a437693d10005 closed
46780:DEBUG[20:30:04 ReelectionLeaderIntegrationTest-LocalMarathon-39501] INFO [20:30:04 ClientCnxn] EventThread shut down for session: 0x15a437693d10005
46781:DEBUG[20:30:04 ReelectionLeaderIntegrationTest-LocalMarathon-39501] DEBUG[20:30:04 ClientCnxn] An exception was thrown while closing send thread for session 0x15a437693d10005 : Unable to read additional data from server sessionid 0x15a437693d10005, likely server has closed socket
48766:DEBUG[20:30:23 ReelectionLeaderIntegrationTest-LocalMarathon-39501] INFO [20:30:23 MarathonApp] Starting Marathon 1.5.0-SNAPSHOT/13bc4bae6846d757f5233a34f2e55b66e9888a24
```

The IT setup is a little weird in that
1. it tests leader re-election by sending a DELETE to v2/leader instead of terminating the process
1. it tries to verify that the process exits which is an implementation detail and should not necessarily be tested here.

Changing the setup e.g. to one where the process  is simply killed led to a series of other errors. Since several people have put effort into trying to fix the flakey test, we agreed it's time to actually fix the implementation first.
