### ISSUE TITLE
marathon 1.1.2 no leader to select 503

### ISSUE THREAD

**Issue by yugongpeng** [mesosphere/marathon#5191]
[2017-02-16 10:29:00,147] ERROR error while getting current leader (mesosphere.marathon.MarathonLeaderInfo$$EnhancerByGuice$$40e9205:qtp1010311355-35647)
org.apache.zookeeper.KeeperException$SessionExpiredException: KeeperErrorCode = Session expired for /marathon/leader
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:127) ~[marathon:1.1.2]
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[marathon:1.1.2]
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1472) ~[marathon:1.1.2]
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1500) ~[marathon:1.1.2]
        at com.twitter.common.zookeeper.Group.getMemberIds(Group.java:147) ~[marathon:1.1.2]
        at mesosphere.marathon.core.leadership.CandidateImpl.getLeaderData(CandidateImpl.java:119) ~[marathon:1.1.2]
        at mesosphere.marathon.MarathonLeaderInfo$$anonfun$currentLeaderHostPort$1$$anonfun$apply$1.apply(MarathonLeaderInfo.scala:31) [marathon:1.1.2]
        at mesosphere.marathon.MarathonLeaderInfo$$anonfun$currentLeaderHostPort$1$$anonfun$apply$1.apply(MarathonLeaderInfo.scala:29) [marathon:1.1.2]
        at scala.Option.flatMap(Option.scala:171) [marathon:1.1.2]
        at mesosphere.marathon.MarathonLeaderInfo$$anonfun$currentLeaderHostPort$1.apply(MarathonLeaderInfo.scala:29) [marathon:1.1.2]
        at mesosphere.marathon.MarathonLeaderInfo$$anonfun$currentLeaderHostPort$1.apply(MarathonLeaderInfo.scala:29) [marathon:1.1.2]
        at mesosphere.marathon.metrics.Metrics$Timer.apply(Metrics.scala:100) [marathon:1.1.2]
        at mesosphere.marathon.MarathonLeaderInfo.currentLeaderHostPort(MarathonLeaderInfo.scala:28) [marathon:1.1.2]
        at mesosphere.marathon.MarathonLeaderInfo$$EnhancerByGuice$$40e9205.CGLIB$currentLeaderHostPort$3(<generated>) [marathon:1.1.2]
        at mesosphere.marathon.MarathonLeaderInfo$$EnhancerByGuice$$40e9205$$FastClassByGuice$$64fbe0dd.invoke(<generated>) [marathon:1.1.2]
        at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228) [marathon:1.1.2]
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon:1.1.2]
        at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:62) [marathon:1.1.2]
        at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:27) [marathon:1.1.2]
        at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:61) [marathon:1.1.2]
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72) [marathon:1.1.2]
        at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52) [marathon:1.1.2]
        at mesosphere.marathon.MarathonLeaderInfo$$EnhancerByGuice$$40e9205.currentLeaderHostPort(<generated>) [marathon:1.1.2]
        at mesosphere.marathon.api.LeaderProxyFilter.leaderDataOpt$lzycompute$1(LeaderProxyFilter.scala:122) [marathon:1.1.2]
        at mesosphere.marathon.api.LeaderProxyFilter.leaderDataOpt$1(LeaderProxyFilter.scala:122) [marathon:1.1.2]
        at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:128) [marathon:1.1.2]
        at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [marathon:1.1.2]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [marathon:1.1.2]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [marathon:1.1.2]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [marathon:1.1.2]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668) [marathon:1.1.2]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [marathon:1.1.2]
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158) [marathon:1.1.2]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [marathon:1.1.2]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090) [marathon:1.1.2]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [marathon:1.1.2]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon:1.1.2]
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [marathon:1.1.2]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) [marathon:1.1.2]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [marathon:1.1.2]
        at org.eclipse.jetty.server.Server.handle(Server.java:517) [marathon:1.1.2]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) [marathon:1.1.2]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [marathon:1.1.2]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) [marathon:1.1.2]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [marathon:1.1.2]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [marathon:1.1.2]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [marathon:1.1.2]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [marathon:1.1.2]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [marathon:1.1.2]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [marathon:1.1.2]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
[2017-02-16 10:29:00,149] INFO Do not proxy to myself. Waiting for consistent leadership state. Are we leader?: false, leader: None (mesosphere.marathon.api.LeaderProxyFilter$:qtp1010311355-35647)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4527. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
