### ISSUE TITLE
MigrationTest failed in tag v1.4.1

### ISSUE THREAD

**Issue by heww** [mesosphere/marathon#5228]
```bash
Run completed in 1 minute, 13 seconds.
Total number of tests run: 2879
Suites: completed 250, aborted 0
Tests: succeeded 2877, failed 2, canceled 0, ignored 1, pending 0
*** 2 TESTS FAILED ***
MigrationTest:
Migration should
- migrate on a legacy database with the same version will do nothing *** FAILED *** (64 milliseconds)
  mesosphere.marathon.MigrationFailedException: Migration Failed: null
  at mesosphere.marathon.storage.migration.Migration$$anonfun$1.applyOrElse(Migration.scala:161)
  at mesosphere.marathon.storage.migration.Migration$$anonfun$1.applyOrElse(Migration.scala:159)
  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
  at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
  at scala.util.Try$.apply(Try.scala:192)
  at scala.util.Failure.recover(Try.scala:216)
  at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
  at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
  Cause: java.lang.NullPointerException:
  at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:256)
  at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
MigrationTest:
Migration should
- initializes and closes the persistent store when performing a legacy migration *** FAILED *** (33 milliseconds)
  mesosphere.marathon.MigrationFailedException: Migration Failed: null
  at mesosphere.marathon.storage.migration.Migration$$anonfun$1.applyOrElse(Migration.scala:161)
  at mesosphere.marathon.storage.migration.Migration$$anonfun$1.applyOrElse(Migration.scala:159)
  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
  at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
  at scala.util.Try$.apply(Try.scala:192)
  at scala.util.Failure.recover(Try.scala:216)
  at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
  at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
  Cause: java.lang.NullPointerException:
  at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:256)
  at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] ScalaTest
[info] Run completed in 1 minute, 13 seconds.
[info] Total number of tests run: 2879
[info] Suites: completed 250, aborted 0
[info] Tests: succeeded 2877, failed 2, canceled 0, ignored 1, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed: Total 2879, Failed 2, Errors 0, Passed 2877, Ignored 1
[error] Failed tests:
[error] 	mesosphere.marathon.storage.migration.MigrationTest
[error] (marathon/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 376 s, completed Feb 21, 2017 4:47:05 AM
```

**Comment by unterstein** [comment]
Hi @heww!

Thanks for reporting! Your correct, that the v1.4.1 tag do not pass unit tests because of `MigrationTest`. Unfortunately the version was incremented during release process after unit tests were executed, therefore this was detected after the tag/release. We already provided a fix for these tests here #5220. 

If you have any issues with the tag non passing MigrationTest, please feel free to reach out to me or re-open the ticket.

Kind regards
Johannes
