### ISSUE TITLE
OverdueTasksActorTest is unstable

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5281]

**Comment by meichstedt** [comment]
Well ...

```
34841:          "errorStackTrace" : "\n      akka.actor.InvalidActorNameException: actor name [check] is not unique!\n      at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:129)\n      at akka.actor.dungeon.Children$class.reserveChild(Children.scala:130)\n      at akka.actor.ActorCell.reserveChild(ActorCell.scala:374)\n      at akka.actor.dungeon.Children$class.makeChild(Children.scala:268)\n      at akka.actor.dungeon.Children$class.attachChild(Children.scala:46)\n      at akka.actor.ActorCell.attachChild(ActorCell.scala:374)\n      at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:732)\n      at mesosphere.marathon.core.task.jobs.impl.OverdueTasksActorTest$Fixture.<init>(OverdueTasksActorTest.scala:34)\n      at mesosphere.marathon.core.task.jobs.impl.OverdueTasksActorTest$$anonfun$1$$anonfun$apply$mcV$sp$3$$anon$3.<init>(OverdueTasksActorTest.scala:90)\n      at mesosphere.marathon.core.task.jobs.impl.OverdueTasksActorTest$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(OverdueTasksActorTest.scala:90)\n      at mesosphere.marathon.core.task.jobs.impl.OverdueTasksActorTest$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(OverdueTasksActorTest.scala:90)\n      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)\n      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)\n      at org.scalatest.Transformer.apply(Transformer.scala:22)\n      at org.scalatest.Transformer.apply(Transformer.scala:20)\n      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)\n      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)\n      at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)\n      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)\n      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)\n      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)\n      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)\n      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)\n      at mesosphere.UnitTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:83)\n      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)\n      at mesosphere.UnitTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:83)\n      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)\n      at mesosphere.UnitTest.runTest(UnitTest.scala:83)\n      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)\n      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)\n      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)\n      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)\n      at scala.collection.immutable.List.foreach(List.scala:381)\n      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)\n      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)\n      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)\n      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)\n      at scala.collection.immutable.List.foreach(List.scala:381)\n      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)\n      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)\n      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)\n      at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)\n      at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)\n      at org.scalatest.Suite$class.run(Suite.scala:1147)\n      at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)\n      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)\n      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)\n      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)\n      at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)\n      at mesosphere.UnitTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:83)\n      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)\n      at mesosphere.UnitTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:83)\n      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)\n      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)\n      at mesosphere.UnitTest.run(UnitTest.scala:83)\n      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)\n      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)\n      at sbt.ForkMain$Run$2.call(ForkMain.java:296)\n      at sbt.ForkMain$Run$2.call(ForkMain.java:286)\n      at java.util.concurrent.FutureTask.run(FutureTask.java:266)\n      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n      at java.lang.Thread.run(Thread.java:745)\n",

```

**Comment by meichstedt** [comment]
https://phabricator.mesosphere.com/D580

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1993. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
