### ISSUE TITLE
Launch Queue Timeouts during scale tests (AskTimeoutException)

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5286]
The marathon logs are filled with launch queue timeouts during marathon scale tests

```
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]: [2017-03-01 18:25:09,582] ERROR while executing step notifyLaunchQueue for [sleeping.marathon-664d4aa6-feac-11e6-88b0-d6f67f566238], continue with other 
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]: akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://marathon/user/launchQueue#971898520]] after [1000 ms]. Sender[null] sent message of type
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at java.lang.Thread.run(Thread.java:745)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]: [2017-03-01 18:25:09,601] ERROR while executing step notifyLaunchQueue for [sleeping.marathon-66511b37-feac-11e6-88b0-d6f67f566238], continue with other 
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]: akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://marathon/user/launchQueue#971898520]] after [1000 ms]. Sender[null] sent message of type
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:329)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:280)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:284)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236)
Mar 01 18:25:09 ken-275d671b-masters-zqxx.c.massive-bliss-781.internal marathon.sh[4675]:         at java.lang.Thread.run(Thread.java:745)

```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2285. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
