### ISSUE TITLE
GroupDeployIntegrationTest is flaky

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5288]
Build:https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/master/175/

```
gine.scala:410)[0m
[31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)[0m
[31m  at scala.collection.immutable.List.foreach(List.scala:381)[0m
[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)[0m
[31m  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)[0m
[31m  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)[0m
[31m  at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)[0m
[31m  at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)[0m
[31m  at org.scalatest.Suite$class.run(Suite.scala:1147)[0m
[31m  at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)[0m
[31m  at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)[0m
[31m  at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)[0m
[31m  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)[0m
[31m  at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)[0m
[31m  at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:94)[0m
[31m  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)[0m
[31m  at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:94)[0m
[31m  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)[0m
[31m  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)[0m
[31m  at mesosphere.IntegrationTest.run(UnitTest.scala:94)[0m
[31m  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)[0m
[31m  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)[0m
[31m  at sbt.ForkMain$Run$2.call(ForkMain.java:296)[0m
[31m  at sbt.ForkMain$Run$2.call(ForkMain.java:286)[0m
[31m  at java.util.concurrent.FutureTask.run(FutureTask.java:266)[0m
[31m  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[0m
[31m  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[0m
[31m  at java.lang.Thread.run(Thread.java:745)[0m
[31m  Cause: java.lang.RuntimeException: No matching events[0m
[31m  at mesosphere.marathon.integration.setup.MarathonTest$$anonfun$waitForEventMatching$1$$anonfun$apply$19.apply(MarathonTest.scala:488)[0m
[31m  at mesosphere.marathon.integration.setup.MarathonTest$$anonfun$waitForEventMatching$1$$anonfun$apply$19.apply(MarathonTest.scala:488)[0m
[31m  at scala.Option.getOrElse(Option.scala:121)[0m
[31m  at mesosphere.marathon.integration.setup.MarathonTest$$anonfun$waitForEventMatching$1.apply(MarathonTest.scala:488)[0m
[31m  at mesosphere.marathon.integration.setup.MarathonTest$$anonfun$waitForEventMatching$1.apply(MarathonTest.scala:486)[0m
[31m  at org.scalatest.concurrent.Eventually$class.makeAValiantAttempt$1(Eventually.scala:395)[0m
[31m  at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:409)[0m
[31m  at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)[0m
[31m  at mesosphere.marathon.integration.GroupDeployIntegrationTest.eventually(GroupDeployIntegrationTest.scala:14)[0m
[31m  at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)[0m
[31m  at mesosphere.marathon.integration.GroupDeployIntegrationTest.eventually(GroupDeployIntegrationTest.scala:14)[0m
[31m  at mesosphere.marathon.integration.setup.MarathonTest$class.waitForEventMatching(MarathonTest.scala:486)[0m
[31m  at mesosphere.marathon.integration.GroupDeployIntegrationTest.waitForEventMatching(GroupDeployIntegrationTest.scala:14)[0m
[31m  at mesosphere.marathon.integration.setup.MarathonTest$class.waitForEventWith(MarathonTest.scala:467)[0m
[31m  at mesosphere.marathon.integration.GroupDeployIntegrationTest.waitForEventWith(GroupDeployIntegrationTest.scala:14)[0m
[31m  at mesosphere.marathon.integration.setup.MarathonTest$class.waitForDeploymentId(MarathonTest.scala:451)[0m
[31m  at mesosphere.marathon.integration.GroupDeployIntegrationTest.waitForDeploymentId(GroupDeployIntegrationTest.scala:14)[0m
[31m  at mesosphere.marathon.integration.setup.MarathonTest$class.waitForDeployment(MarathonTest.scala:524)[0m
[31m  at mesosphere.marathon.integration.GroupDeployIntegrationTest.waitForDeployment(GroupDeployIntegrationTest.scala:14)[0m
[31m  at mesosphere.marathon.integration.GroupDeployIntegrationTest$$anonfun$2$$anonfun$apply$mcV$sp$12.apply(GroupDeployIntegrationTest.scala:221)[0m
[31m  at mesosphere.marathon.integration.GroupDeployIntegrationTest$$anonfun$2$$anonfun$apply$mcV$sp$12.apply(GroupDeployIntegrationTest.scala:199)[0m
[31m  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)[0m
[31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m
[31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m
[31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m
[31m  at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)[0m
[31m  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)[0m
[31m  at mesosphere.IntegrationTest.mesosphere$RetryOnFailed$$super$withFixture(UnitTest.scala:94)[0m
[31m  at mesosphere.RetryOnFailed$$anonfun$withFixture$1.apply(UnitTest.scala:51)[0m
[31m  at mesosphere.RetryOnFailed$$anonfun$withFixture$1.apply(UnitTest.scala:51)[0m
[31m  at org.scalatest.Retries$class.withRetryOnFailure(Retries.scala:566)[0m
[31m  at mesosphere.IntegrationTest.withRetryOnFailure(UnitTest.scala:94)[0m
[31m  at org.scalatest.Retries$class.withRetryOnFailure(Retries.scala:462)[0m
[31m  at mesosphere.IntegrationTest.withRetryOnFailure(UnitTest.scala:94)[0m
[31m  at mesosphere.RetryOnFailed$class.withFixture(UnitTest.scala:51)[0m
[31m  at mesosphere.IntegrationTest.withFixture(UnitTest.scala:94)[0m
[31m  at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)[0m
[31m  at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)[0m
[31m  at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)[0m
[31m  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)[0m
[31m  at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)[0m
[31m  at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:94)[0m
[31m  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)[0m
[31m  at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:94)[0m
[31m  at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)[0m
[31m  at mesosphere.IntegrationTest.runTest(UnitTest.scala:94)[0m
[31m  at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)[0m
[31m  at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)[0m
[31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)[0m
[31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)[0m
[31m  at scala.collection.immutable.List.foreach(List.scala:381)[0m
[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)[0m
[31m  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)[0m
[31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)[0m
[31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)[0m
[31m  at scala.collection.immutable.List.foreach(List.scala:381)[0m
[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)[0m
[31m  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)[0m
[31m  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)[0m
[31m  at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)[0m
[31m  at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)[0m
[31m  at org.scalatest.Suite$class.run(Suite.scala:1147)[0m
[31m  at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)[0m
[31m  at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)[0m
[31m  at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)[0m
[31m  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)[0m
[31m  at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)[0m
[31m  at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:94)[0m
[31m  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)[0m
[31m  at mesosphere.IntegrationTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:94)[0m
[31m  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)[0m
[31m  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)[0m
[31m  at mesosphere.IntegrationTest.run(UnitTest.scala:94)[0m
[31m  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)[0m
[31m  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)[0m
[31m  at sbt.ForkMain$Run$2.call(ForkMain.java:296)[0m
[31m  at sbt.ForkMain$Run$2.call(ForkMain.java:286)[0m
[31m  at java.util.concurrent.FutureTask.run(FutureTask.java:266)[0m
[31m  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[0m
[31m  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[0m
[31m  at java.lang.Thread.run(Thread.java:745)[0m
[info] ScalaTest
[info] Run completed in 9 minutes, 5 seconds.
[info] Total number of tests run: 20
[info] Suites: completed 244, aborted 0
[info] Tests: succeeded 19, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 20, Failed 1, Errors 0, Passed 19
[error] Failed tests:
[error] 	mesosphere.marathon.integration.GroupDeployIntegrationTest
[error] (marathon/serial-integration:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 558 s, completed Mar 2, 2017 9:23:26 AM
´´´

**Comment by jdef** [comment]
another one: https://jenkins.mesosphere.com/service/jenkins/job/marathon-pipelines/job/master/177/

**Comment by jeschkies** [comment]
These tests fail locally 

* should upgrade a group with application with health checks
* should rollback from an upgrade of group
* should during Deployment the defined minimum health capacity is never undershot
* should An upgrade in progress cannot be interrupted without force
* should A group with a running deployment can not be deleted without force
* should Groups with Applications with circular dependencies can not get deployed
* Groups with dependencies get deployed in the correct order
* Groups with Applications with circular dependencies can not get deployed

**Comment by jeschkies** [comment]
Please see the [logs](https://phabricator.mesosphere.com/P2) for `should rollback from an upgrade of group`.

We deploy a second version. The details

version | port | taskid
--------|-----|-----
v1 | 31359 | proxy_app-e8da0740-dffd-482e-8ac7-37a59d576fb9.956ccbac-0023-11e7-923d-62f702c76f28
v2 | 31590 | proxy_app-e8da0740-dffd-482e-8ac7-37a59d576fb9.c4200e8d-0023-11e7-923d-62f702c76f28

**Comment by jeschkies** [comment]
The second version never queries for the health checks.

**Comment by jeschkies** [comment]
I was able to look at the logs of the deployed app. It is killed before any health check is made.

Further:
* Following test deployments time out. I believe this is due to a time out fetching the instance data from ZooKeeper.
* At least `rollback from an upgrade of group` generates a ton of log lines.

**Comment by jeschkies** [comment]
All tests after `rollback from an upgrade of group` and `during Deployment the defined minimum health capacity is never undershot` fail with a HTTP 503 code.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2114. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by jeschkies** [comment]
Looking at `rollback from an upgrade of group` I see after the update of the app

```
  10451 DEBUG[12:21:18 GroupDeployIntegrationTest-LocalMarathon-53677] DEBUG[12:21:18 HealthCheckWorkerActor] Performing health check for app=/temp-group-682928b8-dd94-48b7-a4bf-5541a1812a21/app-cf115618-4be5-4f7b-8920-4da16506a183 instance=instance [temp-group-682928b8-dd94-48b7-a4bf-5541a1812a21_app-cf115618-4be5-4f7b-8920-4da16506a183.marathon-210c2a5a-0328-11e7-84e1-62f702c76f28] port=None failed with exception
  10452 DEBUG[12:21:18 GroupDeployIntegrationTest-LocalMarathon-53677] akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://marathon/user/IO-HTTP#1417230881]] after [20000 ms]. Sender[null] sent message of type "spray.http.HttpRequest".
```

The app logs

```
INFO [12:21:05 AppMock] AppMock[/temp-group-682928b8-dd94-48b7-a4bf-5541a1812a21/app-cf115618-4be5-4f7b-8920-4da16506a183 v2]: temp-group-682928b8-dd94-48b7-a4bf-5541a1812a21_app-cf115618-4be5-4f7b-8920-4da16506a183.210bdc39-0328-11e7-84e1-62f702c76f28 has taken the stage at port 31940. Will query http://127.0.0.1:53800/health/temp-group-682928b8-dd94-48b7-a4bf-5541a1812a21/app-cf115618-4be5-4f7b-8920-4da16506a183/v2/31940 for health status.
DEBUG[12:21:43 LocalActorRefProvider$SystemGuardian] now supervising Actor[akka://default/system/IO-TCP#-974803524]
DEBUG[12:21:43 TcpManager] started (akka.io.TcpManager@6786657b)
...
DEBUG[12:21:43 TcpOutgoingConnection] Attempting connection to [/127.0.0.1:53800]
DEBUG[12:21:43 TcpOutgoingConnection] Connection established to [/127.0.0.1:53800]
DEBUG[12:21:43 TcpOutgoingConnection] now watched by Actor[akka://default/user/IO-HTTP/group-0/0#479257148]
AppMock[/temp-group-682928b8-dd94-48b7-a4bf-5541a1812a21/app-cf115618-4be5-4f7b-8920-4da16506a183 v2]: current health is HttpResponse(200 OK,Empty,List(Server: akka-http/10.0.1, Date: Tue, 07 Mar 2017 11:21:43 GMT, Content-Length: 0),HTTP/1.1)
```

The queries time out at 12:21:18 however the first request for the app mock comes in at 12:21:43.

**Comment by jeschkies** [comment]
Further more I see the health checks come in at batches and the integration test still replies to requests for the v1 app mock.

**Comment by jeschkies** [comment]
I tried to replace the AppMock with a Python version but get `ConnectionResetError: [Errno 54] Connection reset by peer` in the app.
