### ISSUE TITLE
Loading a huge amount of instances can take more than 10 seconds

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#5293]
Marathon gets elected and tries to load the state from zk.
It abdicates, since it is not able to load all the instances in time.
(50.000 instances in this example)

```
INFO  About to load 50000 tasks (mesosphere.marathon.core.task.tracker.impl.InstancesLoaderImpl:ForkJoinPool-2-worker-15)
ERROR while loading tasks (akka.actor.OneForOneStrategy:marathon-akka.actor.default-dispatcher-14)
java.lang.IllegalStateException: while loading tasks
        at mesosphere.marathon.core.task.tracker.impl.InstanceTrackerActor$$anonfun$initializing$1.applyOrElse(InstanceTrackerActor.scala:111)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at mesosphere.marathon.core.task.tracker.impl.InstanceTrackerActor.aroundReceive(InstanceTrackerActor.scala:70)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: mesosphere.marathon.util.TimeoutException: Timed out after 10 seconds
        at mesosphere.marathon.util.Timeout$$anonfun$1.apply$mcV$sp(Timeout.scala:45)
        at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        ... 4 common frames omitted

```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1727. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
