### ISSUE TITLE
ActorOfferMatcherTest "when the actor takes too long to process should receive a no match after deadline" is unstable

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5294]
when_the_actor_takes_too_long_to_process_should_receive_a_no_match_after_deadline

https://jenkins.mesosphere.com/service/jenkins/job/public-test-marathon-phabricator/1590/testReport/junit/mesosphere.marathon.core.matcher.base.util/ActorOfferMatcherTest/The_ActorOfferMatcher_when_the_actor_takes_too_long_to_process_should_receive_a_no_match_after_deadline/

# Error Message

```
MatchedInstanceOps(value: "other-2"&#010;,List(),true) was not equal to MatchedInstanceOps(value: "1"&#010;,List(),false)
```

# Stacktrace

```
      org.scalatest.exceptions.TestFailedException: MatchedInstanceOps(value: "other-2"
,List(),true) was not equal to MatchedInstanceOps(value: "1"
,List(),false)
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
      at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
      at mesosphere.marathon.core.matcher.base.util.ActorOfferMatcherTest$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$6.apply(ActorOfferMatcherTest.scala:98)
      at mesosphere.marathon.core.matcher.base.util.ActorOfferMatcherTest$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$6.apply(ActorOfferMatcherTest.scala:98)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
      at mesosphere.UnitTest.org$scalatest$BeforeAndAfter$$super$runTest(UnitTest.scala:71)
      at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
      at mesosphere.UnitTest.org$scalatest$BeforeAndAfterEach$$super$runTest(UnitTest.scala:71)
      at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
      at mesosphere.UnitTest.runTest(UnitTest.scala:71)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:381)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
      at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
      at mesosphere.UnitTest.org$scalatest$BeforeAndAfter$$super$run(UnitTest.scala:71)
      at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
      at mesosphere.UnitTest.org$scalatest$BeforeAndAfterAll$$super$run(UnitTest.scala:71)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at mesosphere.UnitTest.run(UnitTest.scala:71)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
      at sbt.ForkMain$Run$2.call(ForkMain.java:296)
      at sbt.ForkMain$Run$2.call(ForkMain.java:286)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
```

**Comment by jeschkies** [comment]
Closed by https://github.com/mesosphere/marathon/commit/3a4f77278fe7071b347a4d24de3410707b2edca5.
