### ISSUE TITLE
InfoIntegrationTest fails due to timeout

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5306]
```
[31m*** 1 SUITE ABORTED ***[0m
[31mInfoIntegrationTest:[0m
[31m *** ABORTED *** (1 minute, 41 seconds)[0m
[31m  The future returned an exception of type: mesosphere.marathon.util.TimeoutException, with message: Timed out after 1 minutes 30 seconds. (MarathonTest.scala:607)[0m
[31m  org.scalatest.exceptions.TestFailedException:[0m
[31m  at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:523)[0m
[31m  at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)[0m
[31m  at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)[0m
[31m  at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:394)[0m
[31m  at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)[0m
[31m  at mesosphere.marathon.integration.setup.LocalMarathonTest$class.beforeAll(MarathonTest.scala:607)[0m
[31m  at mesosphere.marathon.integration.InfoIntegrationTest.beforeAll(InfoIntegrationTest.scala:8)[0m
[31m  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)[0m
[31m  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)[0m
[31m  at mesosphere.IntegrationTest.run(UnitTest.scala:112)[0m
[31m  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)[0m
[31m  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)[0m
[31m  at sbt.ForkMain$Run$2.call(ForkMain.java:296)[0m
[31m  at sbt.ForkMain$Run$2.call(ForkMain.java:286)[0m
[31m  at java.util.concurrent.FutureTask.run(FutureTask.java:266)[0m
[31m  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[0m
[31m  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[0m
[31m  at java.lang.Thread.run(Thread.java:745)[0m
[31m  Cause: mesosphere.marathon.util.TimeoutException: Timed out after 1 minutes 30 seconds[0m
[31m  at mesosphere.marathon.util.Timeout$$anonfun$1.apply$mcV$sp(Timeout.scala:52)[0m
[31m  at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)[0m
[31m  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)[0m
[31m  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)[0m
[31m  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)[0m
[31m  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)[0m
[31m  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)[0m
[31m  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Suggestion resolution is to increase timeout. Justification: aspectJ weaving is slow

**Comment by marcomonaco** [comment]
Shouldn't this be blocker for 1.4.2?

**Comment by marcomonaco** [comment]
Moved to https://jira.mesosphere.com/browse/MARATHON-6987
