### ISSUE TITLE
MarathonSchedulerActorTest failed (flake)

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5307]
```
[36mTests: succeeded 2906, failed 1, canceled 0, ignored 1, pending 0[0m
[31m*** 1 TEST FAILED ***[0m
[31mMarathonSchedulerActorTest:[0m

[31m- Restart deployments after failover *** FAILED *** (52 milliseconds)[0m
[31m  java.lang.AssertionError: assertion failed: expected class mesosphere.marathon.MarathonSchedulerActor$CommandFailed, found class mesosphere.marathon.MarathonSchedulerActor$DeploymentStarted (DeploymentStarted(DeploymentPlan id=a28678ad-a478-4c24-87e2-082ae10e763a,2017-03-06T16:19:38.243Z[0m
[31mstep 1:[0m
[31m  * Start(App(app1, cmd="cmd"List())), instances=0)[0m
[31mstep 2:[0m
[31m  * Scale(App(app1, cmd="cmd"List())), instances=2)[0m
[31m))[0m
[31m  at scala.Predef$.assert(Predef.scala:170)[0m
[31m  at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:473)[0m
[31m  at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:445)[0m
[31m  at mesosphere.marathon.MarathonSchedulerActorTest.expectMsgType(MarathonSchedulerActorTest.scala:38)[0m
[31m  at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$18.apply(MarathonSchedulerActorTest.scala:450)[0m
[31m  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)[0m
[31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m
[31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m
[31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m
[31m  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)[0m
[31m  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)[0m
[31m  at mesosphere.marathon.MarathonSchedulerActorTest.withFixture(MarathonSchedulerActorTest.scala:38)[0m
[31m  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)[0m
[31m  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)[0m
[31m  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)[0m
[31m  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)[0m
[31m  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)[0m
[31m  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$runTest(MarathonSchedulerActorTest.scala:38)[0m
[31m  at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)[0m
[31m  at mesosphere.marathon.MarathonSchedulerActorTest.runTest(MarathonSchedulerActorTest.scala:38)[0m
[31m  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)[0m
[31m  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)[0m
[31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)[0m
[31m  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)[0m
[31m  at scala.collection.immutable.List.foreach(List.scala:381)[0m
[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)[0m
[31m  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)[0m
[31m  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)[0m
[31m  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)[0m
[31m  at mesosphere.marathon.MarathonSchedulerActorTest.runTests(MarathonSchedulerActorTest.scala:38)[0m
[31m  at org.scalatest.Suite$class.run(Suite.scala:1147)[0m
[31m  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$FunSuiteLike$$super$run(MarathonSchedulerActorTest.scala:38)[0m
[31m  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)[0m
[31m  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)[0m
[31m  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)[0m
[31m  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)[0m
[31m  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfter$$super$run(MarathonSchedulerActorTest.scala:38)[0m
[31m  at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)[0m
[31m  at mesosphere.marathon.MarathonSchedulerActorTest.org$scalatest$BeforeAndAfterAll$$super$run(MarathonSchedulerActorTest.scala:38)[0m
[31m  at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)[0m
[31m  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)[0m
[31m  at mesosphere.marathon.MarathonSchedulerActorTest.run(MarathonSchedulerActorTest.scala:38)[0m
[31m  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)[0m
[31m  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)[0m
[31m  at sbt.ForkMain$Run$2.call(ForkMain.java:296)[0m
[31m  at sbt.ForkMain$Run$2.call(ForkMain.java:286)[0m
[31m  at java.util.concurrent.FutureTask.run(FutureTask.java:266)[0m
[31m  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[0m
[31m  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[0m
[31m  at java.lang.Thread.run(Thread.java:745)[0m
[0m[[0minfo[0m] [0mScalaTest[0m
[0m[[0minfo[0m] [0m[36mRun completed in 26 seconds, 362 milliseconds.[0m[0m
[0m[[0minfo[0m] [0m[36mTotal number of tests run: 2907[0m[0m
[0m[[0minfo[0m] [0m[36mSuites: completed 255, aborted 0[0m[0m
[0m[[0minfo[0m] [0m[36mTests: succeeded 2906, failed 1, canceled 0, ignored 1, pending 0[0m[0m
[0m[[0minfo[0m] [0m[31m*** 1 TEST FAILED ***[0m[0m
[0m[[31merror[0m] [0mFailed: Total 2907, Failed 1, Errors 0, Passed 2906, Ignored 1[0m
[0m[[31merror[0m] [0mFailed tests:[0m
[0m[[31merror[0m] [0m	mesosphere.marathon.MarathonSchedulerActorTest[0m
[0m[[31merror[0m] [0m(marathon/test:[31mtest[0m) sbt.TestsFailedException: Tests unsuccessful[0m
[0m[[31merror[0m] [0mTotal time: 175 s, completed Mar 6, 2017 4:19:59 PM[0m
```

**Comment by marcomonaco** [comment]
Shouldn't this be blocker for 1.4.2?

**Comment by marcomonaco** [comment]
Moved to here: https://jira.mesosphere.com/browse/MARATHON-6986
