### ISSUE TITLE
rewrite proxy filter

### ISSUE THREAD

**Issue by drexin** [mesosphere/marathon#828]
Currently the proxy filter has several issues:

- it changes headers
- it uses blocking IO without timeouts (see #1541)
- it handles requests as if the current instance was the master, when it does not know the real master (see #1540)

**Comment by kolloch** [comment]
Case in point, an unresponsive Marathon instance in our test cluster showed a lot of these stack traces in a thread dump:

```
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: "qtp1656012274-16757" prio=10 tid=0x00007f6c24029800 nid=0x2
223 runnable [0x00007f6d5e6e4000]
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: java.lang.Thread.State: RUNNABLE
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at java.net.SocketInputStream.socketRead0(Native Method)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at java.net.SocketInputStream.read(SocketInputStream.java:152)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at java.net.SocketInputStream.read(SocketInputStream.java:122)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: - locked <0x00000000e1880b18> (a java.io.BufferedInputStream)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1324)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: - locked <0x00000000e1880bb0> (a sun.net.www.protocol.http.HttpURLConnection)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:94)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at com.codahale.metrics.jetty8.InstrumentedHandler.handle(InstrumentedHandler.java:192)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.Server.handle(Server.java:370)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
Mar 23 18:34:22 srv4.hw.ca1.mesosphere.com marathon[9935]: at java.lang.Thread.run(Thread.java:745)
```

Maybe, instead of integrating a solid proxying implementation, we can think of alternatives:

* Delegating the the proxying to a dedicated proxy which we make easy to startup and configure.
* Use redirects (as the Mesos UI does)

Of course, both of these solutions have other disadvantages. Mostly convenience.

**Comment by kolloch** [comment]
#726 might be related
