### ISSUE TITLE
Flaky test in MarathonSchedulerActorTest

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#946]
Observed the following spurious error from Travis CI.

```
[info] - Restart deployments after failover *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class mesosphere.marathon.MarathonSchedulerActor$CommandFailed
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:423)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:396)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:718)
[info]   at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$7.apply$mcV$sp(MarathonSchedulerActorTest.scala:331)
[info]   at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$7.apply(MarathonSchedulerActorTest.scala:298)
[info]   at mesosphere.marathon.MarathonSchedulerActorTest$$anonfun$7.apply(MarathonSchedulerActorTest.scala:298)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
```

**Comment by drexin** [comment]
Related exception:

```
[ERROR] [01/07/2015 16:56:44.896] [System-akka.actor.default-dispatcher-2] [akka.dispatch.Dispatcher] null
java.lang.NullPointerException
	at mesosphere.marathon.MarathonSchedulerActor$$anonfun$mesosphere$marathon$MarathonSchedulerActor$$lockNotAvailable$1$1$$anonfun$apply$mcV$sp$2.apply(MarathonSchedulerActor.scala:207)
	at mesosphere.marathon.MarathonSchedulerActor$$anonfun$mesosphere$marathon$MarathonSchedulerActor$$lockNotAvailable$1$1$$anonfun$apply$mcV$sp$2.apply(MarathonSchedulerActor.scala:202)
	at scala.util.Success.foreach(Try.scala:235)
	at scala.concurrent.Future$$anonfun$foreach$1.apply(Future.scala:204)
	at scala.concurrent.Future$$anonfun$foreach$1.apply(Future.scala:204)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
