### ISSUE TITLE
Upgrading from 0.7.6 to 0.7.7

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#995]
See more context here: https://github.com/mesosphere/marathon/issues/955#issuecomment-69155859

0.7.3 have an issue when deployment is stuck at "RestartApplication" even if no tasks are scheduled.

I decided to give 0.7.7-SNAPSHOT another try. I upgraded 0.7.3 -> 0.7.6 -> 0.7.7 (full cluster restart, not rolling). Here what happened on new master:

```
[2015-01-14 12:28:47,738] INFO Received status update for task topface_docker_registry-mirror.17340386-9be8-11e4-89cc-56847afe9799: TASK_RUNNING (Reconciliation: Latest task state) (mesosphere.marathon.MarathonScheduler:148)
java.lang.IllegalArgumentException: requirement failed: Path is not absolute. Can not create safe path.
	at scala.Predef$.require(Predef.scala:219)
	at mesosphere.marathon.state.PathId.safePath(PathId.scala:52)
	at mesosphere.marathon.state.AppRepository.app(AppRepository.scala:23)
	at mesosphere.marathon.MarathonScheduler$$anonfun$statusUpdate$5.apply(MarathonScheduler.scala:181)
	at mesosphere.marathon.MarathonScheduler$$anonfun$statusUpdate$5.apply(MarathonScheduler.scala:179)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

No apps are shown in UI or present in API, but tasks are there.

I built image from #925, rebased against latest master.

**Comment by bobrik** [comment]
I tried to run marathon 0.7.7 with different zk node. After deploying first app I get the same error in logs:

```
[2015-01-14 12:46:44,988] INFO Received status update for task topface_lenny_whatever.6530201a-9beb-11e4-a315-56847afe9799: TASK_RUNNING () (mesosphere.marathon.MarathonScheduler:148)
java.lang.IllegalArgumentException: requirement failed: Path is not absolute. Can not create safe path.
	at scala.Predef$.require(Predef.scala:219)
	at mesosphere.marathon.state.PathId.safePath(PathId.scala:52)
	at mesosphere.marathon.state.AppRepository.app(AppRepository.scala:23)
	at mesosphere.marathon.MarathonScheduler$$anonfun$statusUpdate$5.apply(MarathonScheduler.scala:181)
	at mesosphere.marathon.MarathonScheduler$$anonfun$statusUpdate$5.apply(MarathonScheduler.scala:179)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

but marathon works as it should. App is scheduled and tasks are running. Killing all tasks works as expected too: all tasks are rescheduled.

Another strange thing in logs:

```
[2015-01-14 12:49:21,577] INFO No matching offer for /topface/lenny/whatever (need cpus=0.2, mem=64.0, disk=0.0, ports=List(12001)) : id {
  value: "20150113-074256-3892422848-5050-1-O4200706"
}
framework_id {
  value: "20150113-074256-3892422848-5050-1-0003"
}
slave_id {
  value: "20150104-100017-3909200064-5050-1-S4"
}
hostname: "web365"
resources {
  name: "cpus"
  type: SCALAR
  scalar {
    value: 7.8
  }
  role: "*"
}
resources {
  name: "mem"
  type: SCALAR
  scalar {
    value: 6872.0
  }
  role: "*"
}
resources {
  name: "disk"
  type: SCALAR
  scalar {
    value: 448015.0
  }
  role: "*"
}
resources {
  name: "ports"
  type: RANGES
  ranges {
    range {
      begin: 31000
      end: 31471
    }
    range {
      begin: 31473
      end: 32000
    }
  }
  role: "*"
}
 (mesosphere.mesos.TaskBuilder:47)
```

5/5 tasks for single app are running and healthy, but marathon tries to match offers.

**Comment by bobrik** [comment]
Tried to run docker image that takes 1.8gb on disk. Marathon scheduled task, task moved to state `FAILED` after some time.

Slave logs:

```
E0114 13:11:53.822912     7 slave.cpp:2787] Container '0c4d000a-afc3-4deb-aeb6-e3c8b42892b2' for executor 'topface_prod-test_app.c4f59dac-9bee-11e4-a315-56847afe9799' of framework '20150113-074256-3892422848-5050-1-0003' failed to start:  future discarded
E0114 13:11:53.823235     7 slave.cpp:2882] Termination of executor 'topface_prod-test_app.c4f59dac-9bee-11e4-a315-56847afe9799' of framework '20150113-074256-3892422848-5050-1-0003' failed: Unknown container: 0c4d000a-afc3-4deb-aeb6-e3c8b42892b2
E0114 13:11:53.823521    11 slave.cpp:3134] Failed to unmonitor container for executor topface_prod-test_app.c4f59dac-9bee-11e4-a315-56847afe9799 of framework 20150113-074256-3892422848-5050-1-0003: Not monitored
W0114 13:11:53.845448     7 docker.cpp:1184] Ignoring updating unknown container: 0c4d000a-afc3-4deb-aeb6-e3c8b42892b
```

Marathon logs:

```
[2015-01-14 13:11:53,924] INFO Received status update for task topface_prod-test_app.c4f59dac-9bee-11e4-a315-56847afe9799: TASK_FAILED (Abnormal executor termination) (mesosphere.marathon.MarathonScheduler:148)
[2015-01-14 13:11:53,929] INFO Task launch delay for [/topface/prod-test/app] is now [1] seconds (mesosphere.util.RateLimiter:34)
[2015-01-14 13:11:53,931] INFO Task topface_prod-test_app.c4f59dac-9bee-11e4-a315-56847afe9799 expunged and removed from TaskTracker (mesosphere.marathon.tasks.TaskTracker:101)
[2015-01-14 13:11:53,931] INFO Sending event notification. (mesosphere.marathon.MarathonScheduler:261)
[2015-01-14 13:11:53,959] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999180 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,959] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999519 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,960] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999997589 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,960] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999563 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,960] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999576 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,961] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999612 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,961] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999572 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,961] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999445 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,962] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999595 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,962] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999641 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,962] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999544 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,962] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999637 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,963] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999477 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,963] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999421 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,963] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999470 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,963] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999548 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,964] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999606 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,964] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999620 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,964] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999601 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,965] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999527 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,965] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999642 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,965] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999645 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,965] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999441 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,966] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999557 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,966] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999601 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,966] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999623 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,967] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999559 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:53,967] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999454 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:54,759] INFO 172.17.0.29 -  -  [14/Jan/2015:13:11:54 +0000] "GET /v2/tasks HTTP/1.1" 200 12 "-" "Go 1.1 package http" (mesosphere.chaos.http.ChaosRequestLog:15)
[2015-01-14 13:11:55,005] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999072 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,005] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999603 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,005] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999570 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,006] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999523 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,006] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999481 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,006] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999643 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,006] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999635 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,007] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999522 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,007] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999668 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,007] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999649 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,008] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999680 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,008] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999585 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,008] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999650 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,008] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999579 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,009] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999630 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,009] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999550 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,009] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999660 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,009] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999648 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,010] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999656 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,010] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999643 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,010] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999636 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,010] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999595 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,011] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999666 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,011] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999662 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,011] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999663 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,011] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999654 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,012] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999652 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,012] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999646 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,012] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999678 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,012] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999638 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,013] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999662 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,013] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999638 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
[2015-01-14 13:11:55,013] INFO Delaying /topface/prod-test/app due to backoff. Time left: 999999590 nanoseconds. (mesosphere.marathon.tasks.TaskQueue:108)
```

Logs continue to assure me that task is going to be rescheduled in ~1s, but that is not happening:

```
web13 ~ # docker logs 4c | fgrep -v 'due to backoff' | fgrep -v v2/tasks | tail -n5
[2015-01-14 13:11:53,929] INFO Task launch delay for [/topface/prod-test/app] is now [1] seconds (mesosphere.util.RateLimiter:34)
[2015-01-14 13:11:53,931] INFO Task topface_prod-test_app.c4f59dac-9bee-11e4-a315-56847afe9799 expunged and removed from TaskTracker (mesosphere.marathon.tasks.TaskTracker:101)
[2015-01-14 13:11:53,931] INFO Sending event notification. (mesosphere.marathon.MarathonScheduler:261)
[2015-01-14 13:16:36,419] INFO Syncing tasks for all apps (mesosphere.marathon.SchedulerActions:397)
[2015-01-14 13:16:36,419] INFO Requesting task reconciliation with the Mesos master (mesosphere.marathon.SchedulerActions:419)
```

**Comment by drexin** [comment]
Hi Ian,

please try if this PR fixes your problem: https://github.com/mesosphere/marathon/pull/996

Thanks!

**Comment by rasputnik** [comment]
You've requested a specific port that isn't in the offered range from
mesos, so this app will never deploy.

**Comment by drexin** [comment]
@rasputnik Is right. The PR I referenced above should fix the issue you described first.

**Comment by bobrik** [comment]
@drexin I'm building image now.

Did port allocation logic changed in 0.7.3+? I request service port, not a real port. Marathon picks random port to run my task on and my service discovery connects service port to actual port. I have several apps that run on ports 12000..15000 and they all are working just fine in 0.7.3.

**Comment by bobrik** [comment]
Moreover, marathon did start my tasks even in 0.7.7-SNAPSHOT, so you are probably wrong about port.

**Comment by bobrik** [comment]
@drexin #966 fixed problem with `Path is not absolute. Can not create safe path.` for fresh installation. I didn't check if it's gone for 0.7.3 -> 0.7.7 migration, though.

Shall I create different issues for endless offer matching and infinite delay for failed tasks?

**Comment by drexin** [comment]
Great. It should also fix it when upgrading from older versions, as it has been a bug only in the extraction of an app id from a task id.

**Comment by bobrik** [comment]
@drexin 

> Shall I create different issues for endless offer matching and infinite delay for failed tasks?

**Comment by drexin** [comment]
Yes, please.
